
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SubRubros](
	[IdSubRubro] [int] NOT NULL,
	[NombreSubRubro] [varchar](50) NOT NULL,
	[DescuentoRecargo] [decimal](5, 2) NOT NULL,
 CONSTRAINT [PK_SubRubros] PRIMARY KEY CLUSTERED 
(
	[IdSubRubro] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


