/****** Object:  Index [IX_Clientes]    Script Date: 29/04/2019 10:58:39 ******/
ALTER TABLE [dbo].[Clientes] ADD  CONSTRAINT [IX_Clientes] UNIQUE NONCLUSTERED ([CodigoCliente] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
