'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WSBFE
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private BFEAuthorizeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEGetCMPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEGetPARAM_Tipo_docOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEGetPARAM_Tipo_IVAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEGetPARAM_ZonasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEGetPARAM_Tipo_CbteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEGetPARAM_UMedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEGetPARAM_NCMOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEGetPARAM_MONOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEGetLast_CMPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEDummyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BFEGetLast_IDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Eniac.Reglas.My.MySettings.Default.Eniac_Reglas_WSBFE_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event BFEAuthorizeCompleted As BFEAuthorizeCompletedEventHandler
        
        '''<remarks/>
        Public Event BFEGetCMPCompleted As BFEGetCMPCompletedEventHandler
        
        '''<remarks/>
        Public Event BFEGetPARAM_Tipo_docCompleted As BFEGetPARAM_Tipo_docCompletedEventHandler
        
        '''<remarks/>
        Public Event BFEGetPARAM_Tipo_IVACompleted As BFEGetPARAM_Tipo_IVACompletedEventHandler
        
        '''<remarks/>
        Public Event BFEGetPARAM_ZonasCompleted As BFEGetPARAM_ZonasCompletedEventHandler
        
        '''<remarks/>
        Public Event BFEGetPARAM_Tipo_CbteCompleted As BFEGetPARAM_Tipo_CbteCompletedEventHandler
        
        '''<remarks/>
        Public Event BFEGetPARAM_UMedCompleted As BFEGetPARAM_UMedCompletedEventHandler
        
        '''<remarks/>
        Public Event BFEGetPARAM_NCMCompleted As BFEGetPARAM_NCMCompletedEventHandler
        
        '''<remarks/>
        Public Event BFEGetPARAM_MONCompleted As BFEGetPARAM_MONCompletedEventHandler
        
        '''<remarks/>
        Public Event BFEGetLast_CMPCompleted As BFEGetLast_CMPCompletedEventHandler
        
        '''<remarks/>
        Public Event BFEDummyCompleted As BFEDummyCompletedEventHandler
        
        '''<remarks/>
        Public Event BFEGetLast_IDCompleted As BFEGetLast_IDCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEAuthorize", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEAuthorize(ByVal Auth As ClsBFEAuthRequest, ByVal Cmp As ClsBFERequest) As BFEResponseAuthorize
            Dim results() As Object = Me.Invoke("BFEAuthorize", New Object() {Auth, Cmp})
            Return CType(results(0),BFEResponseAuthorize)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEAuthorizeAsync(ByVal Auth As ClsBFEAuthRequest, ByVal Cmp As ClsBFERequest)
            Me.BFEAuthorizeAsync(Auth, Cmp, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEAuthorizeAsync(ByVal Auth As ClsBFEAuthRequest, ByVal Cmp As ClsBFERequest, ByVal userState As Object)
            If (Me.BFEAuthorizeOperationCompleted Is Nothing) Then
                Me.BFEAuthorizeOperationCompleted = AddressOf Me.OnBFEAuthorizeOperationCompleted
            End If
            Me.InvokeAsync("BFEAuthorize", New Object() {Auth, Cmp}, Me.BFEAuthorizeOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEAuthorizeOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEAuthorizeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEAuthorizeCompleted(Me, New BFEAuthorizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetCMP", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEGetCMP(ByVal Auth As ClsBFEAuthRequest, ByVal Cmp As ClsBFEGetCMP) As BFEGetCMPResponse
            Dim results() As Object = Me.Invoke("BFEGetCMP", New Object() {Auth, Cmp})
            Return CType(results(0),BFEGetCMPResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEGetCMPAsync(ByVal Auth As ClsBFEAuthRequest, ByVal Cmp As ClsBFEGetCMP)
            Me.BFEGetCMPAsync(Auth, Cmp, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEGetCMPAsync(ByVal Auth As ClsBFEAuthRequest, ByVal Cmp As ClsBFEGetCMP, ByVal userState As Object)
            If (Me.BFEGetCMPOperationCompleted Is Nothing) Then
                Me.BFEGetCMPOperationCompleted = AddressOf Me.OnBFEGetCMPOperationCompleted
            End If
            Me.InvokeAsync("BFEGetCMP", New Object() {Auth, Cmp}, Me.BFEGetCMPOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEGetCMPOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEGetCMPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEGetCMPCompleted(Me, New BFEGetCMPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_Tipo_doc", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEGetPARAM_Tipo_doc(ByVal auth As ClsBFEAuthRequest) As BFEResponse_Tipo_doc
            Dim results() As Object = Me.Invoke("BFEGetPARAM_Tipo_doc", New Object() {auth})
            Return CType(results(0),BFEResponse_Tipo_doc)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_Tipo_docAsync(ByVal auth As ClsBFEAuthRequest)
            Me.BFEGetPARAM_Tipo_docAsync(auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_Tipo_docAsync(ByVal auth As ClsBFEAuthRequest, ByVal userState As Object)
            If (Me.BFEGetPARAM_Tipo_docOperationCompleted Is Nothing) Then
                Me.BFEGetPARAM_Tipo_docOperationCompleted = AddressOf Me.OnBFEGetPARAM_Tipo_docOperationCompleted
            End If
            Me.InvokeAsync("BFEGetPARAM_Tipo_doc", New Object() {auth}, Me.BFEGetPARAM_Tipo_docOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEGetPARAM_Tipo_docOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEGetPARAM_Tipo_docCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEGetPARAM_Tipo_docCompleted(Me, New BFEGetPARAM_Tipo_docCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_Tipo_IVA", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEGetPARAM_Tipo_IVA(ByVal auth As ClsBFEAuthRequest) As BFEResponse_Tipo_IVA
            Dim results() As Object = Me.Invoke("BFEGetPARAM_Tipo_IVA", New Object() {auth})
            Return CType(results(0),BFEResponse_Tipo_IVA)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_Tipo_IVAAsync(ByVal auth As ClsBFEAuthRequest)
            Me.BFEGetPARAM_Tipo_IVAAsync(auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_Tipo_IVAAsync(ByVal auth As ClsBFEAuthRequest, ByVal userState As Object)
            If (Me.BFEGetPARAM_Tipo_IVAOperationCompleted Is Nothing) Then
                Me.BFEGetPARAM_Tipo_IVAOperationCompleted = AddressOf Me.OnBFEGetPARAM_Tipo_IVAOperationCompleted
            End If
            Me.InvokeAsync("BFEGetPARAM_Tipo_IVA", New Object() {auth}, Me.BFEGetPARAM_Tipo_IVAOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEGetPARAM_Tipo_IVAOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEGetPARAM_Tipo_IVACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEGetPARAM_Tipo_IVACompleted(Me, New BFEGetPARAM_Tipo_IVACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_Zonas", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEGetPARAM_Zonas(ByVal auth As ClsBFEAuthRequest) As BFEResponse_Zon
            Dim results() As Object = Me.Invoke("BFEGetPARAM_Zonas", New Object() {auth})
            Return CType(results(0),BFEResponse_Zon)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_ZonasAsync(ByVal auth As ClsBFEAuthRequest)
            Me.BFEGetPARAM_ZonasAsync(auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_ZonasAsync(ByVal auth As ClsBFEAuthRequest, ByVal userState As Object)
            If (Me.BFEGetPARAM_ZonasOperationCompleted Is Nothing) Then
                Me.BFEGetPARAM_ZonasOperationCompleted = AddressOf Me.OnBFEGetPARAM_ZonasOperationCompleted
            End If
            Me.InvokeAsync("BFEGetPARAM_Zonas", New Object() {auth}, Me.BFEGetPARAM_ZonasOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEGetPARAM_ZonasOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEGetPARAM_ZonasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEGetPARAM_ZonasCompleted(Me, New BFEGetPARAM_ZonasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_Tipo_Cbte", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEGetPARAM_Tipo_Cbte(ByVal auth As ClsBFEAuthRequest) As BFEResponse_Tipo_Cbte
            Dim results() As Object = Me.Invoke("BFEGetPARAM_Tipo_Cbte", New Object() {auth})
            Return CType(results(0),BFEResponse_Tipo_Cbte)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_Tipo_CbteAsync(ByVal auth As ClsBFEAuthRequest)
            Me.BFEGetPARAM_Tipo_CbteAsync(auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_Tipo_CbteAsync(ByVal auth As ClsBFEAuthRequest, ByVal userState As Object)
            If (Me.BFEGetPARAM_Tipo_CbteOperationCompleted Is Nothing) Then
                Me.BFEGetPARAM_Tipo_CbteOperationCompleted = AddressOf Me.OnBFEGetPARAM_Tipo_CbteOperationCompleted
            End If
            Me.InvokeAsync("BFEGetPARAM_Tipo_Cbte", New Object() {auth}, Me.BFEGetPARAM_Tipo_CbteOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEGetPARAM_Tipo_CbteOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEGetPARAM_Tipo_CbteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEGetPARAM_Tipo_CbteCompleted(Me, New BFEGetPARAM_Tipo_CbteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_UMed", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEGetPARAM_UMed(ByVal auth As ClsBFEAuthRequest) As BFEResponse_Umed
            Dim results() As Object = Me.Invoke("BFEGetPARAM_UMed", New Object() {auth})
            Return CType(results(0),BFEResponse_Umed)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_UMedAsync(ByVal auth As ClsBFEAuthRequest)
            Me.BFEGetPARAM_UMedAsync(auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_UMedAsync(ByVal auth As ClsBFEAuthRequest, ByVal userState As Object)
            If (Me.BFEGetPARAM_UMedOperationCompleted Is Nothing) Then
                Me.BFEGetPARAM_UMedOperationCompleted = AddressOf Me.OnBFEGetPARAM_UMedOperationCompleted
            End If
            Me.InvokeAsync("BFEGetPARAM_UMed", New Object() {auth}, Me.BFEGetPARAM_UMedOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEGetPARAM_UMedOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEGetPARAM_UMedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEGetPARAM_UMedCompleted(Me, New BFEGetPARAM_UMedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_NCM", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEGetPARAM_NCM(ByVal Auth As ClsBFEAuthRequest) As BFEResponse_NCM
            Dim results() As Object = Me.Invoke("BFEGetPARAM_NCM", New Object() {Auth})
            Return CType(results(0),BFEResponse_NCM)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_NCMAsync(ByVal Auth As ClsBFEAuthRequest)
            Me.BFEGetPARAM_NCMAsync(Auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_NCMAsync(ByVal Auth As ClsBFEAuthRequest, ByVal userState As Object)
            If (Me.BFEGetPARAM_NCMOperationCompleted Is Nothing) Then
                Me.BFEGetPARAM_NCMOperationCompleted = AddressOf Me.OnBFEGetPARAM_NCMOperationCompleted
            End If
            Me.InvokeAsync("BFEGetPARAM_NCM", New Object() {Auth}, Me.BFEGetPARAM_NCMOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEGetPARAM_NCMOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEGetPARAM_NCMCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEGetPARAM_NCMCompleted(Me, New BFEGetPARAM_NCMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_MON", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEGetPARAM_MON(ByVal auth As ClsBFEAuthRequest) As BFEResponse_Mon
            Dim results() As Object = Me.Invoke("BFEGetPARAM_MON", New Object() {auth})
            Return CType(results(0),BFEResponse_Mon)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_MONAsync(ByVal auth As ClsBFEAuthRequest)
            Me.BFEGetPARAM_MONAsync(auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEGetPARAM_MONAsync(ByVal auth As ClsBFEAuthRequest, ByVal userState As Object)
            If (Me.BFEGetPARAM_MONOperationCompleted Is Nothing) Then
                Me.BFEGetPARAM_MONOperationCompleted = AddressOf Me.OnBFEGetPARAM_MONOperationCompleted
            End If
            Me.InvokeAsync("BFEGetPARAM_MON", New Object() {auth}, Me.BFEGetPARAM_MONOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEGetPARAM_MONOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEGetPARAM_MONCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEGetPARAM_MONCompleted(Me, New BFEGetPARAM_MONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetLast_CMP", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEGetLast_CMP(ByVal Auth As ClsBFE_LastCMP) As BFEResponseLast_CMP
            Dim results() As Object = Me.Invoke("BFEGetLast_CMP", New Object() {Auth})
            Return CType(results(0),BFEResponseLast_CMP)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEGetLast_CMPAsync(ByVal Auth As ClsBFE_LastCMP)
            Me.BFEGetLast_CMPAsync(Auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEGetLast_CMPAsync(ByVal Auth As ClsBFE_LastCMP, ByVal userState As Object)
            If (Me.BFEGetLast_CMPOperationCompleted Is Nothing) Then
                Me.BFEGetLast_CMPOperationCompleted = AddressOf Me.OnBFEGetLast_CMPOperationCompleted
            End If
            Me.InvokeAsync("BFEGetLast_CMP", New Object() {Auth}, Me.BFEGetLast_CMPOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEGetLast_CMPOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEGetLast_CMPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEGetLast_CMPCompleted(Me, New BFEGetLast_CMPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEDummy", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEDummy() As DummyResponse
            Dim results() As Object = Me.Invoke("BFEDummy", New Object(-1) {})
            Return CType(results(0),DummyResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEDummyAsync()
            Me.BFEDummyAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEDummyAsync(ByVal userState As Object)
            If (Me.BFEDummyOperationCompleted Is Nothing) Then
                Me.BFEDummyOperationCompleted = AddressOf Me.OnBFEDummyOperationCompleted
            End If
            Me.InvokeAsync("BFEDummy", New Object(-1) {}, Me.BFEDummyOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEDummyOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEDummyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEDummyCompleted(Me, New BFEDummyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetLast_ID", RequestNamespace:="http://ar.gov.afip.dif.bfe/", ResponseNamespace:="http://ar.gov.afip.dif.bfe/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BFEGetLast_ID(ByVal Auth As ClsBFEAuthRequest) As BFEResponse_LastID
            Dim results() As Object = Me.Invoke("BFEGetLast_ID", New Object() {Auth})
            Return CType(results(0),BFEResponse_LastID)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BFEGetLast_IDAsync(ByVal Auth As ClsBFEAuthRequest)
            Me.BFEGetLast_IDAsync(Auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BFEGetLast_IDAsync(ByVal Auth As ClsBFEAuthRequest, ByVal userState As Object)
            If (Me.BFEGetLast_IDOperationCompleted Is Nothing) Then
                Me.BFEGetLast_IDOperationCompleted = AddressOf Me.OnBFEGetLast_IDOperationCompleted
            End If
            Me.InvokeAsync("BFEGetLast_ID", New Object() {Auth}, Me.BFEGetLast_IDOperationCompleted, userState)
        End Sub
        
        Private Sub OnBFEGetLast_IDOperationCompleted(ByVal arg As Object)
            If (Not (Me.BFEGetLast_IDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BFEGetLast_IDCompleted(Me, New BFEGetLast_IDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEAuthRequest
        
        Private tokenField As String
        
        Private signField As String
        
        Private cuitField As Long
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sign() As String
            Get
                Return Me.signField
            End Get
            Set
                Me.signField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cuit() As Long
            Get
                Return Me.cuitField
            End Get
            Set
                Me.cuitField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEResponse_LastID
        
        Private idField As Long
        
        '''<remarks/>
        Public Property Id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEResponse_LastID
        
        Private bFEResultGetField As ClsBFEResponse_LastID
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResultGet() As ClsBFEResponse_LastID
            Get
                Return Me.bFEResultGetField
            End Get
            Set
                Me.bFEResultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEErr
        
        Private errCodeField As Integer
        
        Private errMsgField As String
        
        '''<remarks/>
        Public Property ErrCode() As Integer
            Get
                Return Me.errCodeField
            End Get
            Set
                Me.errCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrMsg() As String
            Get
                Return Me.errMsgField
            End Get
            Set
                Me.errMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEEvents
        
        Private eventCodeField As Integer
        
        Private eventMsgField As String
        
        '''<remarks/>
        Public Property EventCode() As Integer
            Get
                Return Me.eventCodeField
            End Get
            Set
                Me.eventCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EventMsg() As String
            Get
                Return Me.eventMsgField
            End Get
            Set
                Me.eventMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class DummyResponse
        
        Private appServerField As String
        
        Private dbServerField As String
        
        Private authServerField As String
        
        '''<remarks/>
        Public Property AppServer() As String
            Get
                Return Me.appServerField
            End Get
            Set
                Me.appServerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DbServer() As String
            Get
                Return Me.dbServerField
            End Get
            Set
                Me.dbServerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AuthServer() As String
            Get
                Return Me.authServerField
            End Get
            Set
                Me.authServerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFE_LastCMP_Response
        
        Private cbte_nroField As Long
        
        Private cbte_fechaField As String
        
        '''<remarks/>
        Public Property Cbte_nro() As Long
            Get
                Return Me.cbte_nroField
            End Get
            Set
                Me.cbte_nroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cbte_fecha() As String
            Get
                Return Me.cbte_fechaField
            End Get
            Set
                Me.cbte_fechaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEResponseLast_CMP
        
        Private bFEResult_LastCMPField As ClsBFE_LastCMP_Response
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResult_LastCMP() As ClsBFE_LastCMP_Response
            Get
                Return Me.bFEResult_LastCMPField
            End Get
            Set
                Me.bFEResult_LastCMPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFE_LastCMP
        
        Private tokenField As String
        
        Private signField As String
        
        Private cuitField As Long
        
        Private pto_ventaField As Short
        
        Private tipo_cbteField As Short
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sign() As String
            Get
                Return Me.signField
            End Get
            Set
                Me.signField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cuit() As Long
            Get
                Return Me.cuitField
            End Get
            Set
                Me.cuitField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pto_venta() As Short
            Get
                Return Me.pto_ventaField
            End Get
            Set
                Me.pto_ventaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tipo_cbte() As Short
            Get
                Return Me.tipo_cbteField
            End Get
            Set
                Me.tipo_cbteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEResponse_Mon
        
        Private mon_IdField As String
        
        Private mon_DsField As String
        
        Private mon_vig_desdeField As String
        
        Private mon_vig_hastaField As String
        
        '''<remarks/>
        Public Property Mon_Id() As String
            Get
                Return Me.mon_IdField
            End Get
            Set
                Me.mon_IdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mon_Ds() As String
            Get
                Return Me.mon_DsField
            End Get
            Set
                Me.mon_DsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mon_vig_desde() As String
            Get
                Return Me.mon_vig_desdeField
            End Get
            Set
                Me.mon_vig_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mon_vig_hasta() As String
            Get
                Return Me.mon_vig_hastaField
            End Get
            Set
                Me.mon_vig_hastaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEResponse_Mon
        
        Private bFEResultGetField() As ClsBFEResponse_Mon
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResultGet() As ClsBFEResponse_Mon()
            Get
                Return Me.bFEResultGetField
            End Get
            Set
                Me.bFEResultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEResponse_NCM
        
        Private nCM_CodigoField As String
        
        Private nCM_DsField As String
        
        Private nCM_NotaField As String
        
        Private nCM_vig_desdeField As String
        
        Private nCM_vig_hastaField As String
        
        '''<remarks/>
        Public Property NCM_Codigo() As String
            Get
                Return Me.nCM_CodigoField
            End Get
            Set
                Me.nCM_CodigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NCM_Ds() As String
            Get
                Return Me.nCM_DsField
            End Get
            Set
                Me.nCM_DsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NCM_Nota() As String
            Get
                Return Me.nCM_NotaField
            End Get
            Set
                Me.nCM_NotaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NCM_vig_desde() As String
            Get
                Return Me.nCM_vig_desdeField
            End Get
            Set
                Me.nCM_vig_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NCM_vig_hasta() As String
            Get
                Return Me.nCM_vig_hastaField
            End Get
            Set
                Me.nCM_vig_hastaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEResponse_NCM
        
        Private bFEResultGetField() As ClsBFEResponse_NCM
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResultGet() As ClsBFEResponse_NCM()
            Get
                Return Me.bFEResultGetField
            End Get
            Set
                Me.bFEResultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEResponse_UMed
        
        Private umed_IdField As Short
        
        Private umed_DsField As String
        
        Private umed_vig_desdeField As String
        
        Private umed_vig_hastaField As String
        
        '''<remarks/>
        Public Property Umed_Id() As Short
            Get
                Return Me.umed_IdField
            End Get
            Set
                Me.umed_IdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Umed_Ds() As String
            Get
                Return Me.umed_DsField
            End Get
            Set
                Me.umed_DsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Umed_vig_desde() As String
            Get
                Return Me.umed_vig_desdeField
            End Get
            Set
                Me.umed_vig_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Umed_vig_hasta() As String
            Get
                Return Me.umed_vig_hastaField
            End Get
            Set
                Me.umed_vig_hastaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEResponse_Umed
        
        Private bFEResultGetField() As ClsBFEResponse_UMed
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResultGet() As ClsBFEResponse_UMed()
            Get
                Return Me.bFEResultGetField
            End Get
            Set
                Me.bFEResultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEResponse_Tipo_Cbte
        
        Private cbte_IdField As Short
        
        Private cbte_DsField As String
        
        Private cbte_vig_desdeField As String
        
        Private cbte_vig_hastaField As String
        
        '''<remarks/>
        Public Property Cbte_Id() As Short
            Get
                Return Me.cbte_IdField
            End Get
            Set
                Me.cbte_IdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cbte_Ds() As String
            Get
                Return Me.cbte_DsField
            End Get
            Set
                Me.cbte_DsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cbte_vig_desde() As String
            Get
                Return Me.cbte_vig_desdeField
            End Get
            Set
                Me.cbte_vig_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cbte_vig_hasta() As String
            Get
                Return Me.cbte_vig_hastaField
            End Get
            Set
                Me.cbte_vig_hastaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEResponse_Tipo_Cbte
        
        Private bFEResultGetField() As ClsBFEResponse_Tipo_Cbte
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResultGet() As ClsBFEResponse_Tipo_Cbte()
            Get
                Return Me.bFEResultGetField
            End Get
            Set
                Me.bFEResultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEResponse_Zon
        
        Private zon_IdField As Short
        
        Private zon_DsField As String
        
        Private zon_vig_desdeField As String
        
        Private zon_vig_hastaField As String
        
        '''<remarks/>
        Public Property Zon_Id() As Short
            Get
                Return Me.zon_IdField
            End Get
            Set
                Me.zon_IdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Zon_Ds() As String
            Get
                Return Me.zon_DsField
            End Get
            Set
                Me.zon_DsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Zon_vig_desde() As String
            Get
                Return Me.zon_vig_desdeField
            End Get
            Set
                Me.zon_vig_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Zon_vig_hasta() As String
            Get
                Return Me.zon_vig_hastaField
            End Get
            Set
                Me.zon_vig_hastaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEResponse_Zon
        
        Private bFEResultGetField() As ClsBFEResponse_Zon
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResultGet() As ClsBFEResponse_Zon()
            Get
                Return Me.bFEResultGetField
            End Get
            Set
                Me.bFEResultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEResponse_Tipo_IVA
        
        Private iVA_IdField As Short
        
        Private iVA_DsField As String
        
        Private iVA_vig_desdeField As String
        
        Private iVA_vig_hastaField As String
        
        '''<remarks/>
        Public Property IVA_Id() As Short
            Get
                Return Me.iVA_IdField
            End Get
            Set
                Me.iVA_IdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IVA_Ds() As String
            Get
                Return Me.iVA_DsField
            End Get
            Set
                Me.iVA_DsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IVA_vig_desde() As String
            Get
                Return Me.iVA_vig_desdeField
            End Get
            Set
                Me.iVA_vig_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IVA_vig_hasta() As String
            Get
                Return Me.iVA_vig_hastaField
            End Get
            Set
                Me.iVA_vig_hastaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEResponse_Tipo_IVA
        
        Private bFEResultGetField() As ClsBFEResponse_Tipo_IVA
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResultGet() As ClsBFEResponse_Tipo_IVA()
            Get
                Return Me.bFEResultGetField
            End Get
            Set
                Me.bFEResultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEResponse_Tipo_doc
        
        Private doc_IdField As Short
        
        Private doc_DsField As String
        
        Private doc_vig_desdeField As String
        
        Private doc_vig_hastaField As String
        
        '''<remarks/>
        Public Property Doc_Id() As Short
            Get
                Return Me.doc_IdField
            End Get
            Set
                Me.doc_IdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Doc_Ds() As String
            Get
                Return Me.doc_DsField
            End Get
            Set
                Me.doc_DsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Doc_vig_desde() As String
            Get
                Return Me.doc_vig_desdeField
            End Get
            Set
                Me.doc_vig_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Doc_vig_hasta() As String
            Get
                Return Me.doc_vig_hastaField
            End Get
            Set
                Me.doc_vig_hastaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEResponse_Tipo_doc
        
        Private bFEResultGetField() As ClsBFEResponse_Tipo_doc
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResultGet() As ClsBFEResponse_Tipo_doc()
            Get
                Return Me.bFEResultGetField
            End Get
            Set
                Me.bFEResultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEGetCMPR
        
        Private idField As Long
        
        Private cuitField As Long
        
        Private tipo_docField As Short
        
        Private nro_docField As Long
        
        Private tipo_cbteField As Short
        
        Private punto_vtaField As Integer
        
        Private cbte_nroField As Long
        
        Private imp_totalField As Double
        
        Private imp_tot_concField As Double
        
        Private imp_netoField As Double
        
        Private impto_liqField As Double
        
        Private impto_liq_rniField As Double
        
        Private imp_op_exField As Double
        
        Private imp_percField As Double
        
        Private imp_iibbField As Double
        
        Private imp_perc_munField As Double
        
        Private imp_internosField As Double
        
        Private imp_moneda_IdField As String
        
        Private imp_moneda_ctzField As Double
        
        Private fecha_cbte_origField As String
        
        Private fecha_cbte_caeField As String
        
        Private fch_venc_CaeField As String
        
        Private caeField As String
        
        Private resultadoField As String
        
        Private obsField As String
        
        Private itemsField() As Item
        
        '''<remarks/>
        Public Property Id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cuit() As Long
            Get
                Return Me.cuitField
            End Get
            Set
                Me.cuitField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tipo_doc() As Short
            Get
                Return Me.tipo_docField
            End Get
            Set
                Me.tipo_docField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nro_doc() As Long
            Get
                Return Me.nro_docField
            End Get
            Set
                Me.nro_docField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tipo_cbte() As Short
            Get
                Return Me.tipo_cbteField
            End Get
            Set
                Me.tipo_cbteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Punto_vta() As Integer
            Get
                Return Me.punto_vtaField
            End Get
            Set
                Me.punto_vtaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cbte_nro() As Long
            Get
                Return Me.cbte_nroField
            End Get
            Set
                Me.cbte_nroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_total() As Double
            Get
                Return Me.imp_totalField
            End Get
            Set
                Me.imp_totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_tot_conc() As Double
            Get
                Return Me.imp_tot_concField
            End Get
            Set
                Me.imp_tot_concField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_neto() As Double
            Get
                Return Me.imp_netoField
            End Get
            Set
                Me.imp_netoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Impto_liq() As Double
            Get
                Return Me.impto_liqField
            End Get
            Set
                Me.impto_liqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Impto_liq_rni() As Double
            Get
                Return Me.impto_liq_rniField
            End Get
            Set
                Me.impto_liq_rniField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_op_ex() As Double
            Get
                Return Me.imp_op_exField
            End Get
            Set
                Me.imp_op_exField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_perc() As Double
            Get
                Return Me.imp_percField
            End Get
            Set
                Me.imp_percField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_iibb() As Double
            Get
                Return Me.imp_iibbField
            End Get
            Set
                Me.imp_iibbField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_perc_mun() As Double
            Get
                Return Me.imp_perc_munField
            End Get
            Set
                Me.imp_perc_munField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_internos() As Double
            Get
                Return Me.imp_internosField
            End Get
            Set
                Me.imp_internosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_moneda_Id() As String
            Get
                Return Me.imp_moneda_IdField
            End Get
            Set
                Me.imp_moneda_IdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_moneda_ctz() As Double
            Get
                Return Me.imp_moneda_ctzField
            End Get
            Set
                Me.imp_moneda_ctzField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fecha_cbte_orig() As String
            Get
                Return Me.fecha_cbte_origField
            End Get
            Set
                Me.fecha_cbte_origField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fecha_cbte_cae() As String
            Get
                Return Me.fecha_cbte_caeField
            End Get
            Set
                Me.fecha_cbte_caeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fch_venc_Cae() As String
            Get
                Return Me.fch_venc_CaeField
            End Get
            Set
                Me.fch_venc_CaeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cae() As String
            Get
                Return Me.caeField
            End Get
            Set
                Me.caeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resultado() As String
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Obs() As String
            Get
                Return Me.obsField
            End Get
            Set
                Me.obsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Items() As Item()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class Item
        
        Private pro_codigo_ncmField As String
        
        Private pro_codigo_secField As String
        
        Private pro_dsField As String
        
        Private pro_qtyField As Double
        
        Private pro_umedField As Integer
        
        Private pro_precio_uniField As Double
        
        Private imp_bonifField As Double
        
        Private imp_totalField As Double
        
        Private iva_idField As Short
        
        '''<remarks/>
        Public Property Pro_codigo_ncm() As String
            Get
                Return Me.pro_codigo_ncmField
            End Get
            Set
                Me.pro_codigo_ncmField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pro_codigo_sec() As String
            Get
                Return Me.pro_codigo_secField
            End Get
            Set
                Me.pro_codigo_secField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pro_ds() As String
            Get
                Return Me.pro_dsField
            End Get
            Set
                Me.pro_dsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pro_qty() As Double
            Get
                Return Me.pro_qtyField
            End Get
            Set
                Me.pro_qtyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pro_umed() As Integer
            Get
                Return Me.pro_umedField
            End Get
            Set
                Me.pro_umedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pro_precio_uni() As Double
            Get
                Return Me.pro_precio_uniField
            End Get
            Set
                Me.pro_precio_uniField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_bonif() As Double
            Get
                Return Me.imp_bonifField
            End Get
            Set
                Me.imp_bonifField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_total() As Double
            Get
                Return Me.imp_totalField
            End Get
            Set
                Me.imp_totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Iva_id() As Short
            Get
                Return Me.iva_idField
            End Get
            Set
                Me.iva_idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEGetCMPResponse
        
        Private bFEResultGetField As ClsBFEGetCMPR
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResultGet() As ClsBFEGetCMPR
            Get
                Return Me.bFEResultGetField
            End Get
            Set
                Me.bFEResultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEGetCMP
        
        Private tipo_cbteField As Short
        
        Private punto_vtaField As Integer
        
        Private cbte_nroField As Long
        
        '''<remarks/>
        Public Property Tipo_cbte() As Short
            Get
                Return Me.tipo_cbteField
            End Get
            Set
                Me.tipo_cbteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Punto_vta() As Integer
            Get
                Return Me.punto_vtaField
            End Get
            Set
                Me.punto_vtaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cbte_nro() As Long
            Get
                Return Me.cbte_nroField
            End Get
            Set
                Me.cbte_nroField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFEOutAuthorize
        
        Private idField As Long
        
        Private cuitField As Long
        
        Private caeField As String
        
        Private fch_venc_CaeField As String
        
        Private fch_cbteField As String
        
        Private resultadoField As String
        
        Private reprocesoField As String
        
        Private obsField As String
        
        '''<remarks/>
        Public Property Id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cuit() As Long
            Get
                Return Me.cuitField
            End Get
            Set
                Me.cuitField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cae() As String
            Get
                Return Me.caeField
            End Get
            Set
                Me.caeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fch_venc_Cae() As String
            Get
                Return Me.fch_venc_CaeField
            End Get
            Set
                Me.fch_venc_CaeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fch_cbte() As String
            Get
                Return Me.fch_cbteField
            End Get
            Set
                Me.fch_cbteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resultado() As String
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reproceso() As String
            Get
                Return Me.reprocesoField
            End Get
            Set
                Me.reprocesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Obs() As String
            Get
                Return Me.obsField
            End Get
            Set
                Me.obsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class BFEResponseAuthorize
        
        Private bFEResultAuthField As ClsBFEOutAuthorize
        
        Private bFEErrField As ClsBFEErr
        
        Private bFEEventsField As ClsBFEEvents
        
        '''<remarks/>
        Public Property BFEResultAuth() As ClsBFEOutAuthorize
            Get
                Return Me.bFEResultAuthField
            End Get
            Set
                Me.bFEResultAuthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEErr() As ClsBFEErr
            Get
                Return Me.bFEErrField
            End Get
            Set
                Me.bFEErrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BFEEvents() As ClsBFEEvents
            Get
                Return Me.bFEEventsField
            End Get
            Set
                Me.bFEEventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.bfe/")>  _
    Partial Public Class ClsBFERequest
        
        Private idField As Long
        
        Private tipo_docField As Short
        
        Private nro_docField As Long
        
        Private zonaField As Short
        
        Private tipo_cbteField As Short
        
        Private punto_vtaField As Integer
        
        Private cbte_nroField As Long
        
        Private imp_totalField As Double
        
        Private imp_tot_concField As Double
        
        Private imp_netoField As Double
        
        Private impto_liqField As Double
        
        Private impto_liq_rniField As Double
        
        Private imp_op_exField As Double
        
        Private imp_percField As Double
        
        Private imp_iibbField As Double
        
        Private imp_perc_munField As Double
        
        Private imp_internosField As Double
        
        Private imp_moneda_IdField As String
        
        Private imp_moneda_ctzField As Double
        
        Private fecha_cbteField As String
        
        Private itemsField() As Item
        
        '''<remarks/>
        Public Property Id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tipo_doc() As Short
            Get
                Return Me.tipo_docField
            End Get
            Set
                Me.tipo_docField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nro_doc() As Long
            Get
                Return Me.nro_docField
            End Get
            Set
                Me.nro_docField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Zona() As Short
            Get
                Return Me.zonaField
            End Get
            Set
                Me.zonaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tipo_cbte() As Short
            Get
                Return Me.tipo_cbteField
            End Get
            Set
                Me.tipo_cbteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Punto_vta() As Integer
            Get
                Return Me.punto_vtaField
            End Get
            Set
                Me.punto_vtaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cbte_nro() As Long
            Get
                Return Me.cbte_nroField
            End Get
            Set
                Me.cbte_nroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_total() As Double
            Get
                Return Me.imp_totalField
            End Get
            Set
                Me.imp_totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_tot_conc() As Double
            Get
                Return Me.imp_tot_concField
            End Get
            Set
                Me.imp_tot_concField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_neto() As Double
            Get
                Return Me.imp_netoField
            End Get
            Set
                Me.imp_netoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Impto_liq() As Double
            Get
                Return Me.impto_liqField
            End Get
            Set
                Me.impto_liqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Impto_liq_rni() As Double
            Get
                Return Me.impto_liq_rniField
            End Get
            Set
                Me.impto_liq_rniField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_op_ex() As Double
            Get
                Return Me.imp_op_exField
            End Get
            Set
                Me.imp_op_exField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_perc() As Double
            Get
                Return Me.imp_percField
            End Get
            Set
                Me.imp_percField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_iibb() As Double
            Get
                Return Me.imp_iibbField
            End Get
            Set
                Me.imp_iibbField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_perc_mun() As Double
            Get
                Return Me.imp_perc_munField
            End Get
            Set
                Me.imp_perc_munField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_internos() As Double
            Get
                Return Me.imp_internosField
            End Get
            Set
                Me.imp_internosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_moneda_Id() As String
            Get
                Return Me.imp_moneda_IdField
            End Get
            Set
                Me.imp_moneda_IdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Imp_moneda_ctz() As Double
            Get
                Return Me.imp_moneda_ctzField
            End Get
            Set
                Me.imp_moneda_ctzField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fecha_cbte() As String
            Get
                Return Me.fecha_cbteField
            End Get
            Set
                Me.fecha_cbteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Items() As Item()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEAuthorizeCompletedEventHandler(ByVal sender As Object, ByVal e As BFEAuthorizeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEAuthorizeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEResponseAuthorize
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEResponseAuthorize)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEGetCMPCompletedEventHandler(ByVal sender As Object, ByVal e As BFEGetCMPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEGetCMPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEGetCMPResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEGetCMPResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEGetPARAM_Tipo_docCompletedEventHandler(ByVal sender As Object, ByVal e As BFEGetPARAM_Tipo_docCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEGetPARAM_Tipo_docCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEResponse_Tipo_doc
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEResponse_Tipo_doc)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEGetPARAM_Tipo_IVACompletedEventHandler(ByVal sender As Object, ByVal e As BFEGetPARAM_Tipo_IVACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEGetPARAM_Tipo_IVACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEResponse_Tipo_IVA
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEResponse_Tipo_IVA)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEGetPARAM_ZonasCompletedEventHandler(ByVal sender As Object, ByVal e As BFEGetPARAM_ZonasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEGetPARAM_ZonasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEResponse_Zon
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEResponse_Zon)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEGetPARAM_Tipo_CbteCompletedEventHandler(ByVal sender As Object, ByVal e As BFEGetPARAM_Tipo_CbteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEGetPARAM_Tipo_CbteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEResponse_Tipo_Cbte
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEResponse_Tipo_Cbte)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEGetPARAM_UMedCompletedEventHandler(ByVal sender As Object, ByVal e As BFEGetPARAM_UMedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEGetPARAM_UMedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEResponse_Umed
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEResponse_Umed)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEGetPARAM_NCMCompletedEventHandler(ByVal sender As Object, ByVal e As BFEGetPARAM_NCMCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEGetPARAM_NCMCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEResponse_NCM
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEResponse_NCM)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEGetPARAM_MONCompletedEventHandler(ByVal sender As Object, ByVal e As BFEGetPARAM_MONCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEGetPARAM_MONCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEResponse_Mon
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEResponse_Mon)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEGetLast_CMPCompletedEventHandler(ByVal sender As Object, ByVal e As BFEGetLast_CMPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEGetLast_CMPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEResponseLast_CMP
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEResponseLast_CMP)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEDummyCompletedEventHandler(ByVal sender As Object, ByVal e As BFEDummyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEDummyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DummyResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DummyResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub BFEGetLast_IDCompletedEventHandler(ByVal sender As Object, ByVal e As BFEGetLast_IDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BFEGetLast_IDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BFEResponse_LastID
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BFEResponse_LastID)
            End Get
        End Property
    End Class
End Namespace
