DELETE Parametros
 WHERE IdParametro IN ('WEBARCHIVOSCLIENTESARCHIVOEXPORTACION',
                       'WEBARCHIVOSPRODUCTOSARCHIVOEXPORTACION',
                       'WEBARCHIVOSPRODSUCURARCHIVOEXPORTACION',
                       'WEBARCHIVOSPRODSUCURPRECIOSARCHIVOEXPORTACION',
                       'WEBARCHIVOSLOCALIDADESARCHIVOEXPORTACION',
                       'WEBARCHIVOSRUBROSARCHIVOEXPORTACION',
                       'WEBARCHIVOSSUBRUBROSARCHIVOEXPORTACION',
                       'WEBARCHIVOSSUBSUBRUBROSARCHIVOEXPORTACION',
                       'WEBARCHIVOSMARCASARCHIVOEXPORTACION',
                       'WEBARCHIVOSRUBROSCOMPRASARCHIVOEXPORTACION',
                       'WEBARCHIVOSPROVEEDORESARCHIVOEXPORTACION')
