    MERGE INTO Parametros AS P USING (
SELECT 'WEBARCHIVOSCLIENTESARCHIVOEXPORTACION'  AS IdParametro, ''  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSCLIENTESTAMANOPAGINAGET'  AS IdParametro, '99999999'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSCLIENTESTAMANOPAGINAPOST'  AS IdParametro, '500'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSCLIENTESURLDELETE'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaclientejson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSCLIENTESURLGET'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaclientejsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSCLIENTESURLGETCOUNT'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaclientejsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSCLIENTESURLGETMAXFECHA'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaclientejsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSCLIENTESURLPOST'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaclientejson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSLOCALIDADESARCHIVOEXPORTACION'  AS IdParametro, ''  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSLOCALIDADESTAMANOPAGINAGET'  AS IdParametro, '500'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSLOCALIDADESTAMANOPAGINAPOST'  AS IdParametro, '500'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSLOCALIDADESURLDELETE'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigalocalidadjson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSLOCALIDADESURLGET'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigalocalidadjsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSLOCALIDADESURLGETCOUNT'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigalocalidadjsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSLOCALIDADESURLGETMAXFECHA'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigalocalidadjsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSLOCALIDADESURLPOST'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigalocalidadjson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSMARCASARCHIVOEXPORTACION'  AS IdParametro, ''  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSMARCASTAMANOPAGINAGET'  AS IdParametro, '99999999'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño Página GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSMARCASTAMANOPAGINAPOST'  AS IdParametro, '500'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño Página POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSMARCASURLDELETE'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigamarcajson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSMARCASURLGET'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigamarcajsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSMARCASURLGETCOUNT'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigamarcajsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSMARCASURLGETMAXFECHA'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigamarcajsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSMARCASURLPOST'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigamarcajson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURARCHIVOEXPORTACION'  AS IdParametro, ''  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURPRECIOSARCHIVOEXPORTACION'  AS IdParametro, 'c:\Temp\_json\export\precios{0:000}.json'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURPRECIOSTAMANOPAGINAGET'  AS IdParametro, '100'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURPRECIOSTAMANOPAGINAPOST'  AS IdParametro, '100'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURPRECIOSURLDELETE'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductossucursalespreciojson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURPRECIOSURLGET'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductossucursalespreciojsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURPRECIOSURLGETCOUNT'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductossucursalespreciojsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURPRECIOSURLGETMAXFECHA'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductossucursalespreciojsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURPRECIOSURLPOST'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductossucursalespreciojson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURTAMANOPAGINAGET'  AS IdParametro, '50'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURTAMANOPAGINAPOST'  AS IdParametro, '50'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURURLDELETE'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductossucursaljson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURURLGET'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductossucursaljsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURURLGETCOUNT'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductossucursaljsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURURLGETMAXFECHA'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductossucursaljsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODSUCURURLPOST'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductossucursaljson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODUCTOSARCHIVOEXPORTACION'  AS IdParametro, 'c:\Temp\_json\export\producto{0:000}.json'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODUCTOSINCLUIRIMAGENES'  AS IdParametro, 'True'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Incluir Imagenes' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODUCTOSPUBLICARENWEB'  AS IdParametro, 'SI'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Publicar en Web' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODUCTOSTAMANOPAGINAGET'  AS IdParametro, '50'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODUCTOSTAMANOPAGINAPOST'  AS IdParametro, '50'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODUCTOSURLDELETE'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductojson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODUCTOSURLGET'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductojsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODUCTOSURLGETCOUNT'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductojsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODUCTOSURLGETMAXFECHA'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductojsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPRODUCTOSURLPOST'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproductojson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPROVEEDORESARCHIVOEXPORTACION'  AS IdParametro, ''  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPROVEEDORESTAMANOPAGINAGET'  AS IdParametro, '99999999'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño Página GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPROVEEDORESTAMANOPAGINAPOST'  AS IdParametro, '200'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño Página POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPROVEEDORESURLDELETE'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproveedorjson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPROVEEDORESURLGET'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproveedorjsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPROVEEDORESURLGETCOUNT'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproveedorjsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPROVEEDORESURLGETMAXFECHA'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproveedorjsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSPROVEEDORESURLPOST'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigaproveedorjson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSARCHIVOEXPORTACION'  AS IdParametro, 'c:\Temp\_json\export\rubro{0:000}.json'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSCOMPRASARCHIVOEXPORTACION'  AS IdParametro, ''  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSCOMPRASTAMANOPAGINAGET'  AS IdParametro, '99999999'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño Página GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSCOMPRASTAMANOPAGINAPOST'  AS IdParametro, '500'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño Página POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSCOMPRASURLDELETE'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigarubrocomprajson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSCOMPRASURLGET'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigarubrocomprajsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSCOMPRASURLGETCOUNT'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigarubrocomprajsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSCOMPRASURLGETMAXFECHA'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigarubrocomprajsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSCOMPRASURLPOST'  AS IdParametro, 'http://distribuidoramatienzo.com/rest-siga/index.php/api/sigarubrocomprajson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSTAMANOPAGINAGET'  AS IdParametro, '100'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSTAMANOPAGINAPOST'  AS IdParametro, '100'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSURLDELETE'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigarubrojson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSURLGET'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigarubrojsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSURLGETCOUNT'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigarubrojsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSURLGETMAXFECHA'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigarubrojsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSRUBROSURLPOST'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigarubrojson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBRUBROSARCHIVOEXPORTACION'  AS IdParametro, 'c:\Temp\_json\export\subrubro{0:000}.json'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBRUBROSTAMANOPAGINAGET'  AS IdParametro, '100'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBRUBROSTAMANOPAGINAPOST'  AS IdParametro, '100'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBRUBROSURLDELETE'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigasubrubrojson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBRUBROSURLGET'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigasubrubrojsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBRUBROSURLGETCOUNT'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigasubrubrojsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBRUBROSURLGETMAXFECHA'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigasubrubrojsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBRUBROSURLPOST'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigasubrubrojson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBSUBRUBROSARCHIVOEXPORTACION'  AS IdParametro, ''  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Archivo Exportación' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBSUBRUBROSTAMANOPAGINAGET'  AS IdParametro, '100'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBSUBRUBROSTAMANOPAGINAPOST'  AS IdParametro, '100'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'Tamaño página' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBSUBRUBROSURLDELETE'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigasubsubrubrojson/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL DELETE' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBSUBRUBROSURLGET'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigasubsubrubrojsondesdehasta/CuitEmpresa/27346831052/FechaActualizacion/{2}/Desde/{0}/Cantidad/{1}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBSUBRUBROSURLGETCOUNT'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigasubsubrubrojsoncount/CuitEmpresa/27346831052/FechaActualizacion/{0}'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET COUNT' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBSUBRUBROSURLGETMAXFECHA'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigasubsubrubrojsonmax/CuitEmpresa/27346831052/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL GET MAX FECHA' AS DescripcionParametro UNION
SELECT 'WEBARCHIVOSSUBSUBRUBROSURLPOST'  AS IdParametro, 'https://distribuidoramatienzo.com/rest-siga/index.php/api/sigasubsubrubrojson/'  ValorParametro, 'WEB-ARCHIVOS'  CategoriaParametro, 'URL POST' AS DescripcionParametro
                ) AS PT ON P.IdParametro = PT.IdParametro
     WHEN MATCHED THEN UPDATE SET P.ValorParametro = PT.ValorParametro, P.CategoriaParametro = PT.CategoriaParametro
     WHEN NOT MATCHED THEN INSERT (   IdParametro,    ValorParametro, CategoriaParametro,    DescripcionParametro) VALUES (PT.IdParametro, PT.ValorParametro, PT.CategoriaParametro , PT.DescripcionParametro);
