CREATE TABLE [dbo].[Alquileres] (
    [IdSucursal]            INT             NOT NULL,
    [NumeroContrato]        BIGINT          NOT NULL,
    [FechaContrato]         DATE            NOT NULL,
    [IdProducto]            VARCHAR (15)    NOT NULL,
    [FechaDesde]            DATE            NOT NULL,
    [FechaHasta]            DATE            NOT NULL,
    [EsRenovable]           BIT             NOT NULL,
    [LocatarioNroDocumento] BIGINT          NULL,
    [LocatarioNombre]       VARCHAR (50)    NULL,
    [LocatarioCargo]        VARCHAR (20)    NULL,
    [ImporteTotal]          DECIMAL (12, 2) NOT NULL,
    [PersonalCapacitado]    VARCHAR (200)   NULL,
    [LugarER]               VARCHAR (200)   NULL,
    [HoraE]                 VARCHAR (5)     NULL,
    [HoraR]                 VARCHAR (5)     NULL,
    [IdEstado]              INT             NOT NULL,
    [FechaRealFin]          DATE            NOT NULL,
    [IdUsuario]             VARCHAR (10)    NOT NULL,
    [IdTipoComprobante]     VARCHAR (15)    NULL,
    [Letra]                 VARCHAR (1)     NULL,
    [CentroEmisor]          INT             NULL,
    [NumeroComprobante]     BIGINT          NULL,
    [ImporteAlquiler]       DECIMAL (14, 4) NOT NULL,
    [ImporteTraslado]       DECIMAL (14, 4) NOT NULL,
    [IdCliente]             BIGINT          NOT NULL,
    CONSTRAINT [PK_Alquileres] PRIMARY KEY CLUSTERED ([IdSucursal] ASC, [NumeroContrato] ASC),
    CONSTRAINT [FK_Alquileres_AlquileresEstadosContratos] FOREIGN KEY ([IdEstado]) REFERENCES [dbo].[AlquileresEstadosContratos] ([IdEstado]),
    CONSTRAINT [FK_Alquileres_Clientes] FOREIGN KEY ([IdCliente]) REFERENCES [dbo].[Clientes] ([IdCliente]),
    CONSTRAINT [FK_Alquileres_Productos] FOREIGN KEY ([IdProducto]) REFERENCES [dbo].[Productos] ([IdProducto]),
    CONSTRAINT [FK_Alquileres_Sucursales] FOREIGN KEY ([IdSucursal]) REFERENCES [dbo].[Sucursales] ([IdSucursal]),
    CONSTRAINT [FK_Alquileres_Usuarios] FOREIGN KEY ([IdUsuario]) REFERENCES [dbo].[Usuarios] ([Id]),
    CONSTRAINT [FK_Alquileres_Ventas] FOREIGN KEY ([IdTipoComprobante], [Letra], [CentroEmisor], [NumeroComprobante], [IdSucursal]) REFERENCES [dbo].[Ventas] ([IdTipoComprobante], [Letra], [CentroEmisor], [NumeroComprobante], [IdSucursal])
);

