CREATE TABLE [dbo].[AuditoriaProductos] (
    [FechaAuditoria]                 DATETIME        NOT NULL,
    [OperacionAuditoria]             CHAR (1)        NOT NULL,
    [UsuarioAuditoria]               VARCHAR (10)    NOT NULL,
    [IdProducto]                     VARCHAR (15)    NOT NULL,
    [NombreProducto]                 VARCHAR (60)    NOT NULL,
    [Tamano]                         DECIMAL (7, 3)  NULL,
    [IdUnidadDeMedida]               CHAR (2)        NULL,
    [IdMarca]                        INT             NOT NULL,
    [IdRubro]                        INT             NOT NULL,
    [MesesGarantia]                  INT             NOT NULL,
    [Activo]                         BIT             NOT NULL,
    [AfectaStock]                    BIT             NOT NULL,
    [IdModelo]                       INT             NULL,
    [IdSubRubro]                     INT             NULL,
    [Foto]                           IMAGE           NULL,
    [Lote]                           BIT             NOT NULL,
    [NroSerie]                       BIT             NOT NULL,
    [IdTipoImpuesto]                 VARCHAR (5)     NOT NULL,
    [Alicuota]                       DECIMAL (6, 2)  NOT NULL,
    [CodigoDeBarras]                 VARCHAR (15)    NULL,
    [EsServicio]                     BIT             NOT NULL,
    [Observacion]                    VARCHAR (300)   NOT NULL,
    [PublicarEnWeb]                  BIT             NOT NULL,
    [EsDeCompras]                    BIT             NOT NULL,
    [EsDeVentas]                     BIT             NOT NULL,
    [DescontarStockComponentes]      BIT             NOT NULL,
    [IdMoneda]                       INT             NOT NULL,
    [EsCompuesto]                    BIT             NOT NULL,
    [CodigoDeBarrasConPrecio]        BIT             NOT NULL,
    [EsAlquilable]                   BIT             NOT NULL,
    [EquipoMarca]                    VARCHAR (20)    NULL,
    [EquipoModelo]                   VARCHAR (20)    NULL,
    [NumeroSerie]                    VARCHAR (50)    NULL,
    [CaractSII]                      VARCHAR (50)    NULL,
    [Anio]                           INT             NULL,
    [PermiteModificarDescripcion]    BIT             NOT NULL,
    [Alicuota2]                      DECIMAL (6, 2)  NULL,
    [PagaIngresosBrutos]             BIT             NOT NULL,
    [Embalaje]                       INT             NOT NULL,
    [Kilos]                          DECIMAL (10, 3) NOT NULL,
    [IdFormula]                      INT             NULL,
    [IdProductoMercosur]             VARCHAR (50)    NULL,
    [IdProductoSecretaria]           VARCHAR (50)    NULL,
    [PublicarListaDePreciosClientes] BIT             NOT NULL,
    [FacturacionCantidadNegativa]    BIT             NOT NULL,
    [SolicitaEnvase]                 BIT             NOT NULL,
    [AlertaDeCaja]                   BIT             NOT NULL,
    [NombreCorto]                    VARCHAR (30)    NULL,
    [EsRetornable]                   BIT             NOT NULL,
    [Orden]                          INT             NULL,
    [ModalidadCodigoDeBarras]        VARCHAR (20)    NULL,
    [CodigoLargoProducto]            VARCHAR (30)    NULL,
    [IdProveedor]                    BIGINT          NULL,
    [EsObservacion]                  BIT             NULL,
    [UnidHasta1]                     INT             NULL,
    [UnidHasta2]                     INT             NULL,
    [UnidHasta3]                     INT             NULL,
    [UHPorc1]                        DECIMAL (14, 2) NULL,
    [UHPorc2]                        DECIMAL (14, 2) NULL,
    [UHPorc3]                        DECIMAL (14, 2) NULL,
    [PrecioPorEmbalaje]              BIT             NULL,
    CONSTRAINT [PK_AuditoriaProductos] PRIMARY KEY CLUSTERED ([FechaAuditoria] ASC, [IdProducto] ASC)
);



