CREATE TABLE [dbo].[Clientes] (
    [TipoDocumentoAnterior] VARCHAR (5)     NULL,
    [NroDocumentoAnterior]  VARCHAR (12)    NULL,
    [NombreCliente]         VARCHAR (100)   NOT NULL,
    [Direccion]             VARCHAR (100)   NOT NULL,
    [IdLocalidad]           INT             NOT NULL,
    [Telefono]              VARCHAR (100)   NULL,
    [FechaNacimiento]       DATETIME        NOT NULL,
    [NroOperacion]          INT             NULL,
    [CorreoElectronico]     VARCHAR (500)   NULL,
    [Celular]               VARCHAR (100)   NULL,
    [NombreTrabajo]         VARCHAR (100)   NULL,
    [DireccionTrabajo]      VARCHAR (100)   NULL,
    [IdLocalidadTrabajo]    INT             NULL,
    [TelefonoTrabajo]       VARCHAR (100)   NULL,
    [CorreoTrabajo]         VARCHAR (100)   NULL,
    [FechaIngresoTrabajo]   DATETIME        NULL,
    [FechaAlta]             DATETIME        NOT NULL,
    [SaldoPendiente]        DECIMAL (10, 2) NULL,
    [IdCategoria]           INT             NOT NULL,
    [IdCategoriaFiscal]     SMALLINT        NOT NULL,
    [Cuit]                  VARCHAR (13)    NULL,
    [TipoDocVendedor]       VARCHAR (5)     NOT NULL,
    [NroDocVendedor]        VARCHAR (12)    NOT NULL,
    [Observacion]           VARCHAR (1000)  NULL,
    [IdListaPrecios]        INT             NOT NULL,
    [IdZonaGeografica]      VARCHAR (20)    NOT NULL,
    [Activo]                BIT             NOT NULL,
    [LimiteDeCredito]       DECIMAL (10, 2) NOT NULL,
    [IdSucursalAsociada]    INT             NULL,
    [NombreDeFantasia]      VARCHAR (100)   NULL,
    [DescuentoRecargoPorc]  DECIMAL (6, 2)  NOT NULL,
    [IdTipoComprobante]     VARCHAR (15)    NULL,
    [IdFormasPago]          INT             NULL,
    [Foto]                  IMAGE           NULL,
    [IdTransportista]       INT             NULL,
    [IngresosBrutos]        VARCHAR (20)    NULL,
    [InscriptoIBStaFe]      BIT             NOT NULL,
    [LocalIB]               BIT             NOT NULL,
    [ConvMultilateralIB]    BIT             NOT NULL,
    [NumeroLote]            BIGINT          NULL,
    [IdCaja]                INT             NULL,
    [GeoLocalizacionLat]    FLOAT (53)      NULL,
    [GeoLocalizacionLng]    FLOAT (53)      NULL,
    [IdTipoDeExension]      SMALLINT        NULL,
    [AnioExension]          INT             NULL,
    [NroCertExension]       VARCHAR (6)     NULL,
    [NroCertPropio]         VARCHAR (12)    NULL,
    [IdCliente]             BIGINT          NOT NULL,
    [CodigoCliente]         BIGINT          NOT NULL,
    [IdClienteGarante]      BIGINT          NULL,
    [TipoDocCliente]        VARCHAR (5)     NULL,
    [NroDocCliente]         BIGINT          NULL,
    [DescuentoRecargoPorc2] DECIMAL (6, 2)  DEFAULT ((0)) NULL,
    [IdClienteCtaCte]       BIGINT          NULL,
    [PaginaWeb]             VARCHAR (100)   NULL,
    [LimiteDiasVtoFactura]  INT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED ([IdCliente] ASC),
    CONSTRAINT [FK_Clientes_Categorias] FOREIGN KEY ([IdCategoria]) REFERENCES [dbo].[Categorias] ([IdCategoria]),
    CONSTRAINT [FK_Clientes_CategoriasFiscales] FOREIGN KEY ([IdCategoriaFiscal]) REFERENCES [dbo].[CategoriasFiscales] ([IdCategoriaFiscal]),
    CONSTRAINT [FK_Clientes_Clientes] FOREIGN KEY ([IdClienteCtaCte]) REFERENCES [dbo].[Clientes] ([IdCliente]),
    CONSTRAINT [FK_Clientes_Empleados] FOREIGN KEY ([TipoDocVendedor], [NroDocVendedor]) REFERENCES [dbo].[Empleados] ([TipoDocEmpleado], [NroDocEmpleado]),
    CONSTRAINT [FK_Clientes_ListasDePrecios] FOREIGN KEY ([IdListaPrecios]) REFERENCES [dbo].[ListasDePrecios] ([IdListaPrecios]),
    CONSTRAINT [FK_Clientes_Localidades] FOREIGN KEY ([IdLocalidad]) REFERENCES [dbo].[Localidades] ([IdLocalidad]),
    CONSTRAINT [FK_Clientes_LocalidadesTrabajo] FOREIGN KEY ([IdLocalidadTrabajo]) REFERENCES [dbo].[Localidades] ([IdLocalidad]),
    CONSTRAINT [FK_Clientes_TiposComprobantes] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [dbo].[TiposComprobantes] ([IdTipoComprobante]),
    CONSTRAINT [FK_Clientes_TiposDeExension] FOREIGN KEY ([IdTipoDeExension]) REFERENCES [dbo].[TiposDeExension] ([IdTipoDeExension]),
    CONSTRAINT [FK_Clientes_TiposDocumento] FOREIGN KEY ([TipoDocumentoAnterior]) REFERENCES [dbo].[TiposDocumento] ([TipoDocumento]),
    CONSTRAINT [FK_Clientes_Transportistas] FOREIGN KEY ([IdTransportista]) REFERENCES [dbo].[Transportistas] ([IdTransportista]),
    CONSTRAINT [FK_Clientes_VentasFormasPago] FOREIGN KEY ([IdFormasPago]) REFERENCES [dbo].[VentasFormasPago] ([IdFormasPago]),
    CONSTRAINT [FK_Clientes_ZonasGeograficas] FOREIGN KEY ([IdZonaGeografica]) REFERENCES [dbo].[ZonasGeograficas] ([IdZonaGeografica]),
    CONSTRAINT [IX_Clientes] UNIQUE NONCLUSTERED ([CodigoCliente] ASC)
);



