CREATE TABLE [dbo].[Compras] (
    [IdSucursal]            INT             NOT NULL,
    [IdTipoComprobante]     VARCHAR (15)    NOT NULL,
    [Letra]                 VARCHAR (1)     NOT NULL,
    [CentroEmisor]          INT             NOT NULL,
    [NumeroComprobante]     BIGINT          NOT NULL,
    [Fecha]                 DATETIME        NOT NULL,
    [TipoDocComprador]      VARCHAR (5)     NULL,
    [NroDocComprador]       VARCHAR (12)    NULL,
    [Neto210]               DECIMAL (12, 2) NOT NULL,
    [Neto105]               DECIMAL (12, 2) NOT NULL,
    [Neto270]               DECIMAL (12, 2) NOT NULL,
    [NetoNoGravado]         DECIMAL (12, 2) NOT NULL,
    [DescuentoRecargo]      DECIMAL (12, 2) NOT NULL,
    [IVA210]                DECIMAL (12, 2) NOT NULL,
    [IVA105]                DECIMAL (12, 2) NOT NULL,
    [IVA270]                DECIMAL (12, 2) NOT NULL,
    [ImporteTotal]          DECIMAL (12, 2) NOT NULL,
    [IdCategoriaFiscal]     SMALLINT        NULL,
    [IdFormasPago]          INT             NULL,
    [Observacion]           VARCHAR (100)   NULL,
    [PorcentajeIVA]         DECIMAL (12, 2) NULL,
    [IdRubro]               INT             NULL,
    [Bruto210]              DECIMAL (12, 2) NOT NULL,
    [Bruto105]              DECIMAL (12, 2) NOT NULL,
    [Bruto270]              DECIMAL (12, 2) NOT NULL,
    [BrutoNoGravado]        DECIMAL (12, 2) NOT NULL,
    [DescuentoRecargoPorc]  DECIMAL (6, 2)  NULL,
    [PercepcionIVA]         DECIMAL (12, 2) NOT NULL,
    [PercepcionIB]          DECIMAL (12, 2) NOT NULL,
    [PercepcionGanancias]   DECIMAL (12, 2) NOT NULL,
    [PercepcionVarias]      DECIMAL (12, 2) NOT NULL,
    [PeriodoFiscal]         INT             NULL,
    [IdAsiento]             INT             NULL,
    [ImportePesos]          DECIMAL (14, 4) NOT NULL,
    [ImporteTarjetas]       DECIMAL (14, 4) NOT NULL,
    [ImporteCheques]        DECIMAL (14, 4) NOT NULL,
    [ImporteTransfBancaria] DECIMAL (14, 4) NOT NULL,
    [IdCuentaBancaria]      INT             NULL,
    [IdEstadoComprobante]   VARCHAR (10)    NULL,
    [IdTipoComprobanteFact] VARCHAR (15)    NULL,
    [LetraFact]             VARCHAR (1)     NULL,
    [CentroEmisorFact]      INT             NULL,
    [NumeroComprobanteFact] BIGINT          NULL,
    [CantidadInvocados]     INT             NOT NULL,
    [IdProveedor]           BIGINT          NOT NULL,
    [IdProveedorFact]       BIGINT          NULL,
    [Usuario]               VARCHAR (10)    NOT NULL,
    [FechaActualizacion]    DATETIME        NOT NULL,
    [IdPlanCuenta]          INT             NULL,
    CONSTRAINT [PK_Compras] PRIMARY KEY CLUSTERED ([IdSucursal] ASC, [IdTipoComprobante] ASC, [Letra] ASC, [CentroEmisor] ASC, [NumeroComprobante] ASC, [IdProveedor] ASC),
    CONSTRAINT [FK_Compras_CategoriasFiscales] FOREIGN KEY ([IdCategoriaFiscal]) REFERENCES [dbo].[CategoriasFiscales] ([IdCategoriaFiscal]),
    CONSTRAINT [FK_Compras_Compras] FOREIGN KEY ([IdSucursal], [IdTipoComprobanteFact], [LetraFact], [CentroEmisorFact], [NumeroComprobanteFact], [IdProveedorFact]) REFERENCES [dbo].[Compras] ([IdSucursal], [IdTipoComprobante], [Letra], [CentroEmisor], [NumeroComprobante], [IdProveedor]),
    CONSTRAINT [FK_Compras_Empleados] FOREIGN KEY ([TipoDocComprador], [NroDocComprador]) REFERENCES [dbo].[Empleados] ([TipoDocEmpleado], [NroDocEmpleado]),
    CONSTRAINT [FK_Compras_PeriodosFiscales] FOREIGN KEY ([PeriodoFiscal]) REFERENCES [dbo].[PeriodosFiscales] ([PeriodoFiscal]),
    CONSTRAINT [FK_Compras_Proveedores] FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[Proveedores] ([IdProveedor]),
    CONSTRAINT [FK_Compras_RubrosCompras] FOREIGN KEY ([IdRubro]) REFERENCES [dbo].[RubrosCompras] ([IdRubro]),
    CONSTRAINT [FK_Compras_Sucursales] FOREIGN KEY ([IdSucursal]) REFERENCES [dbo].[Sucursales] ([IdSucursal]),
    CONSTRAINT [FK_Compras_TiposComprobantes] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [dbo].[TiposComprobantes] ([IdTipoComprobante]),
    CONSTRAINT [FK_Compras_Usuarios] FOREIGN KEY ([Usuario]) REFERENCES [dbo].[Usuarios] ([Id]),
    CONSTRAINT [FK_Compras_VentasFormasPago] FOREIGN KEY ([IdFormasPago]) REFERENCES [dbo].[VentasFormasPago] ([IdFormasPago])
);



