CREATE TABLE [dbo].[CuentasCorrientesProv] (
    [IdSucursal]            INT             NOT NULL,
    [IdTipoComprobante]     VARCHAR (15)    NOT NULL,
    [Letra]                 VARCHAR (1)     NOT NULL,
    [CentroEmisor]          INT             NOT NULL,
    [NumeroComprobante]     BIGINT          NOT NULL,
    [Fecha]                 DATETIME        NOT NULL,
    [FechaVencimiento]      DATETIME        NOT NULL,
    [ImporteTotal]          DECIMAL (12, 2) NOT NULL,
    [IdFormasPago]          INT             NOT NULL,
    [Observacion]           VARCHAR (100)   NULL,
    [Saldo]                 DECIMAL (12, 2) NOT NULL,
    [CantidadCuotas]        INT             NOT NULL,
    [ImportePesos]          DECIMAL (12, 2) NOT NULL,
    [ImporteDolares]        DECIMAL (12, 2) NOT NULL,
    [ImporteEuros]          DECIMAL (12, 2) NOT NULL,
    [ImporteCheques]        DECIMAL (12, 2) NOT NULL,
    [ImporteTransfBancaria] DECIMAL (12, 2) NOT NULL,
    [ImporteTickets]        DECIMAL (12, 2) NOT NULL,
    [IdCuentaBancaria]      INT             NULL,
    [IdCaja]                INT             NULL,
    [NumeroPlanilla]        INT             NULL,
    [NumeroMovimiento]      INT             NULL,
    [ImporteRetenciones]    DECIMAL (14, 4) NOT NULL,
    [ImporteTarjetas]       DECIMAL (10, 2) NOT NULL,
    [IdEstadoComprobante]   VARCHAR (10)    NULL,
    [IdUsuario]             VARCHAR (10)    NOT NULL,
    [IdProveedor]           BIGINT          NOT NULL,
    [FechaActualizacion]    DATETIME        NOT NULL,
    CONSTRAINT [PK_CuentasCorrientesProv] PRIMARY KEY CLUSTERED ([IdSucursal] ASC, [IdProveedor] ASC, [IdTipoComprobante] ASC, [Letra] ASC, [CentroEmisor] ASC, [NumeroComprobante] ASC),
    CONSTRAINT [FK_CuentasCorrientesProv_CajasDetalle] FOREIGN KEY ([IdSucursal], [IdCaja], [NumeroPlanilla], [NumeroMovimiento]) REFERENCES [dbo].[CajasDetalle] ([IdSucursal], [IdCaja], [NumeroPlanilla], [NumeroMovimiento]),
    CONSTRAINT [FK_CuentasCorrientesProv_CuentasBancarias] FOREIGN KEY ([IdCuentaBancaria]) REFERENCES [dbo].[CuentasBancarias] ([IdCuentaBancaria]),
    CONSTRAINT [FK_CuentasCorrientesProv_Proveedores] FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[Proveedores] ([IdProveedor]),
    CONSTRAINT [FK_CuentasCorrientesProv_Sucursales] FOREIGN KEY ([IdSucursal]) REFERENCES [dbo].[Sucursales] ([IdSucursal]),
    CONSTRAINT [FK_CuentasCorrientesProv_TiposComprobantes] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [dbo].[TiposComprobantes] ([IdTipoComprobante]),
    CONSTRAINT [FK_CuentasCorrientesProv_Usuarios] FOREIGN KEY ([IdUsuario]) REFERENCES [dbo].[Usuarios] ([Id]),
    CONSTRAINT [FK_CuentasCorrientesProv_VentasFormasPago] FOREIGN KEY ([IdFormasPago]) REFERENCES [dbo].[VentasFormasPago] ([IdFormasPago])
);

