CREATE TABLE [dbo].[CuentasCorrientes] (
    [IdSucursal]            INT             NOT NULL,
    [IdTipoComprobante]     VARCHAR (15)    NOT NULL,
    [Letra]                 VARCHAR (1)     NOT NULL,
    [CentroEmisor]          INT             NOT NULL,
    [NumeroComprobante]     BIGINT          NOT NULL,
    [Fecha]                 DATETIME        NOT NULL,
    [FechaVencimiento]      DATETIME        NOT NULL,
    [ImporteTotal]          DECIMAL (12, 2) NOT NULL,
    [IdFormasPago]          INT             NOT NULL,
    [Observacion]           VARCHAR (100)   NULL,
    [Saldo]                 DECIMAL (12, 2) NOT NULL,
    [CantidadCuotas]        INT             NOT NULL,
    [ImportePesos]          DECIMAL (12, 2) NOT NULL,
    [ImporteDolares]        DECIMAL (12, 2) NOT NULL,
    [ImporteEuros]          DECIMAL (12, 2) NOT NULL,
    [ImporteCheques]        DECIMAL (12, 2) NOT NULL,
    [ImporteTarjetas]       DECIMAL (12, 2) NOT NULL,
    [ImporteTickets]        DECIMAL (12, 2) NOT NULL,
    [ImporteTransfBancaria] DECIMAL (12, 2) NOT NULL,
    [IdCuentaBancaria]      INT             NULL,
    [TipoDocVendedor]       VARCHAR (5)     NOT NULL,
    [NroDocVendedor]        VARCHAR (12)    NOT NULL,
    [ImporteRetenciones]    DECIMAL (12, 2) NOT NULL,
    [IdCaja]                INT             NULL,
    [NumeroPlanilla]        INT             NULL,
    [NumeroMovimiento]      INT             NULL,
    [IdEstadoComprobante]   VARCHAR (10)    NULL,
    [IdUsuario]             VARCHAR (10)    NOT NULL,
    [IdCliente]             BIGINT          NOT NULL,
    [FechaActualizacion]    DATETIME        NOT NULL,
    [IdClienteCtaCte]       BIGINT          NOT NULL,
    [IdCategoria]           INT             NOT NULL,
    [SaldoCtaCte] DECIMAL(12, 2) NULL, 
    CONSTRAINT [PK_CuentasCorrientes] PRIMARY KEY CLUSTERED ([IdSucursal] ASC, [IdTipoComprobante] ASC, [Letra] ASC, [CentroEmisor] ASC, [NumeroComprobante] ASC),
    CONSTRAINT [FK_CuentasCorrientes_CajasDetalle] FOREIGN KEY ([IdSucursal], [IdCaja], [NumeroPlanilla], [NumeroMovimiento]) REFERENCES [dbo].[CajasDetalle] ([IdSucursal], [IdCaja], [NumeroPlanilla], [NumeroMovimiento]),
    CONSTRAINT [FK_CuentasCorrientes_Clientes] FOREIGN KEY ([IdCliente]) REFERENCES [dbo].[Clientes] ([IdCliente]),
    CONSTRAINT [FK_CuentasCorrientes_CuentasBancarias] FOREIGN KEY ([IdCuentaBancaria]) REFERENCES [dbo].[CuentasBancarias] ([IdCuentaBancaria]),
    CONSTRAINT [FK_CuentasCorrientes_Sucursales] FOREIGN KEY ([IdSucursal]) REFERENCES [dbo].[Sucursales] ([IdSucursal]),
    CONSTRAINT [FK_CuentasCorrientes_TiposComprobantes] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [dbo].[TiposComprobantes] ([IdTipoComprobante]),
    CONSTRAINT [FK_CuentasCorrientes_Usuarios] FOREIGN KEY ([IdUsuario]) REFERENCES [dbo].[Usuarios] ([Id]),
    CONSTRAINT [FK_CuentasCorrientes_VentasFormasPago] FOREIGN KEY ([IdFormasPago]) REFERENCES [dbo].[VentasFormasPago] ([IdFormasPago])
);



