CREATE TABLE [dbo].[MovimientosCompras] (
    [IdSucursal]          INT             NOT NULL,
    [IdTipoMovimiento]    VARCHAR (15)    NOT NULL,
    [NumeroMovimiento]    BIGINT          NOT NULL,
    [FechaMovimiento]     DATETIME        NOT NULL,
    [Neto210]             DECIMAL (12, 2) NOT NULL,
    [Neto105]             DECIMAL (12, 2) NOT NULL,
    [Neto270]             DECIMAL (12, 2) NOT NULL,
    [NetoNoGravado]       DECIMAL (12, 2) NOT NULL,
    [IVA210]              DECIMAL (12, 2) NOT NULL,
    [IVA105]              DECIMAL (12, 2) NOT NULL,
    [IVA270]              DECIMAL (12, 2) NOT NULL,
    [Total]               DECIMAL (12, 2) NOT NULL,
    [PorcentajeIVA]       DECIMAL (12, 2) NULL,
    [IdCategoriaFiscal]   SMALLINT        NULL,
    [IdTipoComprobante]   VARCHAR (15)    NULL,
    [Letra]               VARCHAR (1)     NULL,
    [CentroEmisor]        INT             NULL,
    [NumeroComprobante]   BIGINT          NULL,
    [IdSucursal2]         INT             NULL,
    [Usuario]             VARCHAR (10)    NOT NULL,
    [Observacion]         VARCHAR (100)   NULL,
    [PercepcionIVA]       DECIMAL (12, 2) NOT NULL,
    [PercepcionIB]        DECIMAL (12, 2) NOT NULL,
    [PercepcionGanancias] DECIMAL (12, 2) NOT NULL,
    [PercepcionVarias]    DECIMAL (12, 2) NOT NULL,
    [IdProduccion]        INT             NULL,
    [IdProveedor]         BIGINT          NULL,
    CONSTRAINT [PK_Movimientos] PRIMARY KEY CLUSTERED ([IdSucursal] ASC, [IdTipoMovimiento] ASC, [NumeroMovimiento] ASC),
    CONSTRAINT [FK_MovimientosCompras_CategoriasFiscales] FOREIGN KEY ([IdCategoriaFiscal]) REFERENCES [dbo].[CategoriasFiscales] ([IdCategoriaFiscal]),
    CONSTRAINT [FK_MovimientosCompras_Proveedores] FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[Proveedores] ([IdProveedor]),
    CONSTRAINT [FK_MovimientosCompras_Sucursales] FOREIGN KEY ([IdSucursal]) REFERENCES [dbo].[Sucursales] ([IdSucursal]),
    CONSTRAINT [FK_MovimientosCompras_Sucursales2] FOREIGN KEY ([IdSucursal2]) REFERENCES [dbo].[Sucursales] ([IdSucursal]),
    CONSTRAINT [FK_MovimientosCompras_TiposComprobantes] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [dbo].[TiposComprobantes] ([IdTipoComprobante]),
    CONSTRAINT [FK_MovimientosCompras_TiposMovimientos] FOREIGN KEY ([IdTipoMovimiento]) REFERENCES [dbo].[TiposMovimientos] ([IdTipoMovimiento]),
    CONSTRAINT [FK_MovimientosCompras_Usuarios] FOREIGN KEY ([Usuario]) REFERENCES [dbo].[Usuarios] ([Id])
);

