CREATE TABLE [dbo].[Productos] (
    [IdProducto]                     VARCHAR (15)    NOT NULL,
    [NombreProducto]                 VARCHAR (60)    NOT NULL,
    [Tamano]                         DECIMAL (7, 3)  NULL,
    [IdUnidadDeMedida]               CHAR (2)        NULL,
    [IdMarca]                        INT             NOT NULL,
    [IdRubro]                        INT             NOT NULL,
    [MesesGarantia]                  INT             NOT NULL,
    [Activo]                         BIT             NOT NULL,
    [AfectaStock]                    BIT             NOT NULL,
    [IdModelo]                       INT             NULL,
    [IdSubRubro]                     INT             NULL,
    [Foto]                           IMAGE           NULL,
    [Lote]                           BIT             NOT NULL,
    [NroSerie]                       BIT             NOT NULL,
    [IdTipoImpuesto]                 VARCHAR (5)     NOT NULL,
    [Alicuota]                       DECIMAL (6, 2)  NOT NULL,
    [CodigoDeBarras]                 VARCHAR (15)    NULL,
    [EsServicio]                     BIT             NOT NULL,
    [Observacion]                    VARCHAR (300)   NOT NULL,
    [PublicarEnWeb]                  BIT             NOT NULL,
    [IdMoneda]                       INT             NOT NULL,
    [EsDeVentas]                     BIT             NOT NULL,
    [EsDeCompras]                    BIT             NOT NULL,
    [DescontarStockComponentes]      BIT             NOT NULL,
    [EsCompuesto]                    BIT             NOT NULL,
    [CodigoDeBarrasConPrecio]        BIT             NOT NULL,
    [EsAlquilable]                   BIT             NOT NULL,
    [EquipoMarca]                    VARCHAR (20)    NULL,
    [EquipoModelo]                   VARCHAR (20)    NULL,
    [NumeroSerie]                    VARCHAR (50)    NULL,
    [CaractSII]                      VARCHAR (50)    NULL,
    [Anio]                           INT             NULL,
    [PermiteModificarDescripcion]    BIT             NOT NULL,
    [Alicuota2]                      DECIMAL (6, 2)  NULL,
    [PagaIngresosBrutos]             BIT             NOT NULL,
    [Embalaje]                       INT             NOT NULL,
    [Kilos]                          DECIMAL (10, 3) NOT NULL,
    [IdFormula]                      INT             NULL,
    [IdProductoMercosur]             VARCHAR (50)    NULL,
    [IdProductoSecretaria]           VARCHAR (50)    NULL,
    [PublicarListaDePreciosClientes] BIT             NOT NULL,
    [FacturacionCantidadNegativa]    BIT             NOT NULL,
    [SolicitaEnvase]                 BIT             NOT NULL,
    [AlertaDeCaja]                   BIT             NOT NULL,
    [NombreCorto]                    VARCHAR (30)    NULL,
    [EsRetornable]                   BIT             DEFAULT ('False') NOT NULL,
    [Orden]                          INT             DEFAULT ((1)) NULL,
    [ModalidadCodigoDeBarras]        VARCHAR (20)    NULL,
    [CodigoLargoProducto]            VARCHAR (30)    NULL,
    [IdProveedor]                    BIGINT          NULL,
    [EsObservacion]                  BIT             DEFAULT ('False') NOT NULL,
    [UnidHasta1]                     INT             DEFAULT ((0)) NOT NULL,
    [UnidHasta2]                     INT             DEFAULT ((0)) NOT NULL,
    [UnidHasta3]                     INT             DEFAULT ((0)) NOT NULL,
    [UHPorc1]                        DECIMAL (14, 2) DEFAULT ((0)) NOT NULL,
    [UHPorc2]                        DECIMAL (14, 2) DEFAULT ((0)) NOT NULL,
    [UHPorc3]                        DECIMAL (14, 2) DEFAULT ((0)) NOT NULL,
    [PrecioPorEmbalaje]              BIT             DEFAULT ('False') NOT NULL,
    CONSTRAINT [PK_Productos] PRIMARY KEY CLUSTERED ([IdProducto] ASC),
    CONSTRAINT [FK_Productos_Impuestos] FOREIGN KEY ([IdTipoImpuesto], [Alicuota]) REFERENCES [dbo].[Impuestos] ([IdTipoImpuesto], [Alicuota]),
    CONSTRAINT [FK_Productos_Marcas] FOREIGN KEY ([IdMarca]) REFERENCES [dbo].[Marcas] ([IdMarca]),
    CONSTRAINT [FK_Productos_Modelos] FOREIGN KEY ([IdModelo]) REFERENCES [dbo].[Modelos] ([IdModelo]),
    CONSTRAINT [FK_Productos_Monedas] FOREIGN KEY ([IdMoneda]) REFERENCES [dbo].[Monedas] ([IdMoneda]),
    CONSTRAINT [FK_Productos_Proveedores] FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[Proveedores] ([IdProveedor]),
    CONSTRAINT [FK_Productos_SubRubros] FOREIGN KEY ([IdSubRubro]) REFERENCES [dbo].[SubRubros] ([IdSubRubro]),
    CONSTRAINT [FK_Productos_TiposDeProductos] FOREIGN KEY ([IdRubro]) REFERENCES [dbo].[Rubros] ([IdRubro]),
    CONSTRAINT [FK_Productos2_Impuestos] FOREIGN KEY ([IdTipoImpuesto], [Alicuota2]) REFERENCES [dbo].[Impuestos] ([IdTipoImpuesto], [Alicuota])
);




GO
CREATE NONCLUSTERED INDEX [IX_Productos_CodigoDeBarras]
    ON [dbo].[Productos]([CodigoDeBarras] ASC);

