CREATE TABLE [dbo].[TiposComprobantes] (
    [IdTipoComprobante]           VARCHAR (15)    NOT NULL,
    [EsFiscal]                    BIT             NOT NULL,
    [Descripcion]                 VARCHAR (25)    NOT NULL,
    [Tipo]                        VARCHAR (15)    NOT NULL,
    [CoeficienteStock]            INT             NOT NULL,
    [GrabaLibro]                  BIT             NOT NULL,
    [EsFacturable]                BIT             NOT NULL,
    [LetrasHabilitadas]           VARCHAR (20)    NULL,
    [CantidadMaximaItems]         INT             NOT NULL,
    [Imprime]                     BIT             NOT NULL,
    [CoeficienteValores]          INT             NOT NULL,
    [ModificaAlFacturar]          VARCHAR (15)    NULL,
    [EsFacturador]                BIT             NOT NULL,
    [AfectaCaja]                  BIT             NOT NULL,
    [CargaPrecioActual]           BIT             NOT NULL,
    [ActualizaCtaCte]             BIT             NOT NULL,
    [DescripcionAbrev]            VARCHAR (10)    NOT NULL,
    [PuedeSerBorrado]             BIT             NOT NULL,
    [CantidadCopias]              INT             NOT NULL,
    [EsRemitoTransportista]       BIT             NOT NULL,
    [ComprobantesAsociados]       VARCHAR (500)   NULL,
    [EsComercial]                 BIT             NOT NULL,
    [CantidadMaximaItemsObserv]   INT             NOT NULL,
    [IdTipoComprobanteSecundario] VARCHAR (15)    NULL,
    [ImporteTope]                 DECIMAL (10, 2) NOT NULL,
    [IdTipoComprobanteEpson]      CHAR (1)        NOT NULL,
    [UsaFacturacionRapida]        BIT             NOT NULL,
    [ImporteMinimo]               DECIMAL (10, 2) NOT NULL,
    [EsElectronico]               BIT             NOT NULL,
    [UsaFacturacion]              BIT             NOT NULL,
    [UtilizaImpuestos]            BIT             NOT NULL,
    [NumeracionAutomatica]        BIT             NOT NULL,
    [GeneraObservConInvocados]    BIT             NOT NULL,
    [ImportaObservDeInvocados]    BIT             NOT NULL,
    [IdPlanCuenta]                INT             NOT NULL,
    [EsAnticipo]                  BIT             NOT NULL,
    [EsRecibo]                    BIT             NOT NULL,
    [Grupo]                       VARCHAR (15)    NOT NULL,
    [EsPreElectronico]            BIT             NOT NULL,
    CONSTRAINT [PK_TiposComprobantes] PRIMARY KEY CLUSTERED ([IdTipoComprobante] ASC),
    CONSTRAINT [FK_TiposComprobantes_ContabilidadPlanes] FOREIGN KEY ([IdPlanCuenta]) REFERENCES [dbo].[ContabilidadPlanes] ([IdPlanCuenta]),
    CONSTRAINT [FK_TiposComprobantes_TiposComprobantes] FOREIGN KEY ([IdTipoComprobanteSecundario]) REFERENCES [dbo].[TiposComprobantes] ([IdTipoComprobante])
);



