CREATE TABLE [dbo].[Ventas] (
    [IdSucursal]            INT             NOT NULL,
    [IdTipoComprobante]     VARCHAR (15)    NOT NULL,
    [Letra]                 VARCHAR (1)     NOT NULL,
    [CentroEmisor]          INT             NOT NULL,
    [NumeroComprobante]     BIGINT          NOT NULL,
    [Fecha]                 DATETIME        NOT NULL,
    [TipoDocVendedor]       VARCHAR (5)     NOT NULL,
    [NroDocVendedor]        VARCHAR (12)    NOT NULL,
    [SubTotal]              DECIMAL (12, 2) NOT NULL,
    [DescuentoRecargo]      DECIMAL (12, 2) NOT NULL,
    [ImporteTotal]          DECIMAL (12, 2) NOT NULL,
    [IdCategoriaFiscal]     SMALLINT        NOT NULL,
    [IdFormasPago]          INT             NOT NULL,
    [Observacion]           VARCHAR (100)   NULL,
    [ImporteBruto]          DECIMAL (12, 2) NOT NULL,
    [DescuentoRecargoPorc]  DECIMAL (6, 2)  NOT NULL,
    [IdEstadoComprobante]   VARCHAR (10)    NULL,
    [IdTipoComprobanteFact] VARCHAR (15)    NULL,
    [LetraFact]             VARCHAR (1)     NULL,
    [CentroEmisorFact]      INT             NULL,
    [NumeroComprobanteFact] BIGINT          NULL,
    [IdCaja]                INT             NULL,
    [NumeroPlanilla]        INT             NULL,
    [NumeroMovimiento]      INT             NULL,
    [ImportePesos]          DECIMAL (12, 2) NOT NULL,
    [ImporteTickets]        DECIMAL (12, 2) NOT NULL,
    [ImporteTarjetas]       DECIMAL (12, 2) NOT NULL,
    [ImporteCheques]        DECIMAL (12, 2) NOT NULL,
    [Kilos]                 DECIMAL (10, 3) NOT NULL,
    [Bultos]                INT             NOT NULL,
    [ValorDeclarado]        DECIMAL (12, 2) NOT NULL,
    [IdTransportista]       INT             NULL,
    [NumeroLote]            BIGINT          NOT NULL,
    [TotalImpuestos]        DECIMAL (12, 2) NOT NULL,
    [CantidadInvocados]     INT             NOT NULL,
    [CantidadLotes]         INT             NOT NULL,
    [Usuario]               VARCHAR (10)    NOT NULL,
    [FechaAlta]             DATETIME        NOT NULL,
    [CAE]                   VARCHAR (30)    NULL,
    [CAEVencimiento]        DATETIME        NULL,
    [Utilidad]              DECIMAL (12, 2) NOT NULL,
    [FechaTransmisionAFIP]  DATETIME        NULL,
    [CotizacionDolar]       DECIMAL (7, 3)  NOT NULL,
    [ComisionVendedor]      DECIMAL (12, 2) NOT NULL,
    [FechaImpresion]        DATETIME        NULL,
    [IdAsiento]             INT             NULL,
    [MercDespachada]        BIT             NOT NULL,
    [ImporteTransfBancaria] DECIMAL (14, 4) NOT NULL,
    [IdCuentaBancaria]      INT             NULL,
    [IdActividad]           INT             NULL,
    [IdProvincia]           CHAR (2)        NULL,
    [FechaEnvio]            DATETIME        NULL,
    [NumeroReparto]         INT             NULL,
    [FechaRendicion]        DATETIME        NULL,
    [IdCliente]             BIGINT          NOT NULL,
    [IdProveedor]           BIGINT          NULL,
    [FechaActualizacion]    DATETIME        NOT NULL,
    [Direccion]             VARCHAR (100)   NOT NULL,
    [IdLocalidad]           INT             NOT NULL,
    [IdCategoria]           INT             NOT NULL,
    [CodigoErrorAfip]       VARCHAR (500)   NULL,
    [IdPlanCuenta]          INT             NULL,
    CONSTRAINT [PK_Ventas] PRIMARY KEY CLUSTERED ([IdTipoComprobante] ASC, [Letra] ASC, [CentroEmisor] ASC, [NumeroComprobante] ASC, [IdSucursal] ASC),
    CONSTRAINT [FK_Ventas_CajasDetalle] FOREIGN KEY ([IdSucursal], [IdCaja], [NumeroPlanilla], [NumeroMovimiento]) REFERENCES [dbo].[CajasDetalle] ([IdSucursal], [IdCaja], [NumeroPlanilla], [NumeroMovimiento]),
    CONSTRAINT [FK_Ventas_CategoriasFiscales] FOREIGN KEY ([IdCategoriaFiscal]) REFERENCES [dbo].[CategoriasFiscales] ([IdCategoriaFiscal]),
    CONSTRAINT [FK_Ventas_Clientes] FOREIGN KEY ([IdCliente]) REFERENCES [dbo].[Clientes] ([IdCliente]),
    CONSTRAINT [FK_Ventas_Empleados] FOREIGN KEY ([TipoDocVendedor], [NroDocVendedor]) REFERENCES [dbo].[Empleados] ([TipoDocEmpleado], [NroDocEmpleado]),
    CONSTRAINT [FK_Ventas_Localidades] FOREIGN KEY ([IdLocalidad]) REFERENCES [dbo].[Localidades] ([IdLocalidad]),
    CONSTRAINT [FK_Ventas_Proveedores] FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[Proveedores] ([IdProveedor]),
    CONSTRAINT [FK_Ventas_Sucursales] FOREIGN KEY ([IdSucursal]) REFERENCES [dbo].[Sucursales] ([IdSucursal]),
    CONSTRAINT [FK_Ventas_TiposComprobantes] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [dbo].[TiposComprobantes] ([IdTipoComprobante]),
    CONSTRAINT [FK_Ventas_TiposComprobantes1] FOREIGN KEY ([IdTipoComprobanteFact]) REFERENCES [dbo].[TiposComprobantes] ([IdTipoComprobante]),
    CONSTRAINT [FK_Ventas_Transportistas] FOREIGN KEY ([IdTransportista]) REFERENCES [dbo].[Transportistas] ([IdTransportista]),
    CONSTRAINT [FK_Ventas_Usuarios] FOREIGN KEY ([Usuario]) REFERENCES [dbo].[Usuarios] ([Id]),
    CONSTRAINT [FK_Ventas_Ventas] FOREIGN KEY ([IdTipoComprobanteFact], [LetraFact], [CentroEmisorFact], [NumeroComprobanteFact], [IdSucursal]) REFERENCES [dbo].[Ventas] ([IdTipoComprobante], [Letra], [CentroEmisor], [NumeroComprobante], [IdSucursal]),
    CONSTRAINT [FK_Ventas_VentasFormasPago] FOREIGN KEY ([IdFormasPago]) REFERENCES [dbo].[VentasFormasPago] ([IdFormasPago])
);




GO
CREATE NONCLUSTERED INDEX [IX_Ventas_Fecha]
    ON [dbo].[Ventas]([Fecha] ASC);

