
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
GO
ALTER TABLE dbo.CRMTiposNovedades ADD UsuarioRequerido bit NULL
ALTER TABLE dbo.CRMTiposNovedades ADD UsuarioPorDefecto bit NULL
GO

UPDATE CRMTiposNovedades SET UsuarioRequerido = 'True';
UPDATE CRMTiposNovedades SET UsuarioPorDefecto = 'True';

ALTER TABLE dbo.CRMTiposNovedades ALTER COLUMN UsuarioRequerido bit NOT NULL
ALTER TABLE dbo.CRMTiposNovedades ALTER COLUMN UsuarioPorDefecto bit NOT NULL
GO

ALTER TABLE dbo.CRMTiposNovedades SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
