
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
GO
ALTER TABLE dbo.CRMTiposNovedades ADD ProximoContactoRequerido bit NULL
GO

UPDATE CRMTiposNovedades  
  SET ProximoContactoRequerido = (CASE WHEN IdTipoNovedad = 'PROSP' THEN 'True' ELSE 'False' END);

ALTER TABLE dbo.CRMTiposNovedades ALTER COLUMN ProximoContactoRequerido bit NOT NULL
GO

ALTER TABLE dbo.CRMTiposNovedades SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
