
DECLARE @CUITEMPRESA varchar(10)
DECLARE @NOMBREEMPRESA varchar(100)
DECLARE @PROVINCIA char(2)

SET @CUITEMPRESA = (SELECT ValorParametro FROM dbo.Parametros WHERE IdParametro = 'CUITEMPRESA');
SET @NOMBREEMPRESA = (SELECT ValorParametro FROM dbo.Parametros WHERE IdParametro = 'NOMBREEMPRESA');

-- CUITs Delta Marina
IF (@CUITEMPRESA = '30707965777' OR
    @CUITEMPRESA = '30715139118' OR 
    @CUITEMPRESA = '30715161601' OR 
    @CUITEMPRESA = '30715200615')
BEGIN
    SET @PROVINCIA = 'BS'
END
ELSE
BEGIN
    SET @PROVINCIA = 'SF'
END

PRINT @CUITEMPRESA + '  -  ' + @NOMBREEMPRESA + '  -  ' + @PROVINCIA

UPDATE VentasImpuestos
   SET IdProvincia = @PROVINCIA
 WHERE IdTipoImpuesto = 'PIIBB';
