create view [resvtacons] as
SELECT '' as [Periodo]
      ,'' as [Rubro]
      ,'' as [SubRubro]
      ,'' as [Agrupacion]
      ,'' as [Articulo]
      ,'' as [Codigo]
      ,'' as [Clase]
      ,'' as [Descripcion]
      ,'' as [TipoArt]
      ,2014 as [Año]
      ,1 as [Cuatrimestre]
      ,1 as [Mes]
      ,1 as [semana]
      ,'' as [diasemana]
      ,1 as [dia]
      ,'19000101' as [Fecha]
      ,'' as [TipoVta]
      ,0 as [CBT]
      ,'' as [Signo]
      ,0 as [CE]
      ,0 as [Numero]
      ,0 as [Cliente]
      ,'' as [NombreCliente]
      ,'' as [TipoCliente]
      ,'' as [ZonaVenta]
      ,'' as [Ciudad]
      ,'' as [Provincia]
      ,0 as [Kilos]
      ,0 as [Cantidad]
      ,0 as [Precio]
      ,0 as [BonArt]
      ,0 as [BonCli]
      ,'' as [VendeAct]
      ,'' as [VendeHis]
      ,0 as [costo]
      ,'' as [Empresa]
      ,0 as [ImporteVta]
      ,0 as [CostoVta]
      ,0 as [ImporteRentab]
      ,''as [TIPODATO]
      ,'' as [GrupoCliente]
      ,'' as [MARCA]
      ,'' as[ClaseCliente]
      ,'' as [AñoMes]
      ,0 as [CoDUN]
      ,'' as [UN]