create view salcli as 
SELECT 0 as [codcli]
      ,'' as [Cliente]
      ,'' as [TiCBT]
      ,0 as [CE]
      ,0 as [Numero]
      ,'19000101' as [Fecha]
      ,'19000101' as [Vencimiento]
      ,0 as[Debe]
      ,0 as[Haber]
      ,0 as[Saldo]
      ,'' as [Estado]
      ,'' as [Periodo]
      ,0 as [Dias]
      ,'' as [VendeAct]
      ,'' as [TipoCliente]
      ,'19000101' as[UltGes]
      ,'' as[ObsGes]