create view [StkDispValci] as
SELECT '' as [Rubro]
      ,'' as [SubRubro]
      ,'' as [Articulo]
      ,0 as [Stock]
      ,0 as[PedPen]
      ,0 as[OCPen]
      ,0 as[StockDisp]
      ,0 as[PreRep]
      ,0 as[StockVal]
      ,0 as[StockDispVal]
      ,'' as [Empresa]
      ,'' as [INMOV]
      ,'' as [Orden]