
PRINT '1. Creo PK: Compras'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Compras ADD CONSTRAINT
	PK_Compras PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdTipoComprobante,
	Letra,
	CentroEmisor,
	NumeroComprobante,
	IdProveedor	
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Compras SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '2. Creo PK: ComprasCheques'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ComprasCheques ADD CONSTRAINT
	PK_ComprasCheques PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdTipoComprobante,
	Letra,
	CentroEmisor,
	NumeroComprobante,
	IdProveedor,
	NumeroCheque,
	IdBanco,
	IdBancoSucursal,
	IdLocalidad	
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ComprasCheques SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '3. Creo PK: ComprasObservaciones'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ComprasObservaciones ADD CONSTRAINT
	PK_ComprasObservaciones PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdTipoComprobante,
	Letra,
	CentroEmisor,
	NumeroComprobante,
	IdProveedor,
	Linea
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ComprasObservaciones SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '4. Creo PK: ComprasProductos'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ComprasProductos ADD CONSTRAINT
	PK_ComprasProductos PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdTipoComprobante,
	Letra,
	CentroEmisor,
	NumeroComprobante,
	IdProveedor,
	Orden,
	IdProducto	
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ComprasProductos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '5. Creo PK: CuentasCorrientesProv'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CuentasCorrientesProv ADD CONSTRAINT
	PK_CuentasCorrientesProv PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdProveedor,
	IdTipoComprobante,
	Letra,
	CentroEmisor,
	NumeroComprobante	
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CuentasCorrientesProv SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '6. Creo PK: CuentasCorrientesProvCheques'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CuentasCorrientesProvCheques ADD CONSTRAINT
	PK_CuentasCorrientesProvCheques PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdProveedor,
	IdTipoComprobante,
	Letra,
	CentroEmisor,
	NumeroComprobante,
	NumeroCheque,
	IdBanco,
	IdBancoSucursal,
	IdLocalidad
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CuentasCorrientesProvCheques SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '7. Creo PK: CuentasCorrientesProvPagos'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CuentasCorrientesProvPagos ADD CONSTRAINT
	PK_CuentasCorrientesProvPagos PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdProveedor,
	IdTipoComprobante,
	Letra,
	CentroEmisor,
	NumeroComprobante,
	CuotaNumero
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CuentasCorrientesProvPagos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '8. Creo PK: CuentasCorrientesProvRetenciones'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CuentasCorrientesProvRetenciones ADD CONSTRAINT
	PK_CuentasCorrientesProvRetenciones PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdProveedor,
	IdTipoComprobante,
	Letra,
	CentroEmisor,
	NumeroComprobante,
	IdTipoImpuesto,
	EmisorRetencion,
	NumeroRetencion
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.CuentasCorrientesProvRetenciones SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '9. Creo PK: ProductosProveedores'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ProductosProveedores ADD CONSTRAINT
	PK_ProductosProveedores PRIMARY KEY CLUSTERED 
	(
	IdProveedor,
	IdProducto
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ProductosProveedores SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '10.1 Borro Proveedores.FK_Proveedores_2 (Indice Unico de IdProveedor)'
GO

ALTER TABLE dbo.Proveedores DROP CONSTRAINT [FK_Proveedores_2]
GO

PRINT '10.2 Creo PK: Proveedores'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Proveedores ADD CONSTRAINT
	PK_Proveedores PRIMARY KEY CLUSTERED 
	(
	IdProveedor
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Proveedores SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


PRINT '10.3 Renombros Campos: Proveedores.Tipo y NroDocProveedor'
GO
EXEC sp_rename 'Proveedores.TipoDocProveedor', 'TipoDocProveedorAnterior', 'COLUMN'
GO
EXEC sp_rename 'Proveedores.NroDocProveedor', 'NroDocProveedorAnterior', 'COLUMN'
GO


PRINT '10.4 Creo Campos: Proveedores.Tipo y NroDocProveedor'
GO
ALTER TABLE Proveedores ADD TipoDocProveedor varchar(5) NULL
GO
ALTER TABLE Proveedores ADD NroDocProveedor bigint NULL
GO


PRINT '10.5 Actualizo Campos: Proveedores.Tipo y NroDocProveedor'
GO

UPDATE Proveedores 
   SET TipoDocProveedor = TipoDocProveedorAnterior
     , NroDocProveedor = NroDocProveedorAnterior
   WHERE TipoDocProveedorAnterior NOT IN ('COD', 'ID', 'CUIT', 'CUIL')
GO


/* ------------------------------ */

PRINT '11. Creo PK: RecepcionNotasProveedores'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RecepcionNotasProveedores ADD CONSTRAINT
	PK_RecepcionNotasProveedores PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	NroNota,
	IdProveedor
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.RecepcionNotasProveedores SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '12. Creo PK: RecepcionNotasProveedoresF'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RecepcionNotasProveedoresF ADD CONSTRAINT
	PK_RecepcionNotasProveedoresF PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	NroNota,
	IdProveedor
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.RecepcionNotasProveedoresF SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */

PRINT '13. Creo PK: RetencionesCompras'
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RetencionesCompras ADD CONSTRAINT
	PK_RetencionesCompras PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdTipoImpuesto,
	EmisorRetencion,
	NumeroRetencion,
	IdProveedor
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.RetencionesCompras SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* ------------------------------ */
