
/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AduanasDestinaciones SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AduanasDespachantes SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AduanasAgentesTransporte SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Aduanas SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Compras ADD CONSTRAINT FK_Compras_Aduanas
    FOREIGN KEY (IdAduana)
    REFERENCES dbo.Aduanas(IdAduana) ON UPDATE  NO ACTION ON DELETE  NO ACTION 
GO
ALTER TABLE dbo.Compras ADD CONSTRAINT FK_Compras_AduanasAgentesTransporte
    FOREIGN KEY (IdAgenteTransporte)
    REFERENCES dbo.AduanasAgentesTransporte (IdAgenteTransporte) ON UPDATE  NO ACTION ON DELETE  NO ACTION 
GO
ALTER TABLE dbo.Compras ADD CONSTRAINT FK_Compras_AduanasDespachantes
    FOREIGN KEY (IdDespachante)
    REFERENCES dbo.AduanasDespachantes (IdDespachante) ON UPDATE  NO ACTION ON DELETE  NO ACTION 
GO
ALTER TABLE dbo.Compras ADD CONSTRAINT FK_Compras_AduanasDestinaciones
    FOREIGN KEY (IdDestinacion)
    REFERENCES dbo.AduanasDestinaciones (IdDestinacion) ON UPDATE  NO ACTION ON DELETE  NO ACTION 
GO
ALTER TABLE dbo.Compras SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
