/* Elimino la Referencia desde PedidosProductos */

BEGIN TRANSACTION
	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON
COMMIT

--*** NO hace falta porque no cambia ningun campo ***
--BEGIN TRANSACTION
--	GO
--	ALTER TABLE dbo.PedidosProductos
--	DROP CONSTRAINT FK_PedidosProductos_Pedidos
--	GO
--	ALTER TABLE dbo.PedidosProductos SET (LOCK_ESCALATION = TABLE)
--	GO
--COMMIT

BEGIN TRANSACTION
	GO
	ALTER TABLE dbo.PedidosEstados
	DROP CONSTRAINT FK_PedidosEstados_PedidosProductos
	GO
	ALTER TABLE dbo.PedidosEstados SET (LOCK_ESCALATION = TABLE)
	GO
COMMIT

BEGIN TRANSACTION
	GO
	ALTER TABLE dbo.Pedidos SET (LOCK_ESCALATION = TABLE)
	GO
COMMIT


/* Elimino la Clave Primaria (PK) */

BEGIN TRANSACTION
	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
	GO
	ALTER TABLE dbo.PedidosProductos
		DROP CONSTRAINT PK_PedidosProductos
	GO
	ALTER TABLE dbo.PedidosProductos SET (LOCK_ESCALATION = TABLE)
	GO
COMMIT


/* Ajusto el campo */
ALTER TABLE dbo.PedidosProductos ADD Orden Int NULL
GO

UPDATE dbo.PedidosProductos
   --SET Orden = (SELECT ROW_NUMBER() OVER(ORDER BY IdSucursal, IdPedido, IdProducto) FROM PedidosProductos B)
   SET Orden = IdProducto
 WHERE Orden IS NULL
GO
 
ALTER TABLE dbo.PedidosProductos ALTER COLUMN Orden Int NOT NULL
GO


/* Vuelvo a Crear la Clave Primaria (PK) */
BEGIN TRANSACTION
	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON
COMMIT


BEGIN TRANSACTION
	GO
	ALTER TABLE dbo.PedidosProductos ADD CONSTRAINT
		PK_PedidosProductos PRIMARY KEY CLUSTERED 
		(
		IdSucursal,
		IdPedido,
		IdProducto,
		Orden
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

	GO
	ALTER TABLE dbo.PedidosProductos SET (LOCK_ESCALATION = TABLE)
	GO
COMMIT
