/* Elimino la Referencia desde PedidosProductos */

BEGIN TRANSACTION
	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
	GO
	ALTER TABLE dbo.PedidosEstadosProveedores
	DROP CONSTRAINT FK_PedidosEstadosProveedores_PedidosProductosProveedores
	GO
	ALTER TABLE dbo.PedidosEstadosProveedores SET (LOCK_ESCALATION = TABLE)
	GO
COMMIT

BEGIN TRANSACTION
	GO
	ALTER TABLE dbo.PedidosProveedores SET (LOCK_ESCALATION = TABLE)
	GO
COMMIT


/* Elimino la Clave Primaria (PK) */

BEGIN TRANSACTION
	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
	GO
	ALTER TABLE dbo.PedidosProductosProveedores
		DROP CONSTRAINT PK_PedidosProductosProveedores
	GO
	ALTER TABLE dbo.PedidosProductosProveedores SET (LOCK_ESCALATION = TABLE)
	GO
COMMIT


/* Ajusto el campo */
ALTER TABLE dbo.PedidosProductosProveedores ADD Orden Int NULL
GO

UPDATE dbo.PedidosProductosProveedores
   --SET Orden = (SELECT ROW_NUMBER() OVER(ORDER BY IdSucursal, IdPedido, IdProducto) FROM PedidosProductos B)
   SET Orden = IdProducto
 WHERE Orden IS NULL
GO
 
ALTER TABLE dbo.PedidosProductosProveedores ALTER COLUMN Orden Int NOT NULL
GO


/* Vuelvo a Crear la Clave Primaria (PK) */
BEGIN TRANSACTION
	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON
COMMIT


BEGIN TRANSACTION
	GO
	ALTER TABLE dbo.PedidosProductosProveedores ADD CONSTRAINT
		PK_PedidosProductosProveedores PRIMARY KEY CLUSTERED 
		(
		IdSucursal,
		IdPedido,
		IdProducto,
		Orden
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

	GO
	ALTER TABLE dbo.PedidosProductosProveedores SET (LOCK_ESCALATION = TABLE)
	GO
COMMIT
