
UPDATE Parametros
   SET IdParametro = 'FACTURACIONTICKETINCLUYERECARGOGENERAL'
      ,DescripcionParametro = 'Ticket: incluye Recargo General'
 WHERE IdParametro = 'FACTURACIONTICKETINCLUYEDESCUENTORECARGOGENERAL'
GO
