/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Productos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Conceptos ADD IdProducto varchar(15) NULL
GO
ALTER TABLE dbo.Conceptos ADD CONSTRAINT FK_Conceptos_Productos
    FOREIGN KEY (IdProducto)
    REFERENCES dbo.Productos (IdProducto)
    ON UPDATE  NO ACTION ON DELETE  NO ACTION 
GO
ALTER TABLE dbo.Conceptos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
