/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
PRINT ''
PRINT '1. Función: Campo Pedidos IdMoneda'
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Monedas SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Pedidos ADD IdMoneda int NULL
GO
UPDATE Pedidos SET IdMoneda = 1;

ALTER TABLE dbo.Pedidos ALTER COLUMN IdMoneda int NOT NULL
GO
ALTER TABLE dbo.Pedidos ADD CONSTRAINT FK_Pedidos_Monedas
    FOREIGN KEY (IdMoneda)
    REFERENCES dbo.Monedas (IdMoneda)
    ON UPDATE  NO ACTION ON DELETE  NO ACTION 
GO
ALTER TABLE dbo.Pedidos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
PRINT ''
PRINT '2.- Funcion Campo Pedidos IdClienteVinculado'
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Clientes SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Pedidos ADD IdClienteVinculado bigint NULL
GO
ALTER TABLE dbo.Pedidos ADD CONSTRAINT FK_Pedidos_Clientes_Vinculado
    FOREIGN KEY (IdClienteVinculado)
    REFERENCES dbo.Clientes (IdCliente)
    ON UPDATE  NO ACTION ON DELETE  NO ACTION 
GO
ALTER TABLE dbo.Pedidos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
PRINT ''
PRINT '2.- Funcion Campo CategoriasNovedades Color'
/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CRMCategoriasNovedades ADD Color int NULL
GO
ALTER TABLE dbo.CRMCategoriasNovedades SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
