SELECT C1.TABLE_NAME, C1.COLUMN_NAME, C1.DATA_TYPE, C1.IS_NULLABLE, C2.TABLE_NAME, C2.DATA_TYPE, C2.IS_NULLABLE
  FROM (SELECT * FROM INFORMATION_SCHEMA.COLUMNS AS C1
         WHERE C1.TABLE_NAME = N'Clientes') AS C1
 INNER JOIN (SELECT * FROM INFORMATION_SCHEMA.COLUMNS AS C2
              WHERE C2.TABLE_NAME = N'AuditoriaClientes') AS C2 ON C2.COLUMN_NAME = C1.COLUMN_NAME
 WHERE C1.DATA_TYPE <> C2.DATA_TYPE
