--PRIMERO CHEQUEAR SI HAY PROBLEMAS EN LA BASE DE DATOS
dbcc checkdb('siga')

/*
--SI HAY PROBLEMAS SEGUIR CON LOS SIGUIENTES PASOS
--  PASAR A SINGLE_USER
alter database siga SET single_user with rollback immediate 

--  LUEGO DE PASAR A SINGLE_USER, EJECUTAR ESTE COMANDO
dbcc checkdb('siga',REPAIR_ALLOW_DATA_LOSS)

--  SI ESE COMANDO NO PUEDE REPARAR USAR EL SIGUIENTE
--dbcc checkdb('siga',REPAIR_FAST)


/*
--UNA VEZ QUE SE HAYA TERMINADO EL DDCC CHECKDB,
--VOLVER LA BASE A MULTI_USER
alter database siga SET MULTI_USER
*/
*/

/*
--SE NOS DIO OTRO CASO QUE LO ANTES EXPUESTO NO FUNCIONÓ. EN ESTE CASO LO PASAMOS A EMERGENCIA Y REPARAMOS
ALTER DATABASE emergencydemo SET EMERGENCY;
GO
DBCC CHECKDB (emergencydemo, REPAIR_ALLOW_DATA_LOSS) WITH NO_INFOMSGS;
GO
*/
