
USE [master] 
GO 
ALTER DATABASE [SIGA] SET EMERGENCY 
GO 
ALTER DATABASE [SIGA] SET SINGLE_USER 
GO 
DBCC CHECKDB ([SIGA], REPAIR_ALLOW_DATA_LOSS) 
GO 
ALTER DATABASE [SIGA] SET MULTI_USER 
GO 
ALTER DATABASE [SIGA] SET ONLINE 
GO
