
ALTER TABLE [dbo].Productos DROP CONSTRAINT DF__Productos__UHPor__066DDD9B
GO 
ALTER TABLE [dbo].Productos DROP CONSTRAINT DF__Productos__UHPor__076201D4
GO 
ALTER TABLE [dbo].Productos DROP CONSTRAINT DF__Productos__UHPor__0856260D
GO 
ALTER TABLE [dbo].Productos DROP CONSTRAINT DF__Productos__UnidH__039170F0
GO 
ALTER TABLE [dbo].Productos DROP CONSTRAINT DF__Productos__UnidH__04859529
GO 
ALTER TABLE [dbo].Productos DROP CONSTRAINT DF__Productos__UnidH__0579B962
GO 

ALTER TABLE [dbo].Rubros DROP CONSTRAINT DF__Rubros__UHPorc1__00B50445
GO 
ALTER TABLE [dbo].Rubros DROP CONSTRAINT DF__Rubros__UHPorc2__01A9287E
GO 
ALTER TABLE [dbo].Rubros DROP CONSTRAINT DF__Rubros__UHPorc3__029D4CB7
GO 
ALTER TABLE [dbo].Rubros DROP CONSTRAINT DF__Rubros__UnidHast__7DD8979A
GO 
ALTER TABLE [dbo].Rubros DROP CONSTRAINT DF__Rubros__UnidHast__7ECCBBD3
GO 
ALTER TABLE [dbo].Rubros DROP CONSTRAINT DF__Rubros__UnidHast__7FC0E00C
GO 
