DECLARE @FechaAlta DATETIME = GETDATE();

--Renombrado por las dudas.
--DELETE AuditoriaClientes;

INSERT INTO AuditoriaClientes
           (FechaAuditoria
           ,OperacionAuditoria
           ,UsuarioAuditoria
           ,TipoDocumentoAnterior
           ,NroDocumentoAnterior
           ,NombreCliente
           ,Direccion
           ,IdLocalidad
           ,Telefono
           ,FechaNacimiento
           ,NroOperacion
           ,CorreoElectronico
           ,Celular
           ,NombreTrabajo
           ,DireccionTrabajo
           ,IdLocalidadTrabajo
           ,TelefonoTrabajo
           ,CorreoTrabajo
           ,FechaIngresoTrabajo
           ,FechaAlta
           ,SaldoPendiente
           ,IdCategoria
           ,IdCategoriaFiscal
           ,Cuit
           ,Observacion
           ,IdListaPrecios
           ,IdZonaGeografica
           ,Activo
           ,LimiteDeCredito
           ,IdSucursalAsociada
           ,NombreDeFantasia
           ,DescuentoRecargoPorc
           ,IdTipoComprobante
           ,IdFormasPago
           ,Foto
           ,IdTransportista
           ,IngresosBrutos
           ,InscriptoIBStaFe
           ,LocalIB
           ,ConvMultilateralIB
           ,NumeroLote
           ,IdCaja
           ,GeoLocalizacionLat
           ,GeoLocalizacionLng
           ,IdTipoDeExension
           ,AnioExension
           ,NroCertExension
           ,NroCertPropio
           ,IdCliente
           ,CodigoCliente
           ,IdClienteGarante
           ,TipoDocCliente
           ,NroDocCliente
           ,DescuentoRecargoPorc2
           ,IdClienteCtaCte
           ,PaginaWeb
           ,LimiteDiasVtoFactura
           ,ModificarDatos
           ,EsResidente
           ,CorreoAdministrativo
           ,IdEstado
           ,IdCobrador
           ,IdTipoCliente
           ,HoraInicio
           ,HoraFin
           ,HoraInicio2
           ,HoraFin2
           ,HoraSabInicio
           ,HoraSabFin
           ,HoraSabInicio2
           ,HoraSabFin2
           ,HoraDomInicio
           ,HoraDomFin
           ,HoraDomInicio2
           ,HoraDomFin2
           ,HorarioCorrido
           ,HorarioCorridoSab
           ,HorarioCorridoDom
           ,NroVersion
           ,FechaActualizacionWeb
           ,FechaInicio
           ,FechaInicioReal
           ,VencimientoLicencia
           ,BackupAutoCuenta
           ,BackupAutoConfig
           ,TienePreciosConIVA
           ,ConsultaPreciosConIVA
           ,TieneServidorDedicado
           ,MotorBaseDatos
           ,CantidadDePCs
           ,HorasCapacitacionPactadas
           ,HorasCapacitacionRealizadas
           ,FechaActualizacionVersion
           ,UsaArchivoAImprimir2
           ,CBU
           ,IdBanco
           ,IdCuentaBancariaClase
           ,NumeroCuentaBancaria
           ,CuitCtaBancaria
           ,CantidadVisitas
           ,BackupNroVersion
           ,Facebook
           ,Instagram
           ,Twitter
           ,IdAplicacion
           ,Edicion
           ,DireccionAdicional
           ,RecibeNotificaciones
           ,Contacto
           ,FechaBaja
           ,VerEnConsultas
           ,IdCalle
           ,Altura
           ,IdCalle2
           ,Altura2
           ,DireccionAdicional2
           ,TelefonosParticulares
           ,Fax
           ,FechaSUS
           ,HabilitarVisita
           ,Direccion2
           ,IdLocalidad2
           ,ObservacionWeb
           ,RepartoIndependiente
           ,NivelAutorizacion
           ,IdCuentaContable
           ,EsClienteGenerico
           ,URLWebmovilPropio
           ,URLWebmovilAdminPropio
           ,URLSimovilGestionPropio
           ,UtilizaAppSoporte
           ,CantidadLocal
           ,CantidadRemota
           ,CantidadMovil
           ,ObservacionAdministrativa
           ,NroVersionWebmovilPropio
           ,NroVersionWebmovilAdminPropio
           ,NroVersionSimovilGestionPropio
           ,CodigoClienteLetras
           ,SiMovilIdUsuario
           ,SiMovilClave
           ,URLActualizadorPropio
           ,NroVersionActualizadorPropio
           ,Alicuota2deProducto
           ,CertificadoMiPyme
           ,FechaDesdeCertificado
           ,FechaHastaCertificado
           ,IdVendedor
           ,IdDadoAltaPor
           ,Sexo
           ,ValorizacionFacturacionMensual
           ,ValorizacionCoeficienteFacturacion
           ,ValorizacionFacturacion
           ,ValorizacionImporteAdeudado
           ,ValorizacionCoeficienteDeuda
           ,ValorizacionDeuda
           ,ValorizacionProyecto
           ,ValorizacionCliente
           ,ValorizacionEstrellas
           ,PublicarEnWeb)
SELECT @FechaAlta AS xxFechaAuditoria
      ,'A' AS xxOperacionAuditoria
      ,'admin' AS xxUsuarioAuditoria
      ,TipoDocumentoAnterior
      ,NroDocumentoAnterior
      ,NombreCliente
      ,Direccion
      ,IdLocalidad
      ,Telefono
      ,FechaNacimiento
      ,NroOperacion
      ,CorreoElectronico
      ,Celular
      ,NombreTrabajo
      ,DireccionTrabajo
      ,IdLocalidadTrabajo
      ,TelefonoTrabajo
      ,CorreoTrabajo
      ,FechaIngresoTrabajo
      ,FechaAlta
      ,SaldoPendiente
      ,IdCategoria
      ,IdCategoriaFiscal
      ,Cuit
      ,Observacion
      ,IdListaPrecios
      ,IdZonaGeografica
      ,Activo
      ,LimiteDeCredito
      ,IdSucursalAsociada
      ,NombreDeFantasia
      ,DescuentoRecargoPorc
      ,IdTipoComprobante
      ,IdFormasPago
      ,Foto
      ,IdTransportista
      ,IngresosBrutos
      ,InscriptoIBStaFe
      ,LocalIB
      ,ConvMultilateralIB
      ,NumeroLote
      ,IdCaja
      ,GeoLocalizacionLat
      ,GeoLocalizacionLng
      ,IdTipoDeExension
      ,AnioExension
      ,NroCertExension
      ,NroCertPropio
      ,IdCliente
      ,CodigoCliente
      ,IdClienteGarante
      ,TipoDocCliente
      ,NroDocCliente
      ,DescuentoRecargoPorc2
      ,IdClienteCtaCte
      ,PaginaWeb
      ,LimiteDiasVtoFactura
      ,ModificarDatos
      ,EsResidente
      ,CorreoAdministrativo
      ,IdEstado
      ,IdCobrador
      ,IdTipoCliente
      ,HoraInicio
      ,HoraFin
      ,HoraInicio2
      ,HoraFin2
      ,HoraSabInicio
      ,HoraSabFin
      ,HoraSabInicio2
      ,HoraSabFin2
      ,HoraDomInicio
      ,HoraDomFin
      ,HoraDomInicio2
      ,HoraDomFin2
      ,HorarioCorrido
      ,HorarioCorridoSab
      ,HorarioCorridoDom
      ,NroVersion
      ,FechaActualizacionWeb
      ,FechaInicio
      ,FechaInicioReal
      ,VencimientoLicencia
      ,BackupAutoCuenta
      ,BackupAutoConfig
      ,TienePreciosConIVA
      ,ConsultaPreciosConIVA
      ,TieneServidorDedicado
      ,MotorBaseDatos
      ,CantidadDePCs
      ,HorasCapacitacionPactadas
      ,HorasCapacitacionRealizadas
      ,FechaActualizacionVersion
      ,UsaArchivoAImprimir2
      ,CBU
      ,IdBanco
      ,IdCuentaBancariaClase
      ,NumeroCuentaBancaria
      ,CuitCtaBancaria
      ,CantidadVisitas
      ,BackupNroVersion
      ,Facebook
      ,Instagram
      ,Twitter
      ,IdAplicacion
      ,Edicion
      ,DireccionAdicional
      ,RecibeNotificaciones
      ,Contacto
      ,FechaBaja
      ,VerEnConsultas
      ,IdCalle
      ,Altura
      ,IdCalle2
      ,Altura2
      ,DireccionAdicional2
      ,TelefonosParticulares
      ,Fax
      ,FechaSUS
      ,HabilitarVisita
      ,Direccion2
      ,IdLocalidad2
      ,ObservacionWeb
      ,RepartoIndependiente
      ,NivelAutorizacion
      ,IdCuentaContable
      ,EsClienteGenerico
      ,URLWebmovilPropio
      ,URLWebmovilAdminPropio
      ,URLSimovilGestionPropio
      ,UtilizaAppSoporte
      ,CantidadLocal
      ,CantidadRemota
      ,CantidadMovil
      ,ObservacionAdministrativa
      ,NroVersionWebmovilPropio
      ,NroVersionWebmovilAdminPropio
      ,NroVersionSimovilGestionPropio
      ,CodigoClienteLetras
      ,SiMovilIdUsuario
      ,SiMovilClave
      ,URLActualizadorPropio
      ,NroVersionActualizadorPropio
      ,Alicuota2deProducto
      ,CertificadoMiPyme
      ,FechaDesdeCertificado
      ,FechaHastaCertificado
      ,IdVendedor
      ,IdDadoAltaPor
      ,Sexo
      ,ValorizacionFacturacionMensual
      ,ValorizacionCoeficienteFacturacion
      ,ValorizacionFacturacion
      ,ValorizacionImporteAdeudado
      ,ValorizacionCoeficienteDeuda
      ,ValorizacionDeuda
      ,ValorizacionProyecto
      ,ValorizacionCliente
      ,ValorizacionEstrellas
      ,PublicarEnWeb
  FROM Clientes
GO
