
ALTER TABLE Rubros DROP COLUMN UnidHasta1
GO
ALTER TABLE Rubros DROP COLUMN UnidHasta2
GO
ALTER TABLE Rubros DROP COLUMN UnidHasta3
GO
ALTER TABLE Rubros DROP COLUMN UHPorc1
GO
ALTER TABLE Rubros DROP COLUMN UHPorc2
GO
ALTER TABLE Rubros DROP COLUMN UHPorc3
GO

ALTER TABLE Productos DROP COLUMN UnidHasta1
GO
ALTER TABLE Productos DROP COLUMN UnidHasta2
GO
ALTER TABLE Productos DROP COLUMN UnidHasta3
GO
ALTER TABLE Productos DROP COLUMN UHPorc1
GO
ALTER TABLE Productos DROP COLUMN UHPorc2
GO
ALTER TABLE Productos DROP COLUMN UHPorc3
GO

ALTER TABLE AuditoriaProductos DROP COLUMN UnidHasta1
GO
ALTER TABLE AuditoriaProductos DROP COLUMN UnidHasta2
GO
ALTER TABLE AuditoriaProductos DROP COLUMN UnidHasta3
GO
ALTER TABLE AuditoriaProductos DROP COLUMN UHPorc1
GO
ALTER TABLE AuditoriaProductos DROP COLUMN UHPorc2
GO
ALTER TABLE AuditoriaProductos DROP COLUMN UHPorc3
GO
