'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WSPN3
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="select.ContribuyenteNivel3SelectServiceImplSoapBinding", [Namespace]:="https://awshomo.afip.gov.ar/padron-puc-ws/services/select.ContribuyenteNivel3Sele"& _ 
        "ctServiceImpl")>  _
    Partial Public Class ContribuyenteNivel3SelectServiceImplService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private dummyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Eniac.Reglas.My.MySettings.Default.Eniac_Reglas_WSPN3_ContribuyenteNivel3SelectServiceImplService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event dummyCompleted As dummyCompletedEventHandler
        
        '''<remarks/>
        Public Event getCompleted As getCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://select.services.server.ws.impl.puc.padron.afip.gov", ResponseNamespace:="https://awshomo.afip.gov.ar/padron-puc-ws/services/select.ContribuyenteNivel3Sele"& _ 
            "ctServiceImpl")>  _
        Public Function dummy() As <System.Xml.Serialization.SoapElementAttribute("dummyReturn")> String
            Dim results() As Object = Me.Invoke("dummy", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub dummyAsync()
            Me.dummyAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub dummyAsync(ByVal userState As Object)
            If (Me.dummyOperationCompleted Is Nothing) Then
                Me.dummyOperationCompleted = AddressOf Me.OndummyOperationCompleted
            End If
            Me.InvokeAsync("dummy", New Object(-1) {}, Me.dummyOperationCompleted, userState)
        End Sub
        
        Private Sub OndummyOperationCompleted(ByVal arg As Object)
            If (Not (Me.dummyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent dummyCompleted(Me, New dummyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://select.services.server.ws.impl.puc.padron.afip.gov", ResponseNamespace:="https://awshomo.afip.gov.ar/padron-puc-ws/services/select.ContribuyenteNivel3Sele"& _ 
            "ctServiceImpl")>  _
        Public Function [get](ByVal pContribuyentePK As String, ByVal pToken As String, ByVal pSign As String) As <System.Xml.Serialization.SoapElementAttribute("getReturn")> String
            Dim results() As Object = Me.Invoke("get", New Object() {pContribuyentePK, pToken, pSign})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getAsync(ByVal pContribuyentePK As String, ByVal pToken As String, ByVal pSign As String)
            Me.getAsync(pContribuyentePK, pToken, pSign, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getAsync(ByVal pContribuyentePK As String, ByVal pToken As String, ByVal pSign As String, ByVal userState As Object)
            If (Me.getOperationCompleted Is Nothing) Then
                Me.getOperationCompleted = AddressOf Me.OngetOperationCompleted
            End If
            Me.InvokeAsync("get", New Object() {pContribuyentePK, pToken, pSign}, Me.getOperationCompleted, userState)
        End Sub
        
        Private Sub OngetOperationCompleted(ByVal arg As Object)
            If (Not (Me.getCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getCompleted(Me, New getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub dummyCompletedEventHandler(ByVal sender As Object, ByVal e As dummyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class dummyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub getCompletedEventHandler(ByVal sender As Object, ByVal e As getCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
