Partial Class Parametro
   Public Enum Parametros
      TIENEMODULOS
      'Nuevos campos SiSeN categorias
      CargosCalcularPor
      CALIDADUTILIZAMODELOASIGLISTAS
      FORZARLISTADEPRECIOSCLIENTE
      CLIENTEUTILIZACALLE
      CUITEMPRESA
      SUELDOS_DOMICILIO_EMPRESA
      SUELDOS_CONCEPTO_AGUINALDO
      FACTELECTSINCRONICA
      MODULOFACTURACIONELECTRONICA
      MAILSERVIDOR
      MAILDIRECCION
      MAILUSUARIO
      MAILPASSWORD
      MAILPUERTOSALIDA
      URLWSAA
      CLAVETICKETACCESOFE
      URLWSFE
      URLWSFEX
      URLWSBFE
      URLWSPN4
      UBICACIONPDFSFE 'carpeta donde se van a depositar los PDFs generados para Fact. Electrónica
      NOMBREFANTASIA
      INGRESOSBRUTOS
      FECHAINICIOACTIVIDADES
      TAMAÑOMAXIMOIMAGENES
      FACTURACIONSOLICITACOMPROBANTE
      DIRECCIONWEBEMPRESA
      COMPRASSINPRODUCTOS
      CTACAJAMOVCHEQUES 'Define la cuenta para movimientos de Cheques entre Sucursales
      CLIENTETIENESUCURSALASOC
      RECIBOUTILIZADESCUENTORECARGO
      CATEGORIAFISCALEMPRESA
      MODULOCUENTACORRIENTECLIENTES
      MODULOCAJA
      CTACAJAVENTAS
      CTACAJAVENTASACUMULA
      FACTURACIONMANTIENECLIENTE
      FACTURACIONMANTIENECOMPROBANTE
      CTACAJAPAGO
      RETIENEGANANCIAS
      CTABANCOTRANSFBANCARIA
      CTABANCOACREDTARJETA
      CTABANCOPAGO
      MODULOBANCO
      CTACAJATRANSFBANCARIA
      CTACAJALIQUIDACIONTARJETA
      CALCULOCOMISIONVENDEDOR
      BUSQUEDACLIENTEFACTURACION
      VENDEDORCOMPROBANTEINVOCADO
      MODULOCONTABILIDAD
      ACTUALIZACOSTOYPRECIOVENTA 'en compras despues de grabar el comprobante pregunta si actualiza los costos y precios de venta
      COMPRASPRODUCTOLIQUIDACIONTARJETAS
      PRECIOSUNIFICAR
      VENCIMIENTOSISTEMA
      NOMBREEMPRESA
      DIASAVISOVENCIMIENTOSISTEMA
      DIASCONTROLDELICENCIAS
      MODULOFICHAS
      PRODUCTOUTILIZACODIGODEBARRAS
      PRECIOCONIVA
      IMPORTARPRODUCTOSGENERAHISTORIALPRECIOS
      FACTURACIONIGNORARPCDECAJA
      COMPRASIGNORARPCDECAJA
      RECIBOIGNORARPCDECAJA
      PAGOIGNORARPCDECAJA
      FACTURACIONTICKETINCLUYERECARGOGENERAL
      FACTURACIONPRESUPUESTOINCLUYERECARGOGENERAL
      FACTURACIONMUESTRAHISTORIACLINICA
      IDCATEGORIAPACIENTE
      IDCATEGORIADOCTOR
      'COMPRASVALORREDONDEO
      'COMPRASDECIMALESENTOTALES
      'COMPRASDECIMALESENITEMS
      PEDIDOCULTARENTABILIDAD
      PEDIDOSFACTURARAUTOMATICO
      PEDIDOSPROVFACTURARAUTOMATICO
      REQCOMPRAPERMITEFECHAENTREGADISTINTAS
      FACTURACIONINVOCARINVOCADOR
      MODULOCUENTACORRIENTEPROVEEDORES
      CTACAJARECIBOS
      UNIFICALIBROSDEBANCO
      CONTRAMOVIMIENTOENVIORECEPCIONSUCURSAL
      DESCUENTOMAXIMO
      PEDIDOSVISUALIZA
      RETIENEIIBB
      CTACAJADEPOSITOTARJETAS
      CTACAJACOMPRAS
      RECIBOAPLICASALDOENPESOS
      PRODUCTOUTILIZAEMBALAJEARRIBA
      VISUALIZAPAGOAPROVEEDOR
      CTACTEPROVREALIZANCNDDESCREC
      CTACTEPROVIMPUTACIONAUTOMATICADRFORMAPAGO
      FACTURACIONREMITOTRANSPUTILIZALOTE
      'UTILIZABONOSFISCALESELECTRONICOS
      FACTURACIONPERMITECANTIDADNEGATIVA
      FACTURACIONPERMITECANTIDADNEGATIVAACUMULADA
      DESCRIPCIONADICIONALEMPRESA
      FACTURACIONREMITOTRANSPCALCULABULTOS
      PERMITEPAGOSINAPLICARCOMPROBANTES
      CTACTECLIENTESSEPARAR
      PAGOIMPRIMESALDO
      PAGOIMPRIMETOTALIMPORTE
      PAGOIMPRIMETOTALSALDO
      PAGOIMPRIMETOTALDESCREC

      CTACTECLIENTESPRIORIZARNCSYANTICIPOS
      CTACTESALDOLIMITEDECREDITOCONTEMPLAPEDIDOS
      CTACTESALDOLIMITEDECREDITOCONTEMPLAANTICIPOS
      CTACTESALDOLIMITEDECREDITODIASSUMARFECHACOBRO
      CTACTECANTIDADDIASPREMIOCOBRO

      CAJAMOSTRARNCINDIVIDUAL
      CONSULTARPRECIOSCONEMBALAJE
      CTACTEPROVEEDORESSEPARAR
      FACTURACIONAVISAPRODUCTOSENCERO
      FACTURACIONIGNORARULTIMODIGITOCB
      MAILREQUIERESSL
      MAILREQUIEREAUTENTICACION
      MAILCOPIAASIMISMO
      FACTURACIONGRABALIBRONOFUERZACONSFINAL
      PEDIDOSPROVCONPRODUCTOSENCERO
      PEDIDOSESTADOAREMITIR

      TIPOCOMPROBANTEORDENPRODUCCIONPLANIFICACION
      ESTADOORDENPRODUCCIONPLANIFICACION
      TIPOCOMPROBANTEORDENPRODUCCIONREQUERIMIENTO
      ESTADOORDENPRODUCCIONPLANIFICACIONRQ
      ESTADOFINALORDENPRODUCCION

      ESTADOORDENCOMPRAAVINCULAR
      ESTADOORDENCOMPRAVINCULADA

      OPERARIOINFORMATALLERESEXTERNOS

      MODULOSUELDOS
      CTACTECLIENTESEMISIONPOSTERIOR
      CAJAUTILIZASALDOSDIGITADOS
      DEPOSITOMUESTRACLIENTEXTITULAR
      CAJAPLANILLAMUESTRAPRODUCTOSCONALERTA
      CAJAPLANILLAMUESTRAVENTASENCTACTE
      PRODUCCIONRECETAUNICA
      PRODUCTOUTILIZANOMBRECORTO
      PRODUCTOUTILIZACODIGOLARGO
      PRODUCCIONDESCUENTAPRODFORMULAFACTURAR
      PRODUCCIONDECIMALESVARIABLESMODELOFORMA
      PRODUCCIONDIVIDETAMANO
      CANTIDADCARACTERESPRODUCTOOBSERVACION
      FACTURACIONCANTIDADCARACTERESOBSERVACIONES
      FACTURACIONDECIMALESREDONDEOENPRECIO
      FACTURACIONDECIMALESENPRECIO
      FACTURACIONDECIMALESENTOTALXPRODUCTO
      VisualizarComprobanteVentaAsumeImpresion
      IMPRESIONMASIVAORDENINVERSO
      CtaCteProveedoresEmisionPosterior
      CtaCteClientesCalcularPromedios
      ENVIAMAILCLIENTECOMPELECTRONICO
      ModuloExpensas
      EXPENSASPASAJECOMPRASINCLUYEIMPUESTOS
      FACTELECTSOURCE
      FACTELECTDESTINATION
      FACTELECUNIQUEID
      FACTELECSERVICE
      FACTELECTGENERATIONTIME
      FACTELECTEXPIRATIONTIME
      CAJAPERMITIRMOVSINSALDO
      CAJAPLANILLAFECHADIA
      PLANILLACAJAPREDPORPC

      CAJAIMPORTESNEGATIVOSTOTAL
      CAJAIMPORTESNEGATIVOSPESOS
      CAJAIMPORTESNEGATIVOSTICKETS
      CAJAIMPORTESNEGATIVOSBANCOS
      CAJAIMPORTESNEGATIVOSDOLARES

      IMPRIMIRLUEGODESOLICITARCAE
      PreciosDecimalesEnVenta
      FACTURACIONTAMANOFUENTEDETALLE
      FACTURACIONSALDOCONTEMPLAHORA
      FACTURACIONMUESTRASALDOCTACTEIMPRESION
      FACTURACIONMUESTRASALDOCTACTEIMPRESIONUNIFICADO
      FACTURACIONMARGENDERECHO
      FACTURACIONMARGENIZQUIERDO
      FACTURACIONCLIENTECONTROLADNICF
      FACTURACIONCONTROLATOPECF
      FACTURACIONIMPRIMETICKETNOFISCAL
      MOSTRARNOMBREFANTASIAENCOMPROBANTES
      FACTURACIONPERMITEMODIFICARCLIENTE
      FACTURACIONDIASINVOCACIONCOMPROBANTES
      FACTURACIONDECIMALESREDONDEOENCANTIDAD
      FACTURACIONDECIMALESMOSTRARENCANTIDAD
      COMPRASPERMITEFECHAMAYORHOY
      FACTURACIONPOSICIONNOMBREPRODUCTO


      FACTURACIONMODIFICADESCRECGRALPORC
      FACTURACIONMODIFICADESCRECPRODUCTOPORMONTO
      FACTURACIONPERMITECOBROTARJETAAUTOMATICO
      FACTURACIONTARJETAAUTOMATICO
      FACTURACIONBANCOTARJETAAUTOMATICO
      FACTURACIONRAPIDAMODIFICADESCRECGRALPORC

      FACTURACIONMOSTRARPRECIOCONIVA
      FACTURACIONMOSTRARPRECIOUNITARIO
      FACTURACIONMOSTRARDESC1
      FACTURACIONMOSTRARDESC2
      FACTURACIONMOSTRARKILOS
      FACTURACIONMOSTRARSTOCK

      FACTURACIONRAPIDAMOSTRARDESC1
      FACTURACIONRAPIDAMOSTRARDESC2
      FACTURACIONRAPIDAMOSTRARPRUNITARIO
      FACTURACIONRAPIDAMOSTRARLISTAPRECIO

      CONTROLAEVENTOSDELIMITEDECREDITODECLIENTES
      PEDIDOSCONTROLAEVENTOSDELIMITEDECREDITODECLIENTES

      CAJEROABRIRVARIASVENTANASDEFACTURACION
      CAJEROPERMITEACTUALIZACIONAUTOMATICA
      CAJEROTIEMPODEACTUALIZACIONAUTOMATICA

      CONTABILIDADEJECUTARENLINEA
      CONTABILIDADCUENTAVENTAS
      CONTABILIDADCUENTACOMPRAS
      'CONTABILIDADCUENTAIVA
      RECIBOMUESTRASALDOCTACTEIMPRESION

      INTERESESADICIONALPROPORCIONALDIARIO
      FACTURACIONMUESTRAVENDEDORIMPRESION

      FACTURACIONPRODUCTOMODIFDESCRIPCARGAPRECIOACTUAL

      INTERESESCALCULOCOMPLETOPRIMERPAGO

      INTERESESMONTOAPLICADOINCLUYEINTERESES
      PRODUCTOCODIGONUMERICO
      HABILITACODIGOPRODUCTONUMERICO

      REEMPLAZARCOMPROBANTETIPOCOMPROBANTEORIGEN

      REEMPLAZARCOMPROBANTETIPOCOMPROBANTEDESTINO

      CONTABILIDADCUENTAREDONDEO

      CONTABILIDADREDONDEOIMPORTEMAXIMO
      CONTABILIDADCERRARPERIODOCONASIENTOPERMITIR

      PRODUCTOCODIGOBARRAPRECIORESPETAETIQUETA

      NOMBREBASEARBA

      NOMBREBASEADJUNTOSCRM

      MODULOLOGISTICA

      CONTABILIDADFORMATOEXPORTACION

      PEDIDOSSOLICITATRANSPORTISTA

      PEDIDOSSOLICITACOMPROBANTEGENERAR

      PEDIDOSPERMITEMODIFICARCLIENTE

      FACTURARPEDIDOSELECCIONADO

      VALIDAEMISORELECTRONICOENRECIBOS

      PREFACTURACONSUMEPEDIDOS

      CONTABILIDADCUENTASECUNDARIAPRODUCTO

      FACTURACIONINFORMEVENTASSI

      CONTABILIDADCUENTASECUNDARIACATEGORIA

      RECIBOPERMITEMODIFICARIMPORTEINTERESES

      FACTURACIONTIPOCOMPROBANTEENVIADOCAJERO

      NDEBCHEQRECHCOM

      FACTURACIONITEMSDETALLACHEQUESYTARJETAS

      FACTURACIONUTILIZAINTERESESTARJETAS

      FACTURACIONTIPOCOMPROBANTEGENERADOCAJERO

      CARGOSEXPENSASFORMAPAGO

      CARGOSEXPENSASTIPOCOMPROBANTE

      CARGOSEXPENSASFECHAFACTURA

      CARGOSEXPENSASPERIODOFACTURA

      CARGOSPERMITEGENERARLIQUIDACIONSINCLIENTES

      RECIBOMONTOMINIMOINTERESPERMITO

      CARGOSGENERARCOMPROBANTEPORITEM

      '-- REG-32379/32381.- ----------------
      FACTURACIONVISUALIZAPRECIOCOSTO
      FACTURACIONRAPIDAVISUALIZAPRECIOCOSTO
      '-------------------------------------
      '-- REQ-32944.- ----------------------
      DASHBOARDTIMERBASE
      DASHBOARDMMGRIDS
      '-------------------------------------
      FACTURACIONENVIOMAILCOPIAOCULTA

      FACTURACIONASUNTOENVIOMASIVOEMAIL

      FACTURACIONCARGARECIBOLUEGONC

      FACTURACIONMONEDAPORDEFECTO

      CARGOSPASAJEMOVIMIENTOTOMACOMPROBANTECOMPLETO

      CARGOSUTILIZADESCUENTOSRECARGOS

      URLACTUALIZADOR
      UBICACIONMSI

      CODIGOCLIENTESINERGIA

      CLAVECLIENTESINERGIA

      IDAPLICACION

      MODULOCARGOS

      FACTURACIONINVOCADOSMANTIENEVENDEDOR

      CTACTEPROVEEDORESDHVISTACONTABLE

      PEDIDOSPERMITEFECHAENTREGADISTINTAS
      PEDIDOSMONEDAPORDEFECTO

      VISUALIZASTOCKRESERVADO
      VISUALIZASTOCKDEFECTUOSO
      VISUALIZASTOCKFUTURO
      VISUALIZASTOCKFUTURORESERVADO
      INFDESTOCKMOSTRARPRECIOPREDETERMINADO

      PERMITEABRIRMULTIPLESNOVEDADESNUEVAS
      PERMITEABRIRMULTIPLESNOVEDADESEDITAR

      CANTIDADPADRONESARBA

      FTPSERVIDOR

      FTPUSUARIO

      FTPPASSWORD

      FTPCONEXIONPASIVA

      FTPNOMBREARCHIVO

      FTPFORMATO

      MaximoTamanioFoto  'Req: 34079 - S.C.

      '# Ubicación FTP Movil
      FTPSERVIDORMOVIL
      FTPUSUARIOMOVIL
      FTPPASSWORDMOVIL
      FTPCONEXIONPASIVAMOVIL
      FTPCARPETAREMOTAMOVIL

      FACTURACIONSOLICITANUMERODECOMPROBANTE

      FACTURACIONSOLICITAFORMADEPAGO

      FACTURACIONSOLICITALISTADEPRECIOS

      FACTURACIONCTACTESOLICITADIAFIJO
      '-- REQ-36082.- ----------------
      FACTURACIONUTILIZACANJE
      '-- REQ-38566.- ----------------
      FACTURACIONCANTIDADDEFECTO
      '-------------------------------

      SALDOTOMAACTUALALIMPRIMIR

      COMPRASDECIMALESREDONDEOENPRECIO
      COMPRASDECIMALESENPRECIO
      COMPRASDECIMALESENTOTALXPRODUCTO
      COMPRASDECIMALESREDONDEOENCANTIDAD
      COMPRASDECIMALESMOSTRARENCANTIDAD
      COMPRASDECIMALESENTOTALGENERAL

      FACTURACIONDESCUENTOIMPINTIGUALADO

      AFIPHABILITAVENTASPERIODOAUTOMATICAMENTE
      AFIPUTILIZACM05

      CONFIGURACIONMAIL
      CONFIGURACIONMAILCRM

      SOLICITARCAESELECCIONARTODOS

      VEROBSERVACIONES

      RMACANTIDADMESESHISTORICO
      CRMNOVEDADESOBSERVACIONFACTURABLE
      CRMNOVEDADESPRODUCTOFACTURABLE
      CRMNOVEDADESDIASAVENCERALARMA
      CRMSOLOMUESTRAUSUARIOSACTIVOS
      CRMMOVIMIENTOCONSUMO
      CRMMOVIMIENTOREVERSADO

      CRMMOVIMIENTORESERVA
      CRMMOVIMIENTODEVRESERVA

      CRMNOVEDADESLISTAPRECIOFACTURAR

      CRMNOVEDADESDEPOSITORESERVA
      CRMNOVEDADESUBICACIONRESERVA

      SERVICEIMPRIMEUNACOPIANR

      RMAPRODUCTOSCONSUMIDOSNOFACTURA

      CRMPERMITEENVIOMAILS

      PEDIDOSESTADOFACTURADO

      CTABANCODEPOSITO

      CTABANCOEXTRACCION

      CTABANCOLIQUIDACIONTARJETA

      CTACAJADEPOSITO

      CTACAJAEXTRACCION

      PEDIDOSUTILIZAORDENCOMPRA

      FACTURACIONDECIMALESENDESCREC

      FACTURACIONVENDEDORENTITULO

      LOTESOLICITAFECHAVENCIMIENTO

      LOTESOLICITADESPACHOIMPORTACION

      UTILIZACENTROCOSTOS

      FACTURACIONSOLICITAVENDEDORALABRIR

      PERMITECAMBIARCENTROCOSTOSCOMPRAS

      '-- REG-32597.- --
      FACTURACIONCONSERVAORDENPRODUCTO
      '-- REG-32661.- --
      FACTURACIONRAPIDACONSERVAORDENPRODUCTO

      PERMITECAMBIARCENTROCOSTOSVENTAS

      PERMITECAMBIARCENTROCOSTOSCAJA

      PERMITECAMBIARCENTROCOSTOSBANCO

      FACTURACIONMANTIENEELCLIENTEDEFAULT

      TIPOIMPRESIONFISCAL

      PERMITECONSULTARMULTIPLESUCURSAL

      CONSULTARMULTIPLESUCURSAL

      FACTURACIONDESCUENTOSAGRUPACANTIDADESPORRUBRO

      CONVERTIRPEDIDOENFACTURACONSERVAPRECIOSPEDIDO

      PEDIDOGENERAORDENPRODUCCIONPORPRODUCTO

      ACTUALIZARPRECIOSMARCARTODOS

      GENERARPEDIDOSSTOCKSELECCIONATRUE

      GENERAPEDIDOPROVEEDORDESDESTOCKMODIFICAPRECIOCOSTO

      LISTAPRECIOSPREDETERMINADA
      FACTURACIONCAJEROGENERA

      FACTURACIONCAJEROSELECCIONMULTIPLE
      IMPRESIONMUESTRATOTALKILOS

      IMPRESIONMUESTRATOTALPRODUCTOS

      FACTURACIONMODIFICADESCRIPSOLICITAPRECIO

      SOLICITARCAECANTIDADDIASFILTROFECHA

      RECIBOCOMPARTENUMERACIONENTRESUCURSALES
      '-- REQ-31947.- ------------------------
      RECIBOCALCULOINTERESESFUTURO
      '---------------------------------------
      ORDENARCOBRANZAPOR

      CIERREPLANILLACAJAMODO
      CIERREPLANILLACAJAIDSUCURSALDESTINO
      CIERREPLANILLACAJAIDCAJADESTINO

      CTACTECLIENTEPINTACUOTA
      '-- REQ-33202.- ----------------------
      FACTURACIONAGRUPACANTIDADESPRODUCTOS
      '-------------------------------------
      FACTURARSINSTOCKCONTROLANOAFECTASTOCK

      PEDIDOSMOSTRARTAMANO
      PEDIDOSMOSTRARUM
      PEDIDOSMOSTRARCOSTO
      PEDIDOSMOSTRARPRECIOVENTAPORTAMANO
      PEDIDOSMOSTRARMONEDA
      FACTURACIONSEMAFOROCALCULOMUESTRA
      PEDIDOSMOSTRARSEMAFORORENTABILIDADDETALLE
      PEDIDOSMOSTRARCRITICIDAD
      PEDIDOSPERMITEMODIFICARDESCREC
      PEDIDOSMUESTRAPROVHABITUAL

      PEDIDOSMOSTRARPRODUCTOESPMM
      PEDIDOSMOSTRARPRODUCTOESPPULGADAS
      PEDIDOSMOSTRARPRODUCTOSAE
      PEDIDOSMOSTRARPRODUCTOPRODUCCIONPROCESO
      PEDIDOSMOSTRARPRODUCTOPRODUCCIONFORMA
      PEDIDOSMOSTRARPRODUCTOLARGOEXTALTO
      PEDIDOSMOSTRARPRODUCTOANCHOINTBASE

      PEDIDOSMOSTRARPRODUCTOARCHITRAVE
      PEDIDOSMOSTRARPRODUCTOMODELOFORMA

      ORDPRODMOSTRARPRODUCTOMODELOFORMA


      PEDIDOSMONEDAPRECIOVENTAPORTAMANO
      PEDIDOSMOSTRARPRECIOSENDOLARES
      FACTURACIONMOSTRARPRECIOSENDOLARES

      FACTURACIONDECIMALESREDONDEOENTAMANO
      FACTURACIONDECIMALESMOSTRARENTAMANO
      PEDIDOSPERMITEMODIFICARCAMBIO
      PEDIDOSGENPEDPROVOCOBLIGATORIA
      ACTUALIZAPRECIOCOSTOPORTIPOCAMBIO

      VENTASIMPRESIONVISNROSERIE

      CLAVELOTEDESPACHOIMPORTACION

      ACTUALIZARPRECIOSMOSTRARCODIGOPRODUCTOPROVEEDOR

      PEDIDOSURLWEBPOST

      PEDIDOSWEBFORMATO

      ESTADOPEDIDOPENDIENTEWEBPOST

      ESTADOPEDIDOENVIADOWEBPOST

      PEDIDOSURLWEBGET

      PEDIDOSURLWEBPUT

      PEDIDOSMOSTRARURLPLANODETALLE

      PEDIDOTALKIUTOKEN

      PEDIDOTALKIUGET

      FACTURACIONDESCUENTORECARGO2CARGAMANUAL

      FACTURACIONINVOCADOSRELACIONACABECERA

      PEDIDOSPROVIMPRESIONMUESTRACODIGOPROV

      FACTURACIONPEDIDOSINVOCADOSMANTIENEFORMAPAGO

      FACTURACIONINVOCADOSMANTIENEFORMAPAGO

      ESTADOPRESUPUESTOALANULARPEDIDO

      COMPRASPEDIDOSPROVINVOCADOSMANTIENEFORMAPAGO

      WEBARCHIVOSCLIENTESURLDELETE

      WEBARCHIVOSCLIENTESURLPOST

      WEBARCHIVOSCLIENTESURLGET

      WEBARCHIVOSCLIENTESTAMANOPAGINAPOST

      WEBARCHIVOSPRODUCTOSURLDELETE

      WEBARCHIVOSPRODUCTOSURLGET

      WEBARCHIVOSPRODUCTOSURLPOST

      WEBARCHIVOSPRODUCTOSTAMANOPAGINAPOST

      WEBARCHIVOSPRODSUCURURLDELETE

      WEBARCHIVOSPRODSUCURURLGET

      WEBARCHIVOSPRODSUCURURLPOST

      WEBARCHIVOSPRODSUCURTAMANOPAGINAPOST

      WEBARCHIVOSPRODSUCURPRECIOSURLDELETE

      WEBARCHIVOSPRODSUCURPRECIOSURLGET

      WEBARCHIVOSPRODSUCURPRECIOSURLPOST

      WEBARCHIVOSPRODSUCURPRECIOSTAMANOPAGINAPOST

      WEBARCHIVOSCLIENTESURLGETCOUNT

      WEBARCHIVOSCLIENTESTAMANOPAGINAGET

      WEBARCHIVOSPRODUCTOSURLGETCOUNT

      WEBARCHIVOSPRODUCTOSTAMANOPAGINAGET

      WEBARCHIVOSPRODSUCURURLGETCOUNT

      WEBARCHIVOSPRODSUCURTAMANOPAGINAGET

      WEBARCHIVOSPRODSUCURPRECIOSTAMANOPAGINAGET

      WEBARCHIVOSPRODSUCURPRECIOSURLGETCOUNT

      PEDIDOSMOSTRARFORMULA

      ACTUALIZARPRECIOSEXCEL

      ORDPRODMOSTRARCOSTO
      ORDPRODMOSTRARVENTA

      ORDPRODMOSTRARFORMULA

      ORDPRODMOSTRARPRODUCTOLARGOEXTALTO

      ORDPRODMOSTRARPRODUCTOANCHOINTBASE
      ORDPRODMOSTRARPRODUCTOARCHITRAVE
      ORDPRODIMPRIMIRCOMPONENTESNECESARIOS
      ORDPRODCANTIDADNECESARIAUNITARIA
      ORDPRODCANTIDADLINEASEPARACION

      PRODUCCIONCALCULARPORCENTAJEFORMULA

      NOMBREBASEPRODUCTOWEB

      CRMMUESTRASOLAPAMASINFO

      PRODUCTOPERMITEESCAMBIABLE

      PRODUCTOPERMITEESBONIFICABLE

      PRODUCTOPERMITEESDEVUELTO

      PEDIDOSMOSTRARNOTA
      PEDIDOSMOSTRARPRECIOMASIVA

      FTPCARPETASECUNDARIA

      FTPCARPETAREMOTA

      FTPSUBEINFOALSERVIDOR2
      FTPPASSWORD2
      FTPSERVIDOR2
      FTPUSUARIO2
      FTPCARPETAREMOTA2
      FTPCONEXIONPASIVA2

      WEBARCHIVOSCLIENTESURLGETMAXFECHA
      WEBARCHIVOSPRODUCTOSURLGETMAXFECHA
      WEBARCHIVOSPRODSUCURURLGETMAXFECHA
      WEBARCHIVOSPRODSUCURPRECIOSURLGETMAXFECHA

      WEBARCHIVOSLOCALIDADESURLDELETE
      WEBARCHIVOSLOCALIDADESURLGET
      WEBARCHIVOSLOCALIDADESURLGETCOUNT
      WEBARCHIVOSLOCALIDADESURLGETMAXFECHA
      WEBARCHIVOSLOCALIDADESURLPOST
      WEBARCHIVOSLOCALIDADESTAMANOPAGINAPOST
      WEBARCHIVOSLOCALIDADESTAMANOPAGINAGET

      WEBARCHIVOSRUBROSURLDELETE
      WEBARCHIVOSRUBROSURLGET
      WEBARCHIVOSRUBROSURLGETCOUNT
      WEBARCHIVOSRUBROSURLGETMAXFECHA
      WEBARCHIVOSRUBROSURLPOST
      WEBARCHIVOSRUBROSTAMANOPAGINAPOST
      WEBARCHIVOSRUBROSTAMANOPAGINAGET

      WEBARCHIVOSSUBRUBROSURLDELETE
      WEBARCHIVOSSUBRUBROSURLGET
      WEBARCHIVOSSUBRUBROSURLGETCOUNT
      WEBARCHIVOSSUBRUBROSURLGETMAXFECHA
      WEBARCHIVOSSUBRUBROSURLPOST
      WEBARCHIVOSSUBRUBROSTAMANOPAGINAPOST
      WEBARCHIVOSSUBRUBROSTAMANOPAGINAGET

      WEBARCHIVOSSUBSUBRUBROSURLDELETE
      WEBARCHIVOSSUBSUBRUBROSURLGET
      WEBARCHIVOSSUBSUBRUBROSURLGETCOUNT
      WEBARCHIVOSSUBSUBRUBROSURLGETMAXFECHA
      WEBARCHIVOSSUBSUBRUBROSURLPOST
      WEBARCHIVOSSUBSUBRUBROSTAMANOPAGINAPOST
      WEBARCHIVOSSUBSUBRUBROSTAMANOPAGINAGET

      WEBARCHIVOSMARCASURLDELETE
      WEBARCHIVOSMARCASURLGET
      WEBARCHIVOSMARCASURLGETCOUNT
      WEBARCHIVOSMARCASURLGETMAXFECHA
      WEBARCHIVOSMARCASURLPOST
      WEBARCHIVOSMARCASTAMANOPAGINAPOST
      WEBARCHIVOSMARCASTAMANOPAGINAGET
      WEBARCHIVOSMARCASULTIMADESCARGA

      WEBARCHIVOSRUBROSCOMPRASURLDELETE
      WEBARCHIVOSRUBROSCOMPRASURLGET
      WEBARCHIVOSRUBROSCOMPRASURLGETCOUNT
      WEBARCHIVOSRUBROSCOMPRASURLGETMAXFECHA
      WEBARCHIVOSRUBROSCOMPRASURLPOST
      WEBARCHIVOSRUBROSCOMPRASTAMANOPAGINAPOST
      WEBARCHIVOSRUBROSCOMPRASTAMANOPAGINAGET
      WEBARCHIVOSRUBROSCOMPRASULTIMADESCARGA

      WEBARCHIVOSPROVEEDORESURLDELETE
      WEBARCHIVOSPROVEEDORESURLGET
      WEBARCHIVOSPROVEEDORESURLGETCOUNT
      WEBARCHIVOSPROVEEDORESURLGETMAXFECHA
      WEBARCHIVOSPROVEEDORESURLPOST
      WEBARCHIVOSPROVEEDORESTAMANOPAGINAPOST
      WEBARCHIVOSPROVEEDORESTAMANOPAGINAGET
      WEBARCHIVOSPROVEEDORESULTIMADESCARGA

      FACTURACIONSOLICITACAJAALABRIR
      FACTURACIONCAJAENTITULO
      FACTURACIONORDENDETITULO
      FACTURACIONORDENDECOLOR

      ACTUALIZAPRECIOSUTILIZAAJUSTEA

      FACTURACIONRAPIDAMUESTRACOMPROBANTE
      FACTURACIONRAPIDASOLICITAVENDEDORPORDEFECTO
      FACTURACIONRAPIDASOLICITATIPOCOMPROBANTEPORDEFECTO
      VALORPORDEFECTOENRESUMENDEVENTAS

      CANTIDADLINEASDEPRODUCTOAEVALUARPARADESCRECARGO
      PORCENTAJEDEDESCRECARGOPORLINEADEPRODUCTO

      CODIGOPRODUCTODRINVOCACIONMASIVA
      PORCENTAJEDRINVOCACIONMASIVA

      VENTASIMPRESIONMUESTRALOTEOBSERVACION

      '-- REQ-34813.- -------------------------
      VENTASIMPRESIONMUESTRAVALIDEZPRESUPUESTO
      '-- REQ-35923.- -------------------------
      VENTASIMPRESIONMUESTRAHORAVENTA
      '----------------------------------------
      '-- REQ-39925.- -------------------------
      VENTASIMPRESIONIMPRIMECOMPONENTES
      VENTASIMPRESIONIMPRIMECANTCOMPONENTES
      VENTASIMPRESIONIMPRIMECANTLINEASSEPARACION

      '----------------------------------------
      EXPORTARVENTASCONFORMATO

      GRABALIBRONOINCLUYERECARGOGENERAL

      WEBARCHIVOSCLIENTESULTIMADESCARGA

      WEBARCHIVOSPRODUCTOSULTIMADESCARGA

      WEBARCHIVOSPRODSUCURULTIMADESCARGA

      WEBARCHIVOSPRODSUCURPRECIOSULTIMADESCARGA

      WEBARCHIVOSLOCALIDADESULTIMADESCARGA

      WEBARCHIVOSRUBROSULTIMADESCARGA

      WEBARCHIVOSSUBRUBROSULTIMADESCARGA

      WEBARCHIVOSSUBSUBRUBROSULTIMADESCARGA

      RECIBOCONCILIAAUTOMATICAMENTETRANSFERENCIAS

      PAGOPROVCONCILIAAUTOMATICAMENTETRANSFERENCIAS

      MACROADHERENTEALINEACION
      MACROADHERENTERELLENADO

      UTILIZASTOCKRESERVADO

      UTILIZASTOCKDEFECTUOSO

      UTILIZASTOCKFUTURO

      UTILIZASTOCKFUTURORESERVADO

      ESTADOPEDIDOPREVINCULACION
      ESTADOPEDIDOPOSTVINCULACION
      ESTADOPEDIDOPROVPREVINCULACION
      ESTADOPEDIDOPROVPOSTVINCULACION

      FACTURACIONRAPIDARECALCULAREFECTIVOALCARGARTARJETA

      NOMBREBASEADJUNTOS

      UBICACIONARCHIVOSPDA

      FORMATONOMBREARCHIVOEXPORTACION

      FICHASACTUALIZAPRECIOSDEVENTA

      FICHASPERMITECAMBIARFORMADEPAGO

      FACTURACIONRAPIDASOLICITACANTIDAD

      SIMOVILCOBRANZAURLBASE
      SIMOVILGESTIONURLBASE

      CONCESIONARIOURLBASE

      IMPORTARPEDIDOSFORMATOARCHIVO

      IMPORTARPEDIDOSTIPOCOMPROBANTE

      COPIAPRESUPUESTOACTUALIZAPRECIO

      FACTURACIONIMULAPERCEPCIONNGLIBRO

      DIASENTREGAIMPORTACION

      COMPRASTOLERANCIAIVAMANUAL

      SIMOVILCOBRANZATIPODIRECCION
      SIMOVILCOBRANZASUCURSALES

      SIMOVILCOBRANZANOMBRECLIENTE

      CLIENTESCANTIDADVISITASPORDEFECTO
      CLIENTESZONAGEOGRAFICAPORDEFECTO
      CLIENTESVENDEDORPORDEFECTO
      CLIENTESCOBRADORPORDEFECTO
      CLIENTESLISTADEPRECIOSPORDEFECTO
      CLIENTESCATEGORIAPORDEFECTO
      CLIENTESTIPOPORDEFECTO
      CLIENTESCATEGORIAFISCALPORDEFECTO

      SIMOVILCOBRANZAINCLUIRCLIENTES

      PEDIDOPROVEEDORESTADONUEVO

      PEDIDOSPROVMUESTRAPROVHABITUAL

      PEDIDOPROVEEDORESTADOANULADO

      PRODUCTOTIENESUBRUBRO
      PRODUCTOTIENESUBSUBRUBRO

      FACTURACIONINVOCARPEDIDOSDEOTRASSUCURSALES

      EMPRESACURRENTUICULTURE

      EXPORTARPRECIOPRODUCTOUSANDOMONEDA

      COMPRASPOSICIONARNOMBREPRODUCTO

      TURNOSTIPOBASE

      TURNOSESTADOBASE

      TURNOSTIPOCAMBIO

      CLIENTEBUSCARPORCODIGOYNRODOCUMENTO

      CLIENTEMOSTRARPRODUCTOSASOCIADOS

      FACTURACIONPERMITEFACTURARENOTRASMONEDAS

      AFIPURLCODIGOQR
      AFIPURLCONTROLARCOMPROBANTE

      ACTUALIZARPRECIOSCALCULO

      ACTUALIZARPRECIOSCALCULODESDECOMPRAS

      REEMPLAZARCOMPROBANTEREAPLICARECIBOS

      FICHASPREGUNTAREEMPLAZARCOMPROBANTE

      PREVENTAIMPRIMIRPEDIDOS

      WEBARCHIVOSPRODUCTOSPUBLICARENWEB

      WEBARCHIVOSPRODUCTOSINCLUIRIMAGENES

      MODULOCONTRATISTAS

      MODULOCONTROLDELICENCIAS

      DEBITOAUTOMATICOSANTANDERCODIGOSERVICIO

      DEBITOAUTOMATICOCUENTABANCARIATRANSBANC

      DEBITOAUTOMATICOCAJACUENTABANCARIATRANSBANC


      DEBITOAUTOMATICOTIPORECIBOCTABANCARIATRANF

      DEBITOAUTOMATICOCOBRADORCTABANCARIATRANF

      CONSCCBLUEOCULTANOMFANTASIA

      PRODUCTOFORMATOLIKEBUSCARPORCODIGO

      SOLICITAMODIFICARFORMULALUEGODELPRODUCTO

      EXPORTARPRECIOSCONIVA
      EXPORTARPRECIOSCONIVA1
      CLIENTESSUBIRALAWEB

      PRODUCTOSSUBIRALAWEB

      RUBROSSUBIRALAWEB

      MARCASSUBIRALAWEB

      LOCALIDADESSUBIRALAWEB

      PROVEEDORESSUBIRALAWEB

      RUBROSCOMPRASSUBIRALAWEB

      CLIENTESBAJARDELAWEB

      PRODUCTOSBAJARDELAWEB

      RUBROSBAJARDELAWEB

      MARCASBAJARDELAWEB

      LOCALIDADESBAJARDELAWEB

      PROVEEDORESBAJARDELAWEB

      RUBROSCOMPRASBAJARDELAWEB

      CRMMUESTRAREPORTACATEGORIASNOVEDADES

      CRMIMPORTECONIVA

      FACTURACIONCOEFNEGATIVORECUPERAPRECIOULTIMAVENTA

      CRMASUNTOENVIOMASIVONOVEDADESEMAIL

      FICHASIMPRIMECOBROSFORMATORECIBO

      PRODUCTOUTILIZAPRODUCTOWEB

      CRMENVIOMAILCOPIAOCULTA

      PRECIOSPRIORIZACODIGOYDESCRIPCION

      MINUTOSTABLEROCOMANDO

      TURNOSPERMITEFACTURARDESDECALENDARIO

      TURNOSPRODUCTOZONA

      EXPORTARPRODUCTOSDECIMALESREDONDEOENPRECIO

      EXPENSASPERMITECONSINCONCEPTO

      'SIMOVILSUBIDAINCLUIRCLIENTES
      'SIMOVILSUBIDAINCLUIRRUTAS
      SIMOVILSUBIDAINCLUIRCUENTASCORRIENTES
      SIMOVILSUBIDAINCLUIRRUBROS
      SIMOVILSUBIDAINCLUIRPRODUCTOS
      SIMOVILSUBIDAINCLUIRPRODUCTOSPRECIOS
      SIMOVILSUBIDAINCLUIRPRODUCTOSCLIENTES

      SIMOVILPRECIOSCONIVA
      SIMOVILSOLOPRODUCTOSCONSTOCK
      '-- REQ-44258.- ----------------------------------
      SIMOVILPRECIOPOREMBALAJE
      '
      SIMOVILSUBIDAMESESENVIARCUENTASCORRIENTESDEBEHABER

      ACTUALIZARPRECIOSDESDECOMPRASPRIORIZAIVAPRODUCTO
      '-- REQ-32596.- --
      COMPRASCONSERVAORDENPRODUCTOS
      '-- REQ-32598.- --
      PEDIDOSCLIENTESCONSERVAORDENPRODUCTOS
      '-- REQ-34676.- --
      PEDIDOSCLIENTESVALIDAREMITOFACTURAPROVEEDOR
      '-- REQ-32598.- --
      PEDIDOSPROVEEDORESCONSERVAORDENPRODUCTOS

      PEDIDOSMODIFICADESCRIPSOLICITAKILOS

      PEDIDOSPRESUPUESTOSAGRUPAPRODUCTOS

      PEDIDOSMODIFICAPRECIOPRODUCTO

      PEDIDOSDECIMALESMOSTRARLARGOANCHO

      PRODUCTOFORMATOLIKEBUSCARPORNOMBRE

      MODALIDADCOEFICIENTECOBRANZAS

      CRMASUNTOGENERARVERSION

      CRMGENERARVERSIONPARA

      CRMGENERARVERSIONCOPIAOCULTA

      ORIGENCOTIZACIONMONEDA

      'VENTANA APLICACIÓN MOVIL
      CORREOMOVIL1
      CORREOMOVIL2
      CORREOMOVIL3
      BUSQUEDACLIENTES
      ORDENARPRODUCTOS
      SOLICITACIERREPEDIDOS
      USARFECHAEXPORTACION
      OCULTARCOMPARTIRVENTASPORMAIL
      ENVIAMAILCLIENTE
      ENVIAMAILEMPRESA
      OCULTARRESUMENPROMEDIO

      SIMOVILSUBIDAINCLUIRCONFIGURACIONES

      FACTURACIONPERMITECAMBIARCLIENTEVINCULADO

      PRODUCTOBUSQUEDACOMBINACODIGONOMBRE

      BUSCAPRODUCTOPORCODIGOPROVEEDORHABITUAL

      PRODUCTOBUSCARPORCODIGOEXACTO

      EDITAPRODUCTONORMALMODIFICAHISTORIAL

      MONEDAPARACONSULTARPRECIOS

      CONSULTAPRECIOSCLIENTEMONEDA
      CONSULTAPRECIOSCLIENTEUSAPREDETERMINADO
      CONSULTAPRECIOSCLIENTEUSACODIGOCLIENTE

      FACTURACIONSOLICITAVENDEDORPORCLAVE

      FACTURACIONTARJETASVALIDACUPONLOTE

      URLTELEPROM
      FACTURACIONUTILIZAMONEDADOLAR

      FACTURACIONCANTIDADENTEROSENCOTIZACIONDOLAR
      FACTURACIONCANTIDADDECIMALESENCOTIZACIONDOLAR

      FACTURACIONCANTIDADENTEROSENCANTIDAD

      FACTURACIONRANGOFECHAFILTROINVOCARPEDIDOS

      SITIENEDESCRECPORCANTIDADIGNORAOTROS

      FACTURACIONDECIMALESGRABARDETALLEENPRECIO

      RUTAARCHIVOSPALM

      LOGISTICAFORMATOEXPORTACIONDEFAULT

      INCLUIRESCAMBIABLEESBONIFICABLE

      SIMOVILSOPORTEURLBASE

      PREVENTAV2RESPETALISTAPRECIOSCLIENTE

      'PREVENTAV2IMPORTADESCUENTOS

      VENCIMIENTOCERTIFICADOFE

      CONSOLIDADOCARGAORDENIDPRODUCTO
      LOGISTICANORMALIZACLIENTESENRUTAS

      'EXPORTARPRECIOSCONIVA1

      ORGANIZARENTREGAFILTRAFECHAENVIO

      ORGANIZARENTREGAPERMITEDISTINTAFECHAENVIO

      REGISTRACIONPAGOSTIPOMOVIMIENTO

      ORGANIZARENTREGASFORMADEPAGO

      COLORCONCILIADO

      COLORNOCONCILIADO

      AFIPCITICOMPRASPRORRATEO

      FACTURACIONASUNTOENVIOMASIVOEMAILCTACTE

      ENVIOMASIVOCOMPROBANTESADJUNTACTACTE

      CTACTECANTDIASVENCICOMPMAIL

      CTACTECANTDIASDHRECIBOS

      PROCESOSCORREOPRUEBAPARA

      PREVENTAV2IMPORTADESCUENTOSPEDIDOSPDA

      PREVENTAV2IMPORTADESCUENTOSSIMOVILWEB

      EXPENSASPERMITIRCARGARPRODUCTOSSINCONCEPTOS
      EXPENSASREGISTRACOMPRASPOR

      OPERACIONCOTIZACIONMONEDAS

      UTILIZAPRECIOCOSTOPORLOTE

      CLIENTEPERMITEMODIFICARCODIGO

      WEBARCHIVOSPRODSUCURACTUALIZASTOCKESTOYACA

      SOLICITATIPOCOMPROBANTE

      SIMOVILSUBIDAINCLUIRCUENTASCORRIENTESDEBEHABER

      PREVENTARESPETAPRECIODELMOVIL

      IMPORTARPEDIDOSALTAPRODUCTOS

      SIMOVILSUBIDAAPLICAPRECIOSOFERTA

      PREVENTAACCIONSINLISTAPRECIOS

      REGISTRACIONPAGOSMODOCONSULTARCOMPROBANTES

      CLIENTEMUESTRACODIGOLETRAS

      SIMOVILPORCMAXDESCUENTO

      SIMOVILPORCMAXRECARGO

      CTACTEPERMITIRMODIFICARCOMPROBANTEASOCIADO
      '-- REQ-43822.- ------------------------------------
      CTACTECOBRANZAELECTRONICAHABILITAROELA
      CTACTECOBRANZAELECTRONICAHABILITASIRPLUS
      CTACTECOBRANZAELECTRONICAHABILITADEBITOAUTOMATICO
      '---------------------------------------------------
      FACTURACIONIMPRESIONFISCALSINCRONICA
      SIMOVILSUBIDAPAGINARUTAS
      SIMOVILSUBIDAPAGINARUTASCLIENTES
      SIMOVILSUBIDAPAGINARUTASLISTASPRECIOS
      SIMOVILSUBIDAPAGINACLIENTES
      SIMOVILSUBIDAPAGINACUENTASCORRIENTES
      SIMOVILSUBIDAPAGINACUENTASCORRIENTESDEBEHABER
      SIMOVILSUBIDAPAGINARUBROS
      SIMOVILSUBIDAPAGINAPRODUCTOS
      SIMOVILSUBIDAPAGINAPRODUCTOSPRECIOS
      SIMOVILSUBIDAPAGINATICKETS '-.PE-32232.-

      WEBARCHIVOSCARPETAEXPORTACION

      WEBARCHIVOSHABILITARTLS1_1

      WEBARCHIVOSHABILITARTLS1_2

      SIMOVILSUBIDAMAXIMOCUOTASENVIARCUENTASCORRIENTES
      LISTASCONTROLESTADOPENDIENTE
      LISTASCONTROLESTADOENPROCESO
      LISTASCONTROLESTADOTERMINADO
      CALIDADBASEEXTERNACLIENTES
      CALIDADPANELDECONTROLTIEMPOREFRESCO
      CALIDADPANELDECONTROLPLANTATIEMPOPAGINADO
      CALIDADURLAUDITORIALOGINWEB
      CALIDADURLACTUALIZAAUDITORIALOGINWEB

      CALIDADURLHEADERPC
      CALIDADURLHEADERURBPC
      CALIDADURLHEADERMyLPC

      CALIDADURLITEMSPC
      CALIDADURLSINCROPC

      CALIDADURLHEADERFS
      CALIDADURLITEMSFS
      CALIDADURLITEMSFSMYL
      CALIDADURLITEMSFSURB
      CALIDADURLSINCROFS
      CALIDADURLPERIODOSFS
      CALIDADURLPERIODOSFSRT
      CALIDADCOPIAOCULTAOC
      CALIDADTEXTOEDITABLEOC
      CALIDADCUERPOMAILENVIOOC

      PRODUCTOUBICACIONPORDEFECTO

      PREVENTAAGRUPAORDENPRODUCTOENCADAPEDIDO

      FACTURACIONRAPIDAMUESTRAFOTOPRODUCTO

      VERSIONDB
      VERSIONDB_RESPONSABLE

      EJECUTABLETAREAPROGRAMADA

      CAJEROIGNORARTIPOCOMPROBANTECLIENTE

      COMPRASSOLICITACOMPRADOR

      ORGANIZARENTREGAFILTROIMPRESO

      ORGANIZARENTREGAFILTROFECHADESDE

      TURISMOCATEGORIAESTABLECIMIENTO
      TURISMOCATEGORIAPASAJEROS
      TURISMOCATEGORIARESPONSABLE
      TURISMORUBROPROGRAMA
      TURISMORUBROVISITA
      TURISMORUBROGASTRONOMIA
      TURISMOFORMULAVISITAS
      TURISMOFORMULAGASTRONOMIA
      TURISMOFORMULAVISITASID
      TURISMOFORMULAGASTRONOMIAID
      TURISMOTIPOCOMPROBANTE
      TURISMOTIPOCOMPROBANTEFACTURA
      SIMOVILTURISMOURLBASE
      TURISMOROELAIDCONCEPTO
      TURISMOROELAIDCUENTA
      TURISMOROELAINTERESVTO

      TURISMOSIRPLUSNOMBREEMPRESA
      TURISMOSIRPLUSIDCONCEPTO
      TURISMOSIRPLUSIDCUENTA
      TURISMOSIRPLUSPASS
      TURISMOSIRPLUSCUENTAEMPRESA
      TURISMOSIRPLUSCBU
      TURISMOSIRPLUSCBUEMPRESA
      TURISMOSIRPLUSTIPOSCOMPROBANTES

      SIMOVILSUBIDAINCLUIRUSUARIOS
      '----
      CONCESIONARIOMOVILURLBASE
      CONCESIONARIOMOVILUSUARIO
      CONCESIONARIOMOVILCLAVE
      '---

      PMCFORMATO

      RECALCULAVALORACIONESESTRELLAS

      ABRIRARCHIVOEXPORTADO

      SIMOVILSOPORTEUSUARIODEFAULT

      UTILIZACUOTASOVENCIMIENTOCCPROVEEDORES

      '----
      TIPODOCUMENTOCLIENTE

      TIPODOCUMENTOPROVEEDOR

      VENTASCONPRODUCTOSENCERO

      FACTURACIONMODIFICANUMEROCOMPROBANTE

      FACTURACIONMODIFICADESCRIPCIONPRODUCTO

      FACTURACIONMODIFICADESCRIPRODCANTIDAD

      FACTURACIONMODDESCACUMULAPRODUCTOS

      FACTURACIONMODIFICADESCRIPSOLICITAKILOS

      FACTURACIONSALDOCTACTEINCLUYECH3ROS

      FACTURACIONMODIFICADESCRECPRODUCTO

      FACTURACIONABRIRCAJACOMPNOFISCAL

      FACTURACIONRAPIDAREEMPLAZARCOMP

      FACTURACIONMODIFICALISTADEPRECIOS

      FACTURACIONINVOCARDEOTROCLIENTE

      FACTURACIONSOLICITAVENDEDOR

      COMPRASMODIFICADESCRIPCIONPRODUCTO
      COMPRASSOLOCARGAPRODUCTOSDELPROVEEDOR

      ACTUALIZAPRECIOSDEVENTA

      FACTURACIONVISUALIZASEMAFOROUTILIDAD
      FACTURACIONVISUALIZACANTIDADCONVERTIDA
      FACTURACIONVISUALIZACONVERSION
      '-- REQ-44219.- ------------------------
      FACTURACIONVISUALIZADEPOSITO
      FACTURACIONVISUALIZAUBICACION
      '---------------------------------------
      FACTURACIONRESALTAPRODUCTOSENOFERTA

      FACTURACIONMODIFICAPRECIOPRODUCTO

      FACTURACIONSELECCIONLOTEMANUAL

      FACTURARSINSTOCK

      FACTURACIONDETALLACHEQUESYTARJETAS

      FACTURACIONCONTADOESENPESOS

      FACTURACIONMUESTRAPROVHABITUAL

      FACTURACIONOFRECECALCULARVUELTO

      RECIBOSOLICITAFECHA

      RECIBOMANTIENENUMMODIFICADA

      VISUALIZARECIBO

      CTACTECATEGORIACLIENTESRECIBO

      PERMITERECIBOSINAPLICARCOMPROBANTES

      IDPRODUCTODESCUENTORECARGO
      IDPRODUCTODESCUENTORECARGOPROV

      CTACTECATEGORIACLIENTE


      WEBARCHIVOSSYNCBASEURL
      WEBARCHIVOSSYNCEXPORTPATH

      WEBARCHIVOSSYNCINCLUIRSUBIDACLIENTES
      WEBARCHIVOSSYNCPAGINASUBIDACLIENTES
      WEBARCHIVOSSYNCINCLUIRDESCARGACLIENTES
      WEBARCHIVOSSYNCPAGINADESCARGACLIENTES

      WEBARCHIVOSSYNCINCLUIRSUBIDALOCALIDADES
      WEBARCHIVOSSYNCPAGINASUBIDALOCALIDADES
      WEBARCHIVOSSYNCINCLUIRDESCARGALOCALIDADES
      WEBARCHIVOSSYNCPAGINADESCARGALOCALIDADES

      WEBARCHIVOSSYNCINCLUIRSUBIDAMARCAS
      WEBARCHIVOSSYNCPAGINASUBIDAMARCAS
      WEBARCHIVOSSYNCINCLUIRDESCARGAMARCAS
      WEBARCHIVOSSYNCPAGINADESCARGAMARCAS

      WEBARCHIVOSSYNCINCLUIRSUBIDAPRODUCTOS
      WEBARCHIVOSSYNCPAGINASUBIDAPRODUCTOS
      WEBARCHIVOSSYNCINCLUIRDESCARGAPRODUCTOS
      WEBARCHIVOSSYNCPAGINADESCARGAPRODUCTOS

      WEBARCHIVOSSYNCINCLUIRSUBIDAPRODUCTOSSUCURSALES
      WEBARCHIVOSSYNCPAGINASUBIDAPRODUCTOSSUCURSALES
      WEBARCHIVOSSYNCINCLUIRDESCARGAPRODUCTOSSUCURSALES
      WEBARCHIVOSSYNCPAGINADESCARGAPRODUCTOSSUCURSALES

      WEBARCHIVOSSYNCINCLUIRSUBIDAPRODSUCPRECIOS
      WEBARCHIVOSSYNCPAGINASUBIDAPRODSUCPRECIOS
      WEBARCHIVOSSYNCINCLUIRDESCARGAPRODSUCPRECIOS
      WEBARCHIVOSSYNCPAGINADESCARGAPRODSUCPRECIOS

      WEBARCHIVOSSYNCINCLUIRSUBIDAPROVEEDORES
      WEBARCHIVOSSYNCPAGINASUBIDAPROVEEDORES
      WEBARCHIVOSSYNCINCLUIRDESCARGAPROVEEDORES
      WEBARCHIVOSSYNCPAGINADESCARGAPROVEEDORES

      WEBARCHIVOSSYNCINCLUIRSUBIDARUBROSCOMPRAS
      WEBARCHIVOSSYNCPAGINASUBIDARUBROSCOMPRAS
      WEBARCHIVOSSYNCINCLUIRDESCARGARUBROSCOMPRAS
      WEBARCHIVOSSYNCPAGINADESCARGARUBROSCOMPRAS

      WEBARCHIVOSSYNCINCLUIRSUBIDARUBROS
      WEBARCHIVOSSYNCPAGINASUBIDARUBROS
      WEBARCHIVOSSYNCINCLUIRDESCARGARUBROS
      WEBARCHIVOSSYNCPAGINADESCARGARUBROS

      WEBARCHIVOSSYNCINCLUIRSUBIDASUBRUBROS
      WEBARCHIVOSSYNCPAGINASUBIDASUBRUBROS
      WEBARCHIVOSSYNCINCLUIRDESCARGASUBRUBROS
      WEBARCHIVOSSYNCPAGINADESCARGASUBRUBROS

      WEBARCHIVOSSYNCINCLUIRSUBIDASUBSUBRUBROS
      WEBARCHIVOSSYNCPAGINASUBIDASUBSUBRUBROS
      WEBARCHIVOSSYNCINCLUIRDESCARGASUBSUBRUBROS
      WEBARCHIVOSSYNCPAGINADESCARGASUBSUBRUBROS

      WEBARCHIVOSSYNCINCLUIRSUBIDACRMCATEGORIAS
      WEBARCHIVOSSYNCPAGINASUBIDACRMCATEGORIAS
      WEBARCHIVOSSYNCINCLUIRDESCARGACRMCATEGORIAS
      WEBARCHIVOSSYNCPAGINADESCARGACRMCATEGORIAS
      WEBARCHIVOSCRMCATEGORIASULTIMADESCARGA

      WEBARCHIVOSSYNCINCLUIRSUBIDACRMESTADOS
      WEBARCHIVOSSYNCPAGINASUBIDACRMESTADOS
      WEBARCHIVOSSYNCINCLUIRDESCARGACRMESTADOS
      WEBARCHIVOSSYNCPAGINADESCARGACRMESTADOS
      WEBARCHIVOSCRMESTADOSULTIMADESCARGA

      WEBARCHIVOSSYNCINCLUIRSUBIDACRMMEDIOS
      WEBARCHIVOSSYNCPAGINASUBIDACRMMEDIOS
      WEBARCHIVOSSYNCINCLUIRDESCARGACRMMEDIOS
      WEBARCHIVOSSYNCPAGINADESCARGACRMMEDIOS
      WEBARCHIVOSCRMMEDIOSULTIMADESCARGA

      WEBARCHIVOSSYNCINCLUIRSUBIDACRMMETODOS
      WEBARCHIVOSSYNCPAGINASUBIDACRMMETODOS
      WEBARCHIVOSSYNCINCLUIRDESCARGACRMMETODOS
      WEBARCHIVOSSYNCPAGINADESCARGACRMMETODOS
      WEBARCHIVOSCRMMETODOSULTIMADESCARGA

      WEBARCHIVOSSYNCINCLUIRSUBIDACRMPRIORIDADES
      WEBARCHIVOSSYNCPAGINASUBIDACRMPRIORIDADES
      WEBARCHIVOSSYNCINCLUIRDESCARGACRMPRIORIDADES
      WEBARCHIVOSSYNCPAGINADESCARGACRMPRIORIDADES
      WEBARCHIVOSCRMPRIORIDADESULTIMADESCARGA

      WEBARCHIVOSSYNCINCLUIRSUBIDACRMTIPOSCOMENTARIOS
      WEBARCHIVOSSYNCPAGINASUBIDACRMTIPOSCOMENTARIOS
      WEBARCHIVOSSYNCINCLUIRDESCARGACRMTIPOSCOMENTARIOS
      WEBARCHIVOSSYNCPAGINADESCARGACRMTIPOSCOMENTARIOS
      WEBARCHIVOSCRMTIPOSCOMENTARIOSULTIMADESCARGA

      WEBARCHIVOSSYNCINCLUIRSUBIDACRMNOVEDADES
      WEBARCHIVOSSYNCPAGINASUBIDACRMNOVEDADES
      WEBARCHIVOSSYNCINCLUIRDESCARGACRMNOVEDADES
      WEBARCHIVOSSYNCPAGINADESCARGACRMNOVEDADES
      WEBARCHIVOSCRMNOVEDADESULTIMADESCARGA

      WEBARCHIVOSSYNCINCLUIRSUBIDACRMNOVEDADESSEG
      WEBARCHIVOSSYNCPAGINASUBIDACRMNOVEDADESSEG
      WEBARCHIVOSSYNCINCLUIRDESCARGACRMNOVEDADESSEG
      WEBARCHIVOSSYNCPAGINADESCARGACRMNOVEDADESSEG
      WEBARCHIVOSCRMNOVEDADESSEGULTIMADESCARGA

      '#########################################
      '#             Tienda Nube               #
      '#########################################
      TIENDANUBEURLBASE
      TIENDANUBELISTAPRECIOS
      TIENDANUBEIDPRODUCTOENVIO
      TIENDANUBECATEGORIACLIENTE
      TIENDANUBECATEGORIAFISCALCLIENTE
      TIENDANUBEVENDEDOR
      TIENDANUBEPEDIDOSTIPOCOMPROBANTE
      TIENDANUBEPEDIDOSFORMADEPAGO
      TIENDANUBEPEDIDOSCRITICIDAD
      TIENDANUBECORREONOTIFICACIONES
      TIENDANUBETOKEN
      TIENDANUBEACTUALIZAPRODUCTODESCRIPCION
      TIENDANUBEPRECIOPRODUCTO
      TIENDANUBEPRODUCTOACTIVOWEB
      TIENDANUBESLEEPENTRESOLICITUDES
      TIENDANUBEPRECIOPOREMBALAJE

      '-----------------------------------------
      '#########################################
      '#           Mercado Libre               #
      '#########################################
      MERCADOLIBREURLBASE
      MERCADOLIBRELISTAPRECIOS
      MERCADOLIBREIDPRODUCTOENVIO
      MERCADOLIBRECATEGORIACLIENTE
      MERCADOLIBRECATEGORIAFISCALCLIENTE
      MERCADOLIBREVENDEDOR
      MERCADOLIBREPEDIDOSTIPOCOMPROBANTE
      MERCADOLIBREPEDIDOSFORMADEPAGO
      MERCADOLIBREPEDIDOSCRITICIDAD
      MERCADOLIBRECORREONOTIFICACIONES
      MERCADOLIBRETOKEN
      MERCADOLIBREREFRESHTOKEN
      MERCADOLIBREFECHATOKEN
      MERCADOLIBREIMAGENDEFAULT
      MERCADOLIBRECODIGORESELLER
      MERCADOLIBRECATEGORIADEFAULT
      MERCADOLIBREAPPID
      MERCADOLIBRESECRETKEY
      MERCADOLIBRECAJADEFAULT
      MERCADOLIBREPRECIOPOREMBALAJE

      '-----------------------------------------
      '#########################################
      '#           Arborea                     #
      '#########################################
      ARBOREAURLBASE
      ARBOREAUSUARIOTOKEN
      ARBOREACLAVETOKEN
      ARBOREACATEGORIAPRINCIPAL
      ARBOREACORREONOTIFICACIONES
      ARBOREAIDPRODUCTOENVIO
      ARBOREACATEGORIACLIENTE
      ARBOREACATEGORIAFISCALCLIENTE
      ARBOREAVENDEDOR
      ARBOREAPEDIDOSTIPOCOMPROBANTE
      ARBOREAPEDIDOSCRITICIDAD
      ARBOREAPEDIDOSFORMADEPAGO
      ARBOREALISTADEPRECIOS
      '-----------------------------------------
      ARBOREAURLLISTAPRECIOS
      ARBOREAURLLISTAPRECIOSCLIENTES
      ARBOREAEXPORTARSOLICITUDESSUBIDA
      ARBOREAEXPORTARSOLICITUDESSUBIDAPATH
      ARBOREASINCRONIZACATEGORIAS
      '-- REQ-40570.- --------------------------
      ARBOREAIMPORTAMARCASUBIDA
      ARBOREAIMPORTAMARCASUBIDAID
      '-- REQ-33384.- --------------------------
      ARBOREALISTAPRECIOS01
      ARBOREALISTAPRECIOS02
      ARBOREALISTAPRECIOS03
      ARBOREALISTAPRECIOS04

      ARBOREALISTAPRECIOSCLNUEVO

      ARBOREAACTUALIZACATEGORIA
      ARBOREAPRECIOPRODUCTO
      ARBOREAPRECIOPOREMBALAJE

      PRECIOCONIVAINCLUIDOLISTAPV
      PRECIOCONIVAINCLUIDOLISTALP1
      PRECIOCONIVAINCLUIDOLISTALP2
      PRECIOCONIVAINCLUIDOLISTALP3

      '-- REQ-31725.- --
      VENTASPIRELLIURLBASE
      VENTASPIRELLIIDMARCA
      VENTASPIRELLIIDSUCURSAL
      '-- REQ-34667.- -------------
      TIPOATRIBUTOPRODUCTO01
      TIPOATRIBUTOPRODUCTO02
      TIPOATRIBUTOPRODUCTO03
      TIPOATRIBUTOPRODUCTO04
      '----------------------------

      MODIFICARPRECIOPORDEBAJOPL
      PORCENTAJEPORDEBAJOPL
      MODIFICARPRECIOPORARRIBAPL
      PORCENTAJEPORARRIBAPL

      ENVIAMAILCLIENTERECIBO
      BEJERMANFECHAMODIFICACIONPROVEEDOR
      BEJERMANFECHAMODIFICACIONORDENCOMPRA
      BEJERMANFECHAMODIFOCAUTORIZADAS
      BEJERMANFECHAULTIMASINCRONIZACIONOC

      METALSURURLBASEWEBOC

      '        1         2         3         4         5         6         7
      '234567890123456789012345678901234567890123456789012345678901234567890

      SIMOVILGESTIONTURNOSURLBASE

      SIMOVILSUBIDAINCLUIRCALENDARIOS

      SIMOVILSUBIDAINCLUIREMBARCACIONES

      SIMOVILSUBIDAINCLUIRDESTINOS

      SIMOVILTURNOSURLBASE
      SIMOVILOFICINAURLPRODUCCION
      SIMOVILOFICINAURLTESTING

      LOGINMESESPRESERVARBITACORAERROR

      MESESARCHIVARCRMFINALIZADOS

      MAILCOPIAOCULTACOMPELECTRONICO

      ENVIACOMAILCOMPELECTRONICO

      CONTROLADIASVTODECREDITODECLIENTES
      PEDIDOSCONTROLADIASVTODECREDITODECLIENTES

      GENERALESSUBTOTALESENGRILLAS
      RETENCIONESGANANCIASCALCULORECURSIVO
      RETENCIONESGANANCIASCALCULORECURSIVOREPETIR
      COMPRASCONPRODUCTOSENCERO
      CALIDADUTILIZAPAGAUTOMATICOPANELCONTROLPLANTA

      'nuevo PE-31183
      ReservaSemaforoAmarillo
      IDEDICIONAPLICACION
      'PE-30973
      DIASALERTACLIENTESCATEGORIAMODIFICAR

      'PE-31388
      PRODUCTOPUBLICARWEBCARRITO
      PRODUCTOPUBLICARBALANZA
      PRODUCTOPUBLICARLISTAPRECIOCLIENTES
      PRODUCTOPUBLICARAPPGESTION
      PRODUCTOPUBLICARSINCRONIZACIONSUCURSAL
      PRODUCTOPUBLICARAPPEMPRESARIAL
      PRODUCTOPUBLICARTIENDANUBE
      PRODUCTOPUBLICARMERCADOLIBRE
      PRODUCTOPUBLICARARBOREA

      '-.PE-31623.-
      MUESTRAFECHAACTUALIZA
      FICHASSINREFERENCIADECUOTA
      DIASVISUALIZACIONLIBROBANCO
      TAREASPORUSUARIO
      DIASVALIDEZPRESUPUESTO
      NROHOJALIBROIVAVENTAS
      VISUALIZACOMPROBANTESDEVENTA
      VENTASPRECIOCOSTO
      VENTASPRECIOVENTA

      IDNDEBNOGL
      IDNCREDGL
      IDNDEBGL
      IDNCREDNOGL
      IDNDEBNOGLPROV
      IDNCREDNOGLPROV
      FACTURACIONCOMPROBFECHNUMANTERIOR
      FACTURACIONCOMPROBFECHAFUTURA
      FACTURACIONPORCUENTAYORDEN
      COMISIONVENDEDOR
      NDEBCHEQRECH
      FACTELECGUARDARLOG
      FACTELECGUARDARLOGPATH
      CLIENTEUTILIZAGEOLOCALIZACION
      CLIENTEMULTIPLESDIRECCIONES
      EMPLEADOUTILIZAGEOLOCALIZACION
      CLIENTETIENETRABAJO
      CLIENTETIENEGARANTE
      CLIENTEUTILIZAOTROS
      CLIENTEUTILIZACONTACTOS
      CLIENTEUTILIZAADJUNTOS
      CLIENTEUTILIZAIMPUESTOS
      CLIENTEUTILIZAHORARIOS
      CLIENTEREQUIERETELEFONO
      CLIENTEREQUIERECELULAR
      CLIENTEREQUIERECORREOELECTRONICO
      CLIENTEREQUIERECORREOADMINISTRATIVO

      CONTACTOSAGENDAPRIVADA
      '-- REQ-34505.- ------------
      ALTANUEVOCLIENTEPUBLICAWEB
      '---------------------------
      POLITICASSEGURIDADCLAVES
      ProductoIVA
      PRODUCTOEMBALAJEINVERSO
      PRODUCTOCODIGOQUITARBLANCOS
      PRODUCTOUTILIZACANTIDADESENTERAS

      '-.PE-32652.-
      ALERTAPEDIDOSSINCANTIDADITEMS
      ALERTAPEDIDOSCONCANTIDADITEMS
      FACTURACIONRAPIDAAGRUPAPRODUCTOS
      FACTURACIONIMPRESIONORDENPRODUCTOS
      FACTURACIONIMPRIMERECIBOVENTASCTACTE
      COMPRASCONTADOESENPESOS
      COMPRASIMPRESIONVISNROSERIE
      COMPRASPRECIOCOSTO
      VISUALIZACODIGOPROVEEDOR
      VISUALIZAPORCVARCOSTO
      NROHOJALIBROIVACOMPRAS
      VISUALIZACOMPROBANTESDECOMPRA
      MODULOPEDIDOS
      MODULOPEDIDOSPROV
      PAGOSOLICITAFECHA
      CARACTERESPRODUCTOCBPESOCANTIDAD
      FACTURACIONVISUALIZAORDEN
      '-- REQ-33372.- --
      CUENTACORRIENTEEMBARCACION
      '-- REQ-36328.- --
      CUENTACORRIENTECAMA
      '-----------------
      FACTURACIONRAPIDAPERMITEMODIFICARCLIENTE
      FACTURACIONPERMITEAPLICARSALDOCTACTE
      CRMNOVEDADESFORMADEPAGO
      CRMNOVEDADESCOPIARSALDOCOMOEFECTIVOALFACTURAR
      VENTASVISUALIZARCOMPROBANTEASUMEIMPRESION
      CANTEMAILSPORMINUTO
      CANTEMAILSPORHORA
      VISUALIZANROSERIE
      VISUALIZALOTE
      UTILIZACUOTASOVENCIMIENTOCCCLIENTES
      NROEMPRESABANELCO
      CONSULTARPRECIOSCONIVA
      UTILIZAPRECIODECOMPRA
      CONSULTPRECOCULTARPRODNOAFECTSTOCK
      MOSTRAROBSERVACIONDECOMPROBANTES
      SIMOVILSUBIDAEXPORTARARCHIVOSENVIAR
      SIMOVILSUBIDAPATHEXPORTARARCHIVOSENVIAR
      SINCRONIZA
      EXTRASSINERGIA
      MODULOALQUILER
      MODULOPRODUCCION
      IDTICKETFISCAL
      IDTICKETFACTURAFISCAL
      CLIENTEUTILIZACBU
      PRODUCTOTIENEMODELO
      PRODUCTOUTILIZAALICUOTA2
      CLIENTEDRGRABALIBRO
      NOMBREBASEEMBARCACIONESFOTOS
      PRODUCTOSCANTIDADCOMPRASSOLAPACOMPRAS
      OCULTARPRODUCTOSINACTIVOSABMPRODUCTOS
      PEDIDOSPERMITIRMODIFICARNOGESTIONADOS
      COTIZACIONDOLARCOMPROBANTEINVOCADO
      COTIZACIONDOLARPEDIDOINVOCADO
      COTIZACIONDOLARCOMPROBANTEPESOSINVOCADO
      COTIZACIONDOLARPEDIDOPESOSINVOCADO
      '-- MRP.- --
      MRPRDENPRODUCCIONPORITEMPEDIDO
   End Enum

End Class