
INSERT INTO [Productos]
           ([IdProducto]
           ,[NombreProducto]
           ,[Tamano]
           ,[IdUnidadDeMedida]
           ,[IdMarca]
           ,[IdRubro]
           ,[MesesGarantia]
           ,[Activo]
           ,[AfectaStock]
           ,[IdModelo]
           ,[IdSubRubro]
           ,[Foto]
           ,[Lote]
           ,[NroSerie]
           ,[IdTipoImpuesto]
           ,[Alicuota]
           ,[CodigoDeBarras]
           ,[EsServicio]
           ,[Observacion]
           ,[PublicarEnWeb]
           ,[EsDeCompras]
           ,[EsDeVentas]
           ,[DescontarStockComponentes]
           ,[IdMoneda]
           ,[EsCompuesto]
           ,[CodigoDeBarrasConPrecio]
           ,[EsAlquilable]
           ,[EquipoMarca]
           ,[EquipoModelo]
           ,[NumeroSerie]
           ,[CaractSII]
           ,[Anio]
           ,[PermiteModificarDescripcion]
           ,[Alicuota2]
           ,[PagaIngresosBrutos]
           ,[Embalaje]
           ,[Kilos]
           ,[IdFormula]
           ,[IdProductoMercosur]
           ,[IdProductoSecretaria]
           ,[PublicarListaDePreciosClientes]
           ,[FacturacionCantidadNegativa]
           ,[SolicitaEnvase]
           ,[AlertaDeCaja]
           ,[NombreCorto]
           ,[EsRetornable]
           ,[Orden]
           ,[ModalidadCodigoDeBarras]
           ,[IdProveedor]
           ,[CodigoLargoProducto]
           ,[EsObservacion]
           ,[PrecioPorEmbalaje]
           ,[UnidHasta1]
           ,[UnidHasta2]
           ,[UnidHasta3]
           ,[UHPorc1]
           ,[UHPorc2]
           ,[UHPorc3]
           ,[IdCuentaCompras]
           ,[IdCuentaVentas]
           ,[ImporteImpuestoInterno]
           ,[EsOferta]
           ,[IncluirExpensas]
           ,[IdCuentaComprasSecundaria]
		   ,[PorcImpuestoInterno]
		   ,[CalculaPreciosSegunFormula]
		   ,[EsCambiable]
		   ,[EsBonificable]
		   ,[UnidHasta4]
		   ,[UnidHasta5]
		   ,[UHPorc4]
		   ,[UHPorc5]
		   ,[ObservacionCompras]
		   ,[SolicitaPrecioVentaPorTamano])
   SELECT [IdProducto]
           ,[NombreProducto]
           ,[Tamano]
           ,[IdUnidadDeMedida]
           ,[IdMarca]
           ,[IdRubro]
           ,[MesesGarantia]
           ,[Activo]
           ,[AfectaStock]
           ,[IdModelo]
           ,[IdSubRubro]
           ,[Foto]
           ,[Lote]
           ,[NroSerie]
           ,[IdTipoImpuesto]
           ,[Alicuota]
           ,[CodigoDeBarras]
           ,[EsServicio]
           ,[Observacion]
           ,[PublicarEnWeb]
           ,[EsDeCompras]
           ,[EsDeVentas]
           ,[DescontarStockComponentes]
           ,[IdMoneda]
           ,[EsCompuesto]
           ,1 as [CodigoDeBarrasConPrecio]
           ,0 as [EsAlquilable]
           ,null as [EquipoMarca]
           ,null as [EquipoModelo]
           ,null as [NumeroSerie]
           ,null as [CaractSII]
           ,null as [Anio]
           ,0 as [PermiteModificarDescripcion]
           ,null as [Alicuota2]
           ,1 as [PagaIngresosBrutos]
           ,0 as [Embalaje]
           ,0 as [Kilos]
           ,null as [IdFormula]
           ,null as [IdProductoMercosur]
           ,null as [IdProductoSecretaria]
           ,1 as [PublicarListaDePreciosClientes]
           ,0 as [FacturacionCantidadNegativa]
           ,0 as [SolicitaEnvase]
           ,0 as [AlertaDeCaja]
           ,null as [NombreCorto]
           ,0 as [EsRetornable]
           ,1 as [Orden]
           ,null as [ModalidadCodigoDeBarras]
           ,null as [IdProveedor]
           ,null as [CodigoLargoProducto]
           ,0 as [EsObservacion]
           ,0 as [PrecioPorEmbalaje]
           ,0 as [UnidHasta1]
           ,0 as [UnidHasta2]
           ,0 as [UnidHasta3]
           ,0 as [UHPorc1]
           ,0 as [UHPorc2]
           ,0 as [UHPorc3]
           ,null as [IdCuentaCompras]
           ,null as [IdCuentaVentas]
           ,0 as [ImporteImpuestoInterno]
           ,0 as [EsOferta]
           ,0 as [IncluirExpensas]
           ,null as [IdCuentaComprasSecundaria]
		   ,0 as [PorcImpuestoInterno]
		   ,0 as [CalculaPreciosSegunFormula]
		   ,0 as [EsCambiable]
		   ,0 as [EsBonificable]
		   ,0 as [UnidHasta4]
		   ,0 as [UnidHasta5]
		   ,0 as [UHPorc4]
		   ,0 as [UHPorc5]
		   ,0 as [ObservacionCompras]
		   ,0 as [SolicitaPrecioVentaPorTamano]
  FROM MO_SIGA.[dbo].[Productos]
  GO
