
MERGE INTO Localidades AS P
     USING MO_SIGA.dbo.Localidades AS PT
        ON P.IdLocalidad = PT.IdLocalidad
 WHEN NOT MATCHED THEN
    INSERT (   IdLocalidad,    NombreLocalidad,    IdProvincia)
    VALUES (PT.IdLocalidad, PT.NombreLocalidad, PT.IdProvincia)
;

DELETE FROM AuditoriaClientes
;

INSERT INTO AuditoriaClientes
           (FechaAuditoria
           ,OperacionAuditoria
           ,UsuarioAuditoria
           ,[TipoDocumentoAnterior]
           ,[NroDocumentoAnterior]
           ,[NombreCliente]
           ,[Direccion]
           ,[IdLocalidad]
           ,[Telefono]
           ,[FechaNacimiento]
           ,[NroOperacion]
           ,[CorreoElectronico]
           ,[Celular]
           ,[NombreTrabajo]
           ,[DireccionTrabajo]
           ,[IdLocalidadTrabajo]
           ,[TelefonoTrabajo]
           ,[CorreoTrabajo]
           ,[FechaIngresoTrabajo]
           ,[FechaAlta]
           ,[SaldoPendiente]
           ,[IdCategoria]
           ,[IdCategoriaFiscal]
           ,[Cuit]
           ,[TipoDocVendedor]
           ,[NroDocVendedor]
           ,[Observacion]
           ,[IdListaPrecios]
           ,[IdZonaGeografica]
           ,[Activo]
           ,[LimiteDeCredito]
           ,[IdSucursalAsociada]
           ,[NombreDeFantasia]
           ,[DescuentoRecargoPorc]
           ,[IdTipoComprobante]
           ,[IdFormasPago]
           ,[Foto]
           ,[IdTransportista]
           ,[IngresosBrutos]
           ,[InscriptoIBStaFe]
           ,[LocalIB]
           ,[ConvMultilateralIB]
           ,[NumeroLote]
           ,[IdCaja]
           ,[GeoLocalizacionLat]
           ,[GeoLocalizacionLng]
           ,[IdTipoDeExension]
           ,[AnioExension]
           ,[NroCertExension]
           ,[NroCertPropio]
           ,[IdCliente]
           ,[CodigoCliente]
           ,[IdClienteGarante]
           ,[TipoDocCliente]
           ,[NroDocCliente]
           ,[DescuentoRecargoPorc2]
           ,[IdClienteCtaCte]
           ,[PaginaWeb]
           ,[LimiteDiasVtoFactura]
		   ,[IdEstado]
		   ,[IdCobrador]
		   ,[IdTipoCliente]
           ,ModificarDatos
           ,EsResidente
		   )
     SELECT FechaAuditoria
           ,OperacionAuditoria
           ,UsuarioAuditoria
           ,TipoDocumento as [TipoDocumentoAnterior]
           ,NroDocumento as [NroDocumentoAnterior]
           ,[NombreCliente]
           ,[Direccion]
           ,[IdLocalidad]
           ,[Telefono]
           ,[FechaNacimiento]
           ,[NroOperacion]
           ,[CorreoElectronico]
           ,[Celular]
           ,[NombreTrabajo]
           ,[DireccionTrabajo]
           ,[IdLocalidadTrabajo]
           ,[TelefonoTrabajo]
           ,[CorreoTrabajo]
           ,[FechaIngresoTrabajo]
           ,[FechaAlta]
           ,[SaldoPendiente]
           ,[IdCategoria]
           ,[IdCategoriaFiscal]
           ,[Cuit]
           ,[TipoDocVendedor]
           ,[NroDocVendedor]
           ,[Observacion]
           ,[IdListaPrecios]
           ,[IdZonaGeografica]
           ,[Activo]
           ,[LimiteDeCredito]
           ,[IdSucursalAsociada]
           ,[NombreDeFantasia]
           ,[DescuentoRecargoPorc]
           ,CASE WHEN [IdTipoComprobante] = 'SALDOINICIAL' THEN NULL ELSE [IdTipoComprobante] END AS IdTipoComprobante
           ,[IdFormasPago]
           ,null as [Foto]
           ,null as [IdTransportista]
           ,null as [IngresosBrutos]
           ,0 as [InscriptoIBStaFe]
           ,0 as  [LocalIB]
           ,0 as [ConvMultilateralIB]
           ,null as [NumeroLote]
           ,null as [IdCaja]
           ,null as [GeoLocalizacionLat]
           ,null as [GeoLocalizacionLng]
           ,null as [IdTipoDeExension]
           ,null as [AnioExension]
           ,null as [NroCertExension]
           ,null as [NroCertPropio]
           --,ROW_NUMBER() OVER(ORDER BY NroDocumento ASC) as [IdCliente]
           --,ROW_NUMBER() OVER(ORDER BY NroDocumento ASC) as [CodigoCliente]
           ,NroDocumento AS [IdCliente]
           ,NroDocumento AS [CodigoCliente]
           ,null as [IdClienteGarante]
           ,TipoDocumento as [TipoDocCliente]
           ,NroDocumento as [NroDocCliente]
           ,0 as [DescuentoRecargoPorc2]
           ,null as [IdClienteCtaCte]
           ,null as [PaginaWeb]
           ,0 as [LimiteDiasVtoFactura]
		   ,1 as [IdEstado]
		   ,1 as [IdCobrador]
		   ,1 as [IdTipoCliente]
		   ,'True' AS ModificarDatos
		   ,'False' AS EsResidente
   
  FROM MO_SIGA.[dbo].AuditoriaClientes
GO

UPDATE AuditoriaClientes
  SET TipoDocCliente = NULL
     ,NroDocCliente = NULL
 WHERE LEN(NroDocCliente)<6
GO

DELETE FROM [Clientes]
;

INSERT INTO [Clientes]
           ([TipoDocumentoAnterior]
           ,[NroDocumentoAnterior]
           ,[NombreCliente]
           ,[Direccion]
           ,[IdLocalidad]
           ,[Telefono]
           ,[FechaNacimiento]
           ,[NroOperacion]
           ,[CorreoElectronico]
           ,[Celular]
           ,[NombreTrabajo]
           ,[DireccionTrabajo]
           ,[IdLocalidadTrabajo]
           ,[TelefonoTrabajo]
           ,[CorreoTrabajo]
           ,[FechaIngresoTrabajo]
           ,[FechaAlta]
           ,[SaldoPendiente]
           ,[IdCategoria]
           ,[IdCategoriaFiscal]
           ,[Cuit]
           ,[TipoDocVendedor]
           ,[NroDocVendedor]
           ,[Observacion]
           ,[IdListaPrecios]
           ,[IdZonaGeografica]
           ,[Activo]
           ,[LimiteDeCredito]
           ,[IdSucursalAsociada]
           ,[NombreDeFantasia]
           ,[DescuentoRecargoPorc]
           ,[IdTipoComprobante]
           ,[IdFormasPago]
           ,[Foto]
           ,[IdTransportista]
           ,[IngresosBrutos]
           ,[InscriptoIBStaFe]
           ,[LocalIB]
           ,[ConvMultilateralIB]
           ,[NumeroLote]
           ,[IdCaja]
           ,[GeoLocalizacionLat]
           ,[GeoLocalizacionLng]
           ,[IdTipoDeExension]
           ,[AnioExension]
           ,[NroCertExension]
           ,[NroCertPropio]
           ,[IdCliente]
           ,[CodigoCliente]
           ,[IdClienteGarante]
           ,[TipoDocCliente]
           ,[NroDocCliente]
           ,[DescuentoRecargoPorc2]
           ,[IdClienteCtaCte]
           ,[PaginaWeb]
           ,[LimiteDiasVtoFactura]
		   ,[IdEstado]
		   ,[IdCobrador]
		   ,[IdTipoCliente]
		   )
     SELECT TipoDocumento as [TipoDocumentoAnterior]
           ,NroDocumento as [NroDocumentoAnterior]
           ,[NombreCliente]
           ,[Direccion]
           ,[IdLocalidad]
           ,[Telefono]
           ,[FechaNacimiento]
           ,[NroOperacion]
           ,[CorreoElectronico]
           ,[Celular]
           ,[NombreTrabajo]
           ,[DireccionTrabajo]
           ,[IdLocalidadTrabajo]
           ,[TelefonoTrabajo]
           ,[CorreoTrabajo]
           ,[FechaIngresoTrabajo]
           ,[FechaAlta]
           ,[SaldoPendiente]
           ,[IdCategoria]
           ,[IdCategoriaFiscal]
           ,[Cuit]
           ,[TipoDocVendedor]
           ,[NroDocVendedor]
           ,[Observacion]
           ,[IdListaPrecios]
           ,[IdZonaGeografica]
           ,[Activo]
           ,[LimiteDeCredito]
           ,[IdSucursalAsociada]
           ,[NombreDeFantasia]
           ,[DescuentoRecargoPorc]
           ,CASE WHEN [IdTipoComprobante] = 'SALDOINICIAL' THEN NULL ELSE [IdTipoComprobante] END AS IdTipoComprobante
           ,[IdFormasPago]
           ,null as [Foto]
           ,null as [IdTransportista]
           ,null as [IngresosBrutos]
           ,0 as [InscriptoIBStaFe]
           ,0 as  [LocalIB]
           ,0 as [ConvMultilateralIB]
           ,null as [NumeroLote]
           ,null as [IdCaja]
           ,null as [GeoLocalizacionLat]
           ,null as [GeoLocalizacionLng]
           ,null as [IdTipoDeExension]
           ,null as [AnioExension]
           ,null as [NroCertExension]
           ,null as [NroCertPropio]
           --,ROW_NUMBER() OVER(ORDER BY NroDocumento ASC) as [IdCliente]
           --,ROW_NUMBER() OVER(ORDER BY NroDocumento ASC) as [CodigoCliente]
           ,NroDocumento AS [IdCliente]
           ,NroDocumento AS [CodigoCliente]
           ,null as [IdClienteGarante]
           ,TipoDocumento as [TipoDocCliente]
           ,NroDocumento as [NroDocCliente]
           ,0 as [DescuentoRecargoPorc2]
           ,null as [IdClienteCtaCte]
           ,null as [PaginaWeb]
           ,0 as [LimiteDiasVtoFactura]
		   ,1 as [IdEstado]
		   ,1 as [IdCobrador]
		   ,1 as [IdTipoCliente]
  FROM MO_SIGA.[dbo].[Clientes]
GO


UPDATE [Clientes]
  SET TipoDocCliente = NULL
     ,NroDocCliente = NULL
 WHERE LEN(NroDocCliente)<6
GO
