
/* Elimino la Referencia desde VentasProductosLotes */

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.VentasProductosLotes
	DROP CONSTRAINT FK_VentasProductosLotes_VentasProductos
GO
ALTER TABLE dbo.VentasProductos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.VentasProductosLotes SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


/* Elimino la Clave Primaria (PK) */

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.VentasProductos
	DROP CONSTRAINT PK_VentasProductos
GO
ALTER TABLE dbo.VentasProductos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* Ajusto el campo */

ALTER TABLE dbo.VentasProductos ALTER COLUMN
	Orden Int NOT NULL
GO

ALTER TABLE dbo.VentasProductos ADD 
	Orden2 Int NULL
GO

UPDATE dbo.VentasProductos SET Orden2 = Orden
GO

ALTER TABLE dbo.VentasProductos ALTER COLUMN
	Orden2 Int NOT NULL
GO

ALTER TABLE dbo.VentasProductos DROP COLUMN	Orden 
GO

EXEC sp_rename 'VentasProductos.Orden2', 'Orden', 'COLUMN'
GO


/* Vuelvo a Crear la Clave Primaria (PK) */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.VentasProductos ADD CONSTRAINT
	PK_VentasProductos PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdTipoComprobante,
	Letra,
	CentroEmisor,
	NumeroComprobante,
	Orden,
	IdProducto
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.VentasProductos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
