
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ParametrosImagenes](
	[IdParametroImagen] [varchar](50) NOT NULL,
	[ValorParametroImagen] [image] NULL,
 CONSTRAINT [PK_ParametrosImagenes] PRIMARY KEY CLUSTERED 
(
	[IdParametroImagen] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
