
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CuentasCorrientes ADD ImporteRetenciones decimal(10, 2) NULL
GO
ALTER TABLE dbo.CuentasCorrientes SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

UPDATE CuentasCorrientes SET ImporteRetenciones = 0
GO

ALTER TABLE dbo.CuentasCorrientes ALTER COLUMN ImporteRetenciones decimal(10,2) NOT NULL
GO
