

/* Elimino la Clave Primaria (PK) */

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ComprasProductos
	DROP CONSTRAINT PK_ComprasProductos
GO
ALTER TABLE dbo.ComprasProductos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* Ajusto el campo */

ALTER TABLE dbo.ComprasProductos ALTER COLUMN
	Orden Int NOT NULL
GO

ALTER TABLE dbo.ComprasProductos ADD 
	Orden2 Int NULL
GO

UPDATE dbo.ComprasProductos SET Orden2 = Orden
GO

ALTER TABLE dbo.ComprasProductos ALTER COLUMN
	Orden2 Int NOT NULL
GO

ALTER TABLE dbo.ComprasProductos DROP COLUMN Orden 
GO

EXEC sp_rename 'ComprasProductos.Orden2', 'Orden', 'COLUMN'
GO


/* Vuelvo a Crear la Clave Primaria (PK) */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ComprasProductos ADD CONSTRAINT
	PK_ComprasProductos PRIMARY KEY CLUSTERED 
	(
	IdSucursal,
	IdTipoComprobante,
	Letra,
	CentroEmisor,
	NumeroComprobante,
	TipoDocProveedor,
	NroDocProveedor,
	Orden,
	IdProducto
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ComprasProductos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
