
/* Campo Nuevo */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Productos ADD
	EsCompuesto bit NULL
GO
ALTER TABLE dbo.Productos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


/* OTROS */

UPDATE Productos SET EsCompuesto = 'False'
GO

UPDATE Productos SET EsCompuesto = 'True'
 WHERE IdProducto IN (SELECT DISTINCT IdProducto FROM ProductosComponentes)
GO

ALTER TABLE Productos ALTER COLUMN EsCompuesto bit NOT NULL
GO
