
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Observaciones](
	[IdObservacion] [int] NOT NULL,
	[DetalleObservacion] [varchar](100) NOT NULL,
	[Tipo] [varchar](10) NOT NULL,
 CONSTRAINT [PK_Observaciones] PRIMARY KEY CLUSTERED 
(
	[IdObservacion] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


