Public Class TraductorInfragistics

   Public Shared Sub TraducirShared()
      Dim ins As TraductorInfragistics = New TraductorInfragistics()
      ins.Traducir()
   End Sub

   Public Overridable Sub Traducir()
      'link de donde sacar los nombres de recursos a cambiar
      'http://help.infragistics.com/Help/NetAdvantage/NET/2008.3/CLR2.0/html/WinPrintPreviewDialog_Resource_Strings.html
      Dim lrc As Infragistics.Shared.ResourceCustomizer
      lrc = Infragistics.Win.Printing.Resources.Customizer
      lrc.SetCustomizedString("PrintPreview_DialogCaption", "Vista Preliminar")
      'lrc.SetCustomizedString("PrintPreview_Tool_ClosePreview", "&Cerrar")
      'lrc.SetCustomizedString("PrintPreview_Tool_File", "&Archivo")
      'lrc.SetCustomizedString("PrintPreview_Tool_File_AccessibleDescription", "Menú de Archivo.")
      'lrc.SetCustomizedString("PrintPreview_Tool_Tools", "&Herramientas")
      'lrc.SetCustomizedString("PrintPreview_Tool_Tools_AccessibleDescription", "Menú de Herramientas.")
      'lrc.SetCustomizedString("PrintPreview_Tool_Print", "&Imprimir")
      'lrc.SetCustomizedString("PrintPreview_Tool_Print_AccessibleDescription", "Imprimir el documento.")
      'lrc.SetCustomizedString("PrintPreview_Tool_Exit", "&Salir")
      'lrc.SetCustomizedString("PrintPreview_Tool_Exit_AccessibleDescription", "Cierra la pantalla de la vista preliminar.")
      'lrc.SetCustomizedString("PrintPreview_Tool_View", "&Ver")
      'lrc.SetCustomizedString("PrintPreview_Tool_View_AccessibleDescription", "Menu de Ver")
      'lrc.SetCustomizedString("PrintPreview_Tool_Page_Setup", "&Configurar Página...")
      'lrc.SetCustomizedString("PrintPreview_Tool_Page_Setup_AccessibleDescription", "Muestra la pantalla de Configurar Página.")

      lrc.SetCustomizedString("PrintPreview_Tool_ClosePreview", "&Cerrar")
      lrc.SetCustomizedString("PrintPreview_Tool_ClosePreview_AccessibleDescription", "Cerrar el dialogo de vista preliminar")



      lrc.SetCustomizedString("PrintPreview_Tool_Continuous", "Continuo")
      lrc.SetCustomizedString("PrintPreview_Tool_Continuous_AccessibleDescription", "Muestra las páginas de manera continua cuando se desplaza.")
      lrc.SetCustomizedString("PrintPreview_Tool_Current_Page", "Página actual")
      lrc.SetCustomizedString("PrintPreview_Tool_Current_Page_AccessibleDescription", "La página actual mostrada en la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Dynamic_Zoom_Tool", "&Herramienta de zoom dinámico")
      lrc.SetCustomizedString("PrintPreview_Tool_Dynamic_Zoom_Tool_AccessibleDescription", "Utilize el mouse para realizar acercar o alejar el zoom.")
      lrc.SetCustomizedString("PrintPreview_Tool_Enlarge_Page_Thumbnails", "Agrandar miniatura de página")
      lrc.SetCustomizedString("PrintPreview_Tool_Enlarge_Page_Thumbnails_AccessibleDescription", "Agranda miniatura de página.")
      lrc.SetCustomizedString("PrintPreview_Tool_Exit", "&Salir")
      lrc.SetCustomizedString("PrintPreview_Tool_Exit_AccessibleDescription", "Salir de la vista preliminar.")
      lrc.SetCustomizedString("PrintPreview_Tool_File", "&Archivo")
      lrc.SetCustomizedString("PrintPreview_Tool_File_AccessibleDescription", "Menú Archivo.")
      lrc.SetCustomizedString("PrintPreview_Tool_First_Page", "Primera página")
      lrc.SetCustomizedString("PrintPreview_Tool_First_Page_AccessibleDescription", "Muestra la primera página en la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Go_To", "Ir a la página")
      lrc.SetCustomizedString("PrintPreview_Tool_Go_To_AccessibleDescription", "Ir a una página diferente en la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Hand_Tool", "Herramienta &Manual")
      lrc.SetCustomizedString("PrintPreview_Tool_Hand_Tool_AccessibleDescription", "Permite realizar desplazamientos con el mouse en la pantalla de vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Last_Page", "Última página")
      lrc.SetCustomizedString("PrintPreview_Tool_Last_Page_AccessibleDescription", "Muestra la última página en la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Margin_Width", "Ancho de márgenes")
      lrc.SetCustomizedString("PrintPreview_Tool_Margin_Width_AccessibleDescription", "Ampliar la página para que su margen más amplio se ajuste a la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Next_Page", "Siguiente página")
      lrc.SetCustomizedString("PrintPreview_Tool_Next_Page_AccessibleDescription", "Muestra la siguiente página en la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Next_View", "&Siguiente Vista")
      lrc.SetCustomizedString("PrintPreview_Tool_Next_View_AccessibleDescription", "Muestra la siguiente vista en la historico de vistas.")
      lrc.SetCustomizedString("PrintPreview_Tool_Page_Layout", "Formato de página")
      lrc.SetCustomizedString("PrintPreview_Tool_Page_Layout_AccessibleDescription", "Permite cambiar el formato de página de la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Page_Setup", "&Configurar Página...")
      lrc.SetCustomizedString("PrintPreview_Tool_Page_Setup_AccessibleDescription", "Muestra la pantalla de Configurar Página.")
      lrc.SetCustomizedString("PrintPreview_Tool_Page_Width", "Ancho de página")
      lrc.SetCustomizedString("PrintPreview_Tool_Page_Width_AccessibleDescription", "Ajusta la página para que si ancho se ajuste al de la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Previous_Page", "Anterior página")
      lrc.SetCustomizedString("PrintPreview_Tool_Previous_Page_AccessibleDescription", "Muestra la anterior página en la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Previous_View", "&Anterior Vista")
      lrc.SetCustomizedString("PrintPreview_Tool_Previous_View_AccessibleDescription", "Muestra la anterior vista en la historico de vistas.")
      lrc.SetCustomizedString("PrintPreview_Tool_Print", "&Imprimir")
      lrc.SetCustomizedString("PrintPreview_Tool_Print_AccessibleDescription", "Imprimir el documento.")
      lrc.SetCustomizedString("PrintPreview_Tool_Reduce_Page_Thumbnails", "Achicar miniatura de página")
      lrc.SetCustomizedString("PrintPreview_Tool_Reduce_Page_Thumbnails_AccessibleDescription", "Achica miniatura de página")
      lrc.SetCustomizedString("PrintPreview_Tool_Show_Page_Numbers", "Mostrar la página de la miniatura.")
      lrc.SetCustomizedString("PrintPreview_Tool_Show_Page_Numbers_AccessibleDescription", "Muestra el número de página de la minuatura.")
      lrc.SetCustomizedString("PrintPreview_Tool_Snapshot_Tool", "&Copia área")
      lrc.SetCustomizedString("PrintPreview_Tool_Snapshot_Tool_AccessibleDescription", "Toma una imagen de la vista previa y la copia al portapapeles.")
      lrc.SetCustomizedString("PrintPreview_Tool_Thumbnails", "Miniaturas")
      lrc.SetCustomizedString("PrintPreview_Tool_Thumbnails_AccessibleDescription", "Muestra una miniatura de cada página.")
      lrc.SetCustomizedString("PrintPreview_Tool_Tools", "&Herramientas")
      lrc.SetCustomizedString("PrintPreview_Tool_Tools_AccessibleDescription", "Menú Herramientas.")
      lrc.SetCustomizedString("PrintPreview_Tool_View", "&Ver")
      lrc.SetCustomizedString("PrintPreview_Tool_View_AccessibleDescription", "Menu Ver.")
      lrc.SetCustomizedString("PrintPreview_Tool_Whole_Page", "Página completa")
      lrc.SetCustomizedString("PrintPreview_Tool_Whole_Page_AccessibleDescription", "Ajusta la página para poder verla de manera integra en la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom", "&Zoom:")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom_AccessibleDescription", "Permite indicar el nivel de zoom de la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom_In", "Agrandar")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom_In_AccessibleDescription", "Arganda la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom_In_Tool", "Herramienta para agrandar")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom_In_Tool_AccessibleDescription", "Utiliza el mouse para agrandar la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom_Increments", "Incremento de Zoom")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom_Out", "Achicar")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom_Out_AccessibleDescription", "Achicar la vista previa.")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom_Out_Tool", "Herramienta para achicar")
      lrc.SetCustomizedString("PrintPreview_Tool_Zoom_Out_Tool_AccessibleDescription", "Utiliza el mouse para achicar la vista previa.")
      lrc.SetCustomizedString("PrintPreview_ToolCategory_Context_Menus", "Menú contextual")
      lrc.SetCustomizedString("PrintPreview_ToolCategory_File", "Archivo")
      lrc.SetCustomizedString("PrintPreview_ToolCategory_Menus", "Menus")
      lrc.SetCustomizedString("PrintPreview_ToolCategory_Tools", "Herramientas")
      lrc.SetCustomizedString("PrintPreview_ToolCategory_View", "Vista")
      lrc.SetCustomizedString("PrintPreview_ToolCategory_Zoom_Mode", "Modo de zoom")
      lrc.SetCustomizedString("PrintPreview_ToolTip_ClosePreview", "Cerrar vista previa")
      lrc.SetCustomizedString("PrintPreview_ToolTip_Zoom", "Zoom")


      'http://help.infragistics.com/Help/Doc/WinForms/2012.1/CLR2.0/html/Win_Assembly_Resource_Strings.html
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("CollectionItemCategory", "Ítem")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("CustomPropertiesPageLabelObjects", "Objectos")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("CustomPropertiesPageMenuReset", "Reinicializar")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("CustomPropertiesPageMenuShowDescription", "Mostrar Descripción")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("CustomPropertiesPageMenuShowToolBar", "Mostrar Barra de Herramientas")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("CustomPropertiesPageToolBarModifiedOnly", "Solo Modificados")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("CustomPropertiesPageToolBarObject", "Objectos")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("CustomPropertiesPageToolBarRefresh", "Refrescar")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("DBNullLiteral", "(DBNull)")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_AnchoredReference", "Intento de accesar {0} como una referencia sin anclado")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_ExplicitThis", "{0} - This explicito no soportado")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_ExternalRange", "El rango contiene Referencias Externas")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_FormulaNotSupported", "{0} - Intentó acceder a una fórmula en una referencia que no soporta fórmulas")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_InvalidOperand", "Operando no Invalido")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_InvalidReference", "Referencia invalida o no disponible")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_MethodNotSupported", "{0} no supporta {1}.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_NoCurrentRangeElement", "Sin Elemento de Rango actual")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_NullOperand", "Operando nulo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RangeFromLast", "fromT.No se estableció último")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RangeFromNull", "RefRange: desde es nulo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RangeFromRefBase", "RefRange: from no es un RefBase : {0}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RangeLast", "RefRange Validación: ultima tupla [{0}] != [{1}]")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RangeNormalizeScope", "RefRange Normalizar: mal alcance [{0}/{1}]")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RangeToNull", "RefRange: hasta es nulo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RangeToRefBase", "RefRange: hasta no es un RefBase : {0}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RangeTuple", "RefRange Validación: tupla [{0}] != [{1}]")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RangeValidateCount", "RefRange Validación: cantidad desde {0} != cantidad hasta {1}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_ReadOnlyReference", "{0} - Intento de establecer valor a referencia de sólo lectura")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_ReferenceNotEumerable", "{0} no es una referencia enumerable")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RefMalformed", "{0} - Referencia Malformada {1}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RP_ContainsBase", "RefParser.Contiene - Origen Vacia")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RP_ContainsTarget", "RefParser.Contiene - Destino Vacío")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RP_EmptyElement", "Referencia Inválida {0}. Se encontró un elemente vacío en la ubicación {1}.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RP_EmptyReference", "Referencia Inválida {0}. Referencia vacía.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RP_MalformedExtra", "RefParser Referencia Malformada: Se encontraron multiples [{0}] en [{1}]")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RP_MalformedUnexpected", "RefParser Referencia Malformada: Se encontró un [{0}] inesperado en [{1}]")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RP_MergeRelativeBase", "RefParser.Combinar: Origen es relativo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RP_MissingCloseParenthesis", "Referencia inválida {0}. Falta el parentesis de cierre.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RP_MissingEndQuotes", "Referencia inválida {0}. Falta comillas finales.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_Expected", "RefTuple: Se esperaba [{0}] en [{1}]")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_InvalidScope", "Alcance invalido: {0}.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_InvalidScope_CharactersAfterClosingQuotes", "Se encontró un caracter luego de las doble comillas de cierre en {0} en la ubicación {1}.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_InvalidTuple_CharactersAfterScopeEnd", "Elemento inválido {0}. Se encontró un caracter después del final del alcance.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_InvalidTuple_MissingCloseParenthesis", "Elemento inválido {0}. Falta paréntesis que cierra.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_InvalidTuple_MissingEndQuotes", "Elemento inválido {0}. Faltan las comillas de cierre.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_InvalidTuple_NamePortionEmpty", "Elemento inválido {0}. Porción del nombre del elemento vacía.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_InvalidTuple_ScopeIndexLarge", "Elemento inválido {0}. El índice {1} es invalido: {2}.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_InvalidTuple_UnescapedCharacter", "Caracter {0} sin escape encontrado en {1} en la ubicación {2}.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_NullRefName", "RefTuple: RefName nulo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_RT_Unexpected", "RefTuple: [{0}] inesperado en [{1}]")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_ScopeAllNotLast", "{0} - El alcance All debe aparecer como último elemento {1}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UCErrorCode_Div", "División por cero")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UCErrorCode_Fail", "Fallo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UCErrorCode_NA", "No aplicable")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UCErrorCode_Name", "Nombre inválido")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UCErrorCode_Null", "Valor Nulo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UCErrorCode_Num", "Valor numérico invalido en la función o fórmula.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UCErrorCode_Ok", "Exitoso")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UCErrorCode_Reference", "Referencia inválida o no disponible")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UCErrorCode_Unknown", "Código inválido")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UCErrorCode_Value", "Tipo de argumento u operando incorrecto.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UnexpectedScope", "{0} - Inesperado alcance del Padre {1}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UnknownRange", "Tipo de Rango desconocido")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UnknownRefType", "{0} - RefType desconocido {1}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Error_UnknownScope", "{0} - Alcance desconocido {1}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_About_GraceExpired", "Licenciamiento - Expiró el período de gracia")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_About_InGrace", "Licenciamiento - En período de gracia")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_UltraProdInfo_Expiration1", "Período de gracia ha expirado")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_UltraProdInfo_Expiration10", "Permisos insuficientes")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_UltraProdInfo_Expiration2", "Período de prueba expiró")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_UltraProdInfo_Expiration3", "Período Beta expiró")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_UltraProdInfo_Expiration4", "{0} días de uso / {1} semanas calendario")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_UltraProdInfo_Expiration5", "N/A")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_UltraProdInfo_Expiration6", "Información de licencia inválida")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_UltraProdInfo_Expiration7", "Información de licencia incompleta")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_UltraProdInfo_Expiration8", "{Error}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LDR_UltraProdInfo_Expiration9", "El producto no se instaló correctamente")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LicensedProductActivationGracePrompt", "El período de uso no activo {2} va a expirar ligo de los {0} día(s) de uso or {1} semanas calendario, lo que ocurra primero. Debe activar este producto con el Asistente de Activación de  Producto.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LicensedProductPromptDialogTitle", "Infragistics {0}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("LicensedProductTrialPeriodPrompt", "Esta versión de prueba de {2} expirará luego de ser usado por {0} día(s) o {1} semana(s) calendario, lo que ocurra primero.")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("NewKeyedSubObjectDialog_Cancel", "Cancelar")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("NewKeyedSubObjectDialog_EnterKeyLabel", "&Ingrese la Clave:")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("NewKeyedSubObjectDialog_Ok", "OK")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("NewKeyedSubObjectDialog_Title", "Nuevo {0}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("PropertySetErrorCaption", "Error cargando la propiedad")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TransactionDescription_CustomPropertyPages", "Custom Property Pages")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TrialKey_AboutDialogLabel", "{Prueba}")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_Boolean", "Boolean")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_Byte", "Byte")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_Char", "Character")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_DateTime", "DateTime")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_DateTimeIncrement", "DateTime Incremental")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_DBNull", "DBNull")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_Decimal", "Decimal")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_Double", "Double (punto flotante)")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_I16", "Entero de 16 bit con signo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_I32", "Entero de 32 bit con signo (Int)")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_I64", "Entero de 64 bit con signo (Long)")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_Null", "(null)")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_SByte", "Byte (signed)")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_Single", "Single (floating point)")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_String", "String")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_U16", "Entero de 16 bit sin signo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_U32", "Entero de 32 bit sin signo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("TypeDesc_U64", "Entero de 64 bit sin signo")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("UltraComponentDesignerVerbAbout", "Acerca de")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("UltraComponentDesignerVerbCustomPropertyPage", "Custom Property Pages...")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("UltraPropertyPageCustomPropertyTabCaption", "Object Properties")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("UltraPropertyPageDialogButtonApply", "&Apply")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("UltraPropertyPageDialogButtonCancel", "&Cancel")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("UltraPropertyPageDialogButtonOk", "&OK")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("UltraPropertyPageDialogTitle", "Custom Property Pages")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Value_UCErrorCode_Div", "#DIV/0!")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Value_UCErrorCode_Fail", "#FAIL")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Value_UCErrorCode_NA", "#N/A")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Value_UCErrorCode_Name", "#NAME?")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Value_UCErrorCode_Null", "#NULL!")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Value_UCErrorCode_Num", "#NUM!")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Value_UCErrorCode_Ok", "#OK")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Value_UCErrorCode_Reference", "#REF!")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Value_UCErrorCode_Unknown", "#N/A")
      Infragistics.Shared.Resources.Customizer.SetCustomizedString("Value_UCErrorCode_Value", "#VALUE!")


      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("FormulaError_UnrecognizedFunction", "Nombre de función no reconocido: '{0}'.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("FormulaError_UnsupportedFunction_DateDiff", "El intervalo suminitrado a la función DateDiff ('{0}') no puede ser convertido a una función en Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_BeginExport", "Ocure antes de que comience la exportación de la grilla.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_CellExported", "Ocurre después de que una celda fue exportada a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_CellExporting", "Ocurre antes de que una celda sea exportada a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_EndExport", "Ocurre después de que la grilla terminó de ser exportada.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_FormulaExported", "Se dispara luedo de exportar una fórmula (o se presenta un error al convertir la formula de la grilla a una fórmula de Excel) a una celda de la hoja.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_FormulaExportError", "Se dispara cuando la fórmula de la grilla no puede ser convertida a una fórmula válida de Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_FormulaExporting", "Se dispara antes de exportar una fórmula a una celda de la hoja.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_HeaderCellExported", "Ocurre luego de exportar una celda cabecera a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_HeaderCellExporting", "Ocurre antes de exportar una celda cabecera a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_HeaderRowExported", "Ocurre luego de exportar la cabecera de una fila a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_HeaderRowExporting", "Ocurre antes de exportar la cabecera de una fila a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_InitializeColumn", "Ocurre cuando se inicializa una columna de la grilla.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_InitializeRow", "Ocurre cuando se inicializa una fila.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_RowExported", "Ocurre luego de exportar una fila de la grilla a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_RowExporting", "Ocurre antes de exportar una fila de la grilla a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_SummaryCellExported", "Ocurre luego de exportar una celda de sumarización a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_SummaryCellExporting", "Ocurre antes de exportar una celda de sumarización a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_SummaryRowExported", "Ocurre luego de exportar una fila de sumarización a Excel.")
      Infragistics.Win.UltraWinGrid.ExcelExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridExcelExporter_E_SummaryRowExporting", "Ocurre antes de exportar una fila de sumarización a Excel.")


      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_BeginExport", "Ocure antes de que comience la exportación de la grilla.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_CellExported", "Ocurre después de que una celda fue exportada.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_CellExporting", "Ocurre antes de que una celda sea exportada.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_EndExport", "Ocurre después de que la grilla terminó de ser exportada.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_HeaderCellExported", "Ocurre luego de exportar una celda cabecera.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_HeaderCellExporting", "Ocurre antes de exportar una celda cabecera.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_HeaderRowExported", "Ocurre luego de exportar la cabecera de una fila.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_HeaderRowExporting", "Ocurre antes de exportar la cabecera de una fila.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_InitializeRow", "Ocurre cuando se inicializa una fila.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_RowExported", "Ocurre luego de exportar una fila de la grilla.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_RowExporting", "Ocurre antes de exportar una fila de la grilla.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_SummaryCellExported", "Ocurre luego de exportar una celda de sumarización.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_SummaryCellExporting", "Ocurre antes de exportar una celda de sumarización.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_SummaryRowExported", "Ocurre luego de exportar una fila de sumarización.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("LDR_UltraGridDocumentExporter_E_SummaryRowExporting", "Ocurre antes de exportar una fila de sumarización.")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("UltraGridDocumentExporterActionList_P_AutoSize_DisplayName", "Ajuste autimático de tamaño")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("UltraGridDocumentExporterActionList_P_TargetPaperOrientation_DisplayName", "Orientación del papel")
      Infragistics.Win.UltraWinGrid.DocumentExport.Resources.Customizer.SetCustomizedString("UltraGridDocumentExporterActionList_P_TargetPaperSize_DisplayName", "Tamaño del papel")

      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("AddNewBoxDefaultPrompt", "Agregar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("AllRowsFilteredOut", "0 Ítems.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("ColumnChooserAllBandsItem", "Todos")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("ColumnChooserButtonToolTip", "Presione aquí para mostrar el selector de campos.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("ColumnChooserDialogCaption", "Selector de campos")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("ColumnsUITypeEditorList_None_Entry", "Ninguno")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DataErrorCellUpdateDateNotInMinMaxRange", "Valor inválido: La fecha indicada no se encuentra dentro de los valores de MinDate y MaxDate.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DataErrorCellUpdateEmptyValueNotAllowed", "No se permiten valores nulos en la columna {0}.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DataErrorCellUpdateInvalidDataValue", "Valor inválido")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DataErrorCellUpdateInvalidDateFormat", "Formato de fecha inválido")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DataErrorCellUpdateUnableToConvert", "No se pudo convertir '{0}' a '{1}'")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DataErrorCellUpdateUnableToUpdateValue", "No se pudo actualizar el valor: {0}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DataErrorDeleteRowUnableToDelete", "No se pudo borrar la fila: {0}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DataErrorMessageTitle", "Error de datos")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DataErrorRowAddMessage", "No se pudo agregar la fila: {0}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DataErrorRowUpdateUnableToUpdateRow", "No se pudo actualizar la fila: {0}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DeleteMultipleRowsPrompt", "Ha seleccionado {0} filas para ser borradas. Elija Si para borrar las filas o No para salir.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DeleteRowsMessageTitle", "Borrar filas")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DeleteSingleRowMessageTitle", "Borrar fila")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("DeleteSingleRowPrompt", "Ha seleccionado 1 fila para ser borradas. Elija Si para borrar las filas o No para salir.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("ErrMSgEditorValNotValid", "El valor en el editor es inválido.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Error_Cell_ReadOnly", "La celda '{0}' es de solo-lectura.")

      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterClearButtonToolTip_FilterCell", "Presione aquí para borrar el criterio de filtrado para {0}.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterClearButtonToolTip_RowSelector", "Presione aquí para borrar el criterio de filtrado.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogAllComboItem", "Todas")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogAnyComboItem", "Alguna")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogApplyLabelText", "Filtros aplicados a {0} de las siguientes condiciones:")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogConditionAddButtonText", "&Agregar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogConditionDeleteButtonText", "&Eliminar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogCancelButtonText", "&Cancelar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogDeleteButton_AccessibleDescription", "Borrar la condición seleccionada.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogOkButtonNoFiltersText", "S&ín filtros")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogOkButtonText", "&Aceptar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogTitle", "Filtros personalizados")
      ''Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogAddConditionButtonText", "&Agregar una condició&n")
      ''Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogAndRadio_AccessibleDescription", "Combinar las condiciones con Y lógico.")
      ''Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogAndRadioText", "Condiciones Y")
      ''Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogDeleteButtonText", "Borrar Condición")
      ''Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogOrRadio_AccessibleDescription", "Combinar las condiciones con O lógico.")
      ''Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("FilterDialogOrRadioText", "Condiciones O")

      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("GroupByBoxDefaultPrompt", "Arrastre un encabezado de columna aquí para agrupar por la columna.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("GroupByBoxDefaultPromptMultiBandCardView", "Arrastre un encabezado de columna o etiqueta de la tarjeta aquí para agrupar por la columna.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("GroupByBoxDefaultPromptSingleBandCardView", "Arrastre una etiqueta de la tarjeta aquí para agrupar por la columna.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("GroupByButtonToolTip", "Haga click para cambiar la dirección del orden")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("LDR_ColumnEditorDialog_Add", "&Agregar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("LDR_ColumnEditorDialog_Cancel", "Cancelar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("LDR_ColumnEditorDialog_Members", "&Miembros")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("LDR_ColumnEditorDialog_OK", "Aceptar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("LDR_ColumnEditorDialog_Properties", "&Propiedades")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("LDR_ColumnEditorDialog_Remove", "&Quitar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("LDR_ColumnEditorDialog_Reset", "Reajustar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("LDR_ColumnEditorDialog_ShowDescription", "Mostrar Descripción")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("LDR_ColumnEditorDialog_ShowToolBar", "Mostrar Barra de Herramientas")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Copy_Error_MsgBox_Message", "Error realizando la operación de Copiar. {0} {1}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Copy_Error_MsgBox_Title", "Error al Copiar.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Cut_Error_MsgBox_Message", "Error realizando la operación de Cortar. {0} {1}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Cut_Error_MsgBox_Title", "Error al Cortar.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Delete_Error_MsgBox_Message", "Error realizando la operación de Borrar. {0} {1}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Delete_Error_MsgBox_Title", "Error al Borrar.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Paste_Error_MsgBox_Message", "Error realizando la operación de Pegar. {0} {1}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Paste_Error_MsgBox_Title", "Error al Pegar.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Paste_Error_TooManyColumns", "Los contenidos que están siendo pegados contienen más columnas de las que están disponibles empezando en la celda de anclaje. Los contenidos a pegar contienen {0} columnas mientras que las columnas disponibles desde la celda  de anclaje son {1}.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Paste_Error_TooManyRows", "Los contenidos que están siendo pegados contienen más filas de las que están disponibles empezando en la celda de anclaje. Los contenidos a pegar contienen {0} filas mientras que las filas disponibles desde la celda  de anclaje son {1}.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Redo_Error_MsgBox_Message", "Error realizado la operación de rehacer. {0} {1}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Redo_Error_MsgBox_Title", "Error al Rehacer")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Undo_Error_MsgBox_Message", "Error realizado la operación de deshacer. {0} {1}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCell_Undo_Error_MsgBox_Title", "Error al Deshacer")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCellOperation_Error_ConversionError", "Imposible convertir el valor '{0}' al tipo de dato de la columna: {1}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCellOperation_Error_CrossParentSelection", "La operación no puede realizarse seleccionando padres cruzados.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCellOperation_Error_MsgBox_ContinueQuestion", "¿Continuar con las celdas restantes?")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCellOperation_Error_MsgBox_FurtherInformation", "Más información: {0}")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCellOperation_Error_NoCellsSelected", "No se seleccionaron fechas.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("MultiCellOperation_Error_NonRectangularSelection", "Selección inválida. La selección debe ser rectangular.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_BeyondNextMonth", "Más allá del próximo mes")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_EarlierThisMonth", "A principios de este mes")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_LastMonth", "Mes anterior")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_LastWeek", "Semana anterior")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_LaterThisMonth", "A finales de este mes")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_NextMonth", "Mes próximo")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_NextWeek", "Semana  próxima")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_None", "Ninguno")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_Older", "Anterior")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_ThreeWeeksAgo", "Hace tres semanas")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_ThreeWeeksAway", "En tres semanas")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_Today", "Hoy")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_TwoWeeksAgo", "Hace dos semanas")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_TwoWeeksAway", "En dos semanas")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("Outlook_GroupByMode_Description_Yesterday", "Ayer")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("PropertyPageCaptionGroupsAndColumns", "Grupos y Columnas")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDialogBlanksItem", "(Blanco)")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDialogDBNullItem", "(DBNull)")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDialogEmptyTextItem", "(Texto vacio)")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDialogOperandHeaderCaption", "Operando")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDialogOperatorHeaderCaption", "Operador")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDialogTitlePrefix", "Ingrese el filtro para")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_Contains", "Contiene")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_DoesNotContain", "No contiene")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_DoesNotEndWith", "No termina con")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_DoesNotMatch", "No coincide con")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_DoesNotStartWith", "No comienza con")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_EndsWith", "Termina con")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_Equals", "=")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_GreaterThan", "> ")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_GreaterThanOrEqualTo", ">=")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_LessThan", "< ")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_LessThanOrEqualTo", "<=")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_Like", "Es como (like)")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_Match", "Coincide")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_NotEquals", "!=")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_NotLike", "No es como (not like)")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDown_Operator_StartsWith", "Comienza con")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownAllItem", "(Todos)")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownBlanksItem", "(Blancos)")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownCustomItem", "(Personalizado)")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownEquals", "Igual")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownGreaterThan", "Mayor que")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownGreaterThanOrEqualTo", "Mayor o igual que")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownLessThan", "Menor que")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownLessThanOrEqualTo", "Menor o igual que")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownLike", "Es como (like)")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownMatch", "Coincide con expresión regular")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownNonBlanksItem", "(No blancos)")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterDropDownNotEquals", "No es igual")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterLogicalOperator_And", "Y")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterLogicalOperator_Or", "O")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterPatternCaption", "Patrón de búsqueda inválido")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterPatternError", "Error al analizar el patrón {0}. Por favor ingrese un patrón de búsqueda válido.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterPatternException", "Patrón de búsqueda inválido {0}.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterRegexError", "Error al analizar la expresión regular {0}. Por favor ingrese una expresión regular válida.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterRegexErrorCaption", "Expresión regular inválida.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("RowFilterRegexException", "Expresión regular inválida {0}.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialog_Button_Cancel", "&Cancelar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialog_Button_OK", "&Aceptar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogAverage", "Promediar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogAverage_AccessibleDescription", "Muestra el promedio de valores en la columna.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogCount", "Contar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogCount_AccessibleDescription", "Muestra la cantidad de valores en la columna.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogMaximum", "Máximo")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogMaximum_AccessibleDescription", "Muestra el máximo valores en la columna.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogMinimum", "Mínimo")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogMinimum_AccessibleDescription", "Muestra el mínimo valores en la columna.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogNone", "Ninguno")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogNone_AccessibleDescription", "No muestra información resumida para la columna.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogSum", "Suma")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryDialogSum_AccessibleDescription", "Muestra la suma de valores en la columna.")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryFooterCaption_ChildBandNonGroupByRows", "Resumenes para [BANDHEADER]: [SCROLLTIPFIELD]")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryFooterCaption_GroupByChildRows", "Resumenes para [GROUPBYROWVALUE]")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryFooterCaption_RootRows", "Resumen general")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryTypeAverage", "Promediar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryTypeCount", "Contar")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryTypeCustom", "Personalizada")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryTypeMaximum", "Máximo")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryTypeMinimum", "Mínimo")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryTypeSum", "Suma")
      Infragistics.Win.UltraWinGrid.Resources.Customizer.SetCustomizedString("SummaryValueInvalidDisplayFormat", "DisplayFormat inválido: {0}. Más información: {1}")
   End Sub

End Class
